### ISSUE TITLE
DPL-323 Kanban view for all pipelines [C=M, V=3]

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1032]
**User story**
As a member of a DNAP lab team, I would like to be able to use the equivalent of the Heron 'work in progress' view, but for the pipelines that I work on, so that I can manage my workload and make sure all plates are processed that need to be.

**Who are the primary contacts for this story**
Liz E, Katy

**Acceptance criteria**
- [x] 'In progress' view is made generic, so it can work for any Limber pipeline.
- [x] There are links for all Limber pipelines from the 'Work in progress' dropdown on the home page.

**Related stories**
https://github.com/sanger/limber/issues/1030 will probably result in the query driving the page being updated - doesn't need to clash with this one but be aware of it.

**Additional context**
Liz E said this would be useful for her team, and also that SSRs might find it useful. 
The idea here is to do the minimum possible to extend it to all pipelines, without doing any extra investigation into the details of any specific pipelines. 
Then we can advertise it to relevant customers and gather user feedback, or make further spin-out stories if any obvious problems arise when applying it to other pipelines.

_Technical details_

There is a dropdown on the home page as follows:
<img width="728" alt="Screenshot 2022-03-21 at 15 56 17" src="https://user-images.githubusercontent.com/10407809/159300275-d55bbe67-7dd8-4563-a33f-504bd267514f.png">
Ideally this would list all pipelines, dynamically pulled from config. These buttons pass a parameter through to the page to tell it which pipeline to show. The relevant section of `pipeline_work_in_progress_controller.rb` is here:
```
# TODO: Add 'pipeline_group' or similar to pipeline config ymls, to group related ones together
# So that it can work for all pipelines
heron_pipeline_name_to_configs = {
  'Heron-384' => ['Heron-384 Tailed A V2', 'Heron-384 Tailed B V2'],
  'Heron-96' => ['Heron-96 Tailed A V2', 'Heron-96 Tailed B V2']
}
```
The challenge is that what lab staff think of a 'pipeline' is sometimes represented by more than one key in the pipeline configuration ymls - hence the suggestion in the code snippet above.

**Comment by TWJW-SANGER** [comment]
I am intrigued by "what lab staff think of a 'pipeline' is sometimes represented by more than one key in the pipeline configuration". 
What is the difference between a Limber pipeline and a pipeline for a lab user?
I think this might be relevant for the acceptance crieria.

**Comment by ElizabethEasthope** [comment]
I'm also not clear on what the comment "what lab staff think of a 'Pipeline' "
From my point of view we would be considering the main library creation types at this time.  Using the submission template would be a fine granular look at pipelines, however this may be too focus to give us value.  Sticking to the library creation aspect of the submission templates Limber-HTP-**** e.g Limber-HTP_ISC.  It would be the ISC portion of the submission template which would define the pipeline.

**Comment by TWJW-SANGER** [comment]
I going to hazard an answer to my previous question about "what lab staff think of a 'pipeline' is sometimes represented by more than one key in the pipeline configuration".

I believe this stems from 2 causes - 
i. Pipelines are linear sequences in Limber - that is any "lab" pipeline that splits plates into two or more, or merges multiple plates into one may need to be internally represented as multiple pipelines.
ii. Pipelines have different versions - so when a "lab" pipeline is updated, internally this is managed by creating a new Limber pipeline.

**Comment by KatyTaylor** [comment]
Sorry, I never saw the above two questions (GitHub emails often get lost in the masses!).

Basically, Tom is correct. When there's a branch in a pipeline, we represent it as two pipelines in the config. It doesn't affect the users, it's just an easier way to do it for technical reasons. And yes, we may also have different versions of the pipeline - often we can just update the existing one, but for bigger changes we might make a new pipeline config and then deprecate the old one once we're sure all the samples have finished going through it.

A final reason is that several pipelines are split into separate library prep and multiplexing stages - so these would be represented separately in the config, but I think should be on the same kanban page.

**Comment by harrietc52** [comment]
config/pipelines/bespoke_aggregation.yml and config/pipelines/bespoke_chromium_5p.yml could be grouped?

**Comment by harrietc52** [comment]
Emailed Liz/ Barbora/ Danni saying the initial implementation has been deployed to UAT, and if we could discuss the pipeline groupings in a meeting next week.

**Comment by harrietc52** [comment]
Off the back of Friday's meeting:

- New story for adding user info to Kanban card [DPL-457](https://github.com/sanger/limber/issues/1148) 
- New story for adding filter [DPL-458](https://github.com/sanger/limber/issues/1149)
- New story for more groups [DPL-459](https://github.com/sanger/limber/issues/1150)
- New story to make LCMB own pipeline [DPL-460](https://github.com/sanger/limber/issues/1151)
- New story to archive pipeline "bespoke chrome v2"

Liz is going to check:
- If Custom Metadata and comments work as expected
- How the LCM plate is used, and if some plate purposes are skipped
- If the Aggregation pipeline is still in use, or if it can be archived
- Chromium pipeline and how plates could be grouped. Then add this info to [DPL-459](https://github.com/sanger/limber/issues/1150)
