### ISSUE TITLE
DPL-325 Custom fields on labware [C=L, V=2]

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1034]
**_Implemented via https://github.com/sanger/General-Backlog-Items/issues/193_**

**User story**
As a Heron or DNAP Limber user, I would like to be able to enter information against custom fields on a labware page. The fields would be specific to the labware type. e.g. on a LHTR Cherrypick plate it might show a field called 'Cherrypicking robot'. This will enable me to record more structured information than is available in comments, but also allow flexibility to easily configure more fields if it becomes necessary in the future (configuration of fields can be done through PSD).

**Who are the primary contacts for this story**
Sara, Liz E, Katy

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] I can request for certain fields to be associated with certain labware types in Limber
- [ ] On a labware page in Limber, I can fill in, see and edit the value for those fields

**Additional context**
_More on business value_
Along with https://github.com/sanger/limber/issues/1033, this is intended to replace the use of Trello cards for recording information about the labware, as a building block in the journey to replacing the Trello boards completely.

This is a flexible solution that could be useful straight away as a standalone feature. However, it might not be the best solution for most of the information that's recorded on Trello cards for project Heron. I would recommend instead completing  sanger/limber#1036 and https://github.com/sanger/sequencescape/issues/3569 as it seems like these address the root of the problem, rather than just providing a like-for-like solution. https://github.com/sanger/limber/issues/1033 will also be useful as a simpler way to record ad hoc information. If we are considering implementing this story in order to record some specific information, we should first think about whether there is a better way to record that information.

_Technical suggestions_
The idea was to save these in the plate_metadata table (key-value pairs against the labware), and configure the fields against labware in the purpose config.

**Comment by TWJW-SANGER** [comment]
I would like to be a little clearer on the use cases for these feature/s. 

This story allows a lab user to make & see comments on a specific piece of labware. This recorded information is then useful if a user/lead(?) knows the **individual** labware to look up AND the comments recorded influence how they then process the labware in the lab. 

The alternative features mentioned allow leads(?) to identify labware associated with particular reagent batches or times on robots. This use cases seems to be more about tracing problems back to source after sequencing.

**Comment by JamesGlover** [comment]
Robots are already tracked by the robots themselves - so we should be careful about duplicating that.
