### ISSUE TITLE
DPL-332 Add additional robot for Limber bed verification in the GbS pipeline

### ISSUE THREAD

**Issue by neilsycamore** [sanger/limber#1039]
As R&D (Scott G) we would like to enable a second robot for Limber bed verification for the GbS pipeline ‘GbS PCR1’ to ‘GbS PCR2’ transfer step and to generate the necessary robot barcodes. 
Context:
We’ve been working on enabling some different automation to be used for the GbS pipeline to make it more robust, and need to use Limber to track the process properly as at present. We want to be able to use **Bravo WS7** for this step as well as the current Mosquito HV, with the PCR1 plate on Bed 4 and the PCR2 plate on Bed 6. To get around this issue at the moment we’ve cheated by using some of the Mosquito HV barcodes on the Bravo so there’s no immediate pressure, but it would be good to have the bed verification fully set-up at some point.

Initial story generated from [RT746263](https://rt.sanger.ac.uk/Ticket/Display.html?id=746263)
Subsequent RT [RT786425](https://rt.sanger.ac.uk/Ticket/Display.html?id=786425) outline issues GSU are having.

UAT
Anna K, Ben F (See [RT786425](https://rt.sanger.ac.uk/Ticket/Display.html?id=786425) )

![PXL_20240118_152041165](https://github.com/sanger/limber/assets/115623404/4cc219f1-a171-43b8-8170-0462439a3077)
![PXL_20240118_152048141](https://github.com/sanger/limber/assets/115623404/cacae38e-cec3-428b-a013-f3411ab99adc)
![PXL_20240118_152212842](https://github.com/sanger/limber/assets/115623404/3faab9ec-d7f7-4237-9113-e439f96ad9e4)

**Comment by SujitDey2022** [comment]
Reopened this story as it was identified that the story may not have been implemented. Attaching recent details and a related story to this one.

![image](https://github.com/sanger/limber/assets/115623404/07776b4d-cc1e-49a1-aef8-ab6a3d5f4340)

Additional Related Story: https://github.com/sanger/limber/issues/1480
