### ISSUE TITLE
DPL-376 - Limber - Create merged summary file on PCR XP at end of Duplex Seq and Targeted Nanoseq pipelines

### ISSUE THREAD

**Issue by stevieing** [sanger/limber#1074]
**User story**
As a Team Lead / SSR, we require the ability to merge the named sets of data and be able to relate all data to the original LTN Cherry Pick plate well position within one file, as sample positions change during the course of the process

Named sets:

- [Input amount file - Example_File_A.csv](https://github.com/sanger/limber/files/8729180/Example_File_A.csv)
- [Hamilton driver file - Example_File_B.csv](https://github.com/sanger/limber/files/8729181/Example_File_B.csv)
- [PCR XP concentration file - Example_File_C.csv](https://github.com/sanger/limber/files/8729183/Example_File_C.csv)

The merged file should be populated , presented and downloadable as this set format as regards column order [TNano input order for template for SSR merging.xlsx](https://github.com/sanger/limber/files/8729189/TNano.input.order.for.template.for.SSR.merging.xlsx), in order for the lab team to feed the data into an internal template already present.
 
This information is already present within Limber as these items are uploaded at various stages of process.

**Who are the primary contacts for this story**
Sara W

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Download of the merged file at the PCR XP plate step in the Limber Duplex Seq and Targeted Nanoseq pipelines
- [x] The merged file is populated with the correct data as detailed in the example file and comments below
- [x] The merged file is ordered according to the original sample well within the LDS/LTN Cherry pick plate purpose
- [x] The merged file clearly shows the sample relocation which happened at the AL Lib Dil plate step and continues through to the PCR XP plate step
- [ ] Data in the merged file is accepted into the internal Excel template file without issue.

**Dependencies**
This story is blocked by the following dependencies:
- #1078 
- #1077 

References
This story has a non-blocking relationship with:
- sanger/<repo>#<issue_no.>](https://github.com/sanger/limber/issues/1077)

**Additional context**
See comments below

**Comment by JamesGlover** [comment]
The attachments mentioned in the ticket are missing.

**Comment by JamesGlover** [comment]
Also, what template are they merging into? Is it possible for us to let them skip that step and just generate the output the template gives them?

**Comment by stevieing** [comment]
I know. I have requested them from Emma. I will chase it up this morning.

On 19 May 2022, at 09:54, James Glover ***@***.******@***.***>> wrote:



The attachments mentioned in the ticket are missing.

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sanger_limber_issues_1074-23issuecomment-2D1131426051&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=PioAYl_Zz9lnGwJRms8MsEB0E-grNRW-ut-_gAGl70g&m=aOOEJzT-CVWERH9ns-AvobH9J37nobRAKXsktjysi0jt7UZBnNsbPBZW59BlV1MQ&s=Ku3mZ3lrPkSY55_EqkI4huliv_ihpkn6I4v6x5qQbSs&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAD6ZH6OYH3J2YO4NQ64TUTVKX6UPANCNFSM5WH7Q5QA&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=PioAYl_Zz9lnGwJRms8MsEB0E-grNRW-ut-_gAGl70g&m=aOOEJzT-CVWERH9ns-AvobH9J37nobRAKXsktjysi0jt7UZBnNsbPBZW59BlV1MQ&s=FaI8savVmmiJjbO_a-JRcmYVeYgwYoV51NtUsCck2cM&e=>.
You are receiving this because you authored the thread.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by andrewsparkes** [comment]
File A doesn't align with what the code currently expects to be uploaded, it has an extra column as well as missing columns. e.g. 'Hyb panel' is not an expected column. 'Sub-pool' and 'Coverage' are missing. See app/models/labware_creators/pcr_cycles_binned_plate/csv_file.rb for current upload file columns. This is likely down to differences between Duplex seq and non-MVP Targeted Nanoseq (differences that have not been implemented yet, see https://github.com/sanger/limber/issues/913 where it mentions not needing the sub-pool and coverage columns for targeted nanoseq, vs the MVP story that was implemented https://github.com/sanger/limber/issues/928). Those extra changes away from Duplex seq were not trivial in themselves.
Sub-pool and coverage are persisted for Duplex Seq, and you can see them later in the XP conc file (C).

Need to clarify at what step they expect to download this merged file.

And if the merged file contains the same columns for both pipelines.

**Comment by andrewsparkes** [comment]
Columns expected for both pipelines at the moment (shared code):
```
Well
Concentration (nM)
Sanger Sample Id
Supplier Sample Name
Input amount available (fmol)
Input amount desired
Sample volume
Diluent volume 
PCR cycles
Submit for sequencing (Y/N)?
Sub-Pool
Coverage
```
Which columns are persisted well metadata is set in app/models/labware_creators/pcr_cycles_binned_plate.rb in the after_transfer! method
`fields_to_update = %w[diluent_volume pcr_cycles submit_for_sequencing sub_pool coverage]`

To do something different for the Targeted Nanoseq pipeline vs the Duplex Seq pipeline we'll need to somehow modify the behaviour of PcrCyclesBinnedPlate to have different customer file columns, and validate and persist them.
We'll have to ensure what we persist is passed down in the well metadata to the step where we create the merged file for download (these files created via app/controllers/exports_controller.rb in Limber).

**Comment by andrewsparkes** [comment]
Discussion from meeting on 1st June:
Plan we are thinking of is this:
Customer file download includes hyb panel (bait library) column and potentially other columns that would be needed later for submission.
Customer then fills in certain columns related to them e.g. choice of which samples go forward, volumes and hyb panel choice and returns file to Lab.
Lab staff check and complete file and upload to Limber.
The AL Lib Dil rearrangement is calculated and an auto-submission generated for creation of the next plates up to the XP plate.
The chosen samples proceed to the XP stage.
A new 'merged file' download is made available at that point.
This is ordered by the original stock plate well location, and included the new XP plate and well location, and includes the details specified in the example file supplied above. PSD can extract some of the details from the requests for XP creation.
This file is used by the SSR when generating the submission for ISC/Sequencing.

**Comment by JamesGlover** [comment]
See https://github.com/sanger/limber/issues/1077 as may need to consider change in request graph when finding source wells. Another option would be to use well_links, as this supports different well types. (Ie. not just stock wells).

- Bait library: Could be persisted on the request generated in the submission in #1077 - infrastructure already exists

The current well/current plate columns are intended for use in generating the submission, so should be pulled directly from the XP plate, where this file is generated.

Should consider how we can extend automation at this point, although maybe as additional stories:
1) If we're introducing axlsx as part of #1077, consider value in generating the template directly - although maybe risky if this is going to customers
2) What aspects of the template can we automate?
3) Could we build the submission directly from the uploaded file

More longterm, this feedback/submission loop with the customer is a bit reminiscent of the automation of TOL/Heron stuff. Except we don't have a customer LIMS to communicate back to. However may be worth thinking about ways we could adapt this process from smaller-scale customers. (Such as providing our own interface where customers can see the information, and then provide decisions that help generate the submissions, either directly, or with SSR involvement and advise)

**Comment by andrewsparkes** [comment]
Columns for the merged file to be made available for download from XP plate:
(order file on original well coordinate)

1. Original Plate Barcode (rename to LDS/LTN Stock Plate Barcode?) - from ancestor by plate purpose or by stock_plate method on plate model
2. Well (rename to Original well or to LDS/LTN Stock Well Coordinate?) - from ancestor well or by current LDS/LTN AL Lib plate well
3. Concentration (nM) (of the LDS/LTN AL Lib well) - for well from QC uploaded by lab (see latest_molarity in app/sequencescape/sequencescape/api/v2/well.rb)
4. Sanger Sample Id - from the sample in well aliquot
5. Supplier Sample Name - from the sample in well aliquot
6. Input amount available (fmol) - for well in LDS/LTN AL Lib plate (see calculated method in app/sequencescape/sequencescape/api/v2/well.rb)
7. Input amount desired - from customer uploaded file, stored in well metadata for LDS/LTN AL Lib Dil plate
8. New Plate Barcode (rename to Lib PCR XP Plate Barcode?) - LDS/LTN Lib PCR XP plate barcode
9. New Well ID (rename to Lib PCR XP Well Coordinate?) - Well coordinate e.g. 'D05' from LDS/LTN Lib PCR XP plate barcode (location on plate will have been rearranged after binning step at creation of AL Lib Dil plate).
10. Concentration (ng/ul) (of the LDS/LTN Lib PCR XP plate well) - for well from QC uploaded by lab (see latest_concentration in app/sequencescape/sequencescape/api/v2/well.rb)
11. Hyb Panel - (bait library) from customer uploaded file, stored in well metadata for LDS/LTN AL Lib Dil plate

Care:
There may be more than one descendent plate from the AL Lib, as the customer chooses separate groups of samples to be processed forward. So the same AL Lib well may be transferred into more than one descendant AL Lib Dil -> PCR XP set.

The requirement is about making it very clear which original source plate wells have ended up where in the PCR XP plate, and displaying the concentrations and amounts available and desired.

**Comment by andrewsparkes** [comment]
From the example the template they are loading the merged file data into looks complex, and likely subject to regular changes. For PSD to implement and maintain that template looks like considerable work. Maybe first iteration we go with a download of the merged file as requested to get something working for them as soon as possible.
(They have reported mistakes are being made matching XP plate sample wells back to original wells at the moment).

**Comment by andrewsparkes** [comment]
Fair bit still to do here:
Discrepancies in well.aliquots.first.request being both array and single request, why?
Tests to fix for move from well attributes into request metadata.
Noticed well attribute diluent_volume seems to be being used in hamilton driver file creation in Chromium when it does not seem to be set anywhere for that pipeline (5p Gex, and TCR and BCR dil 2 steps). We have it on request for Duplex Seq and Nanoseq now.
