### ISSUE TITLE
DPL-379 - As developers we need to clarify the changes for the targeted Nano Seq and Duplex Seq pipelines to ensure that we can indentify the work involved so as not to waste developer time

### ISSUE THREAD

**Issue by stevieing** [sanger/limber#1078]
**Description**
As developers we need to clarify the changes for the targeted Nano Seq and Duplex Seq pipelines to ensure that we can indentify the work involved so as not to waste developer time.

**Who the primary contacts are for this work**
Sara W

**Knowledge or Stake holders**
Stef L
Andrew S

**Additional context or information**
This work is linked to the following 2 stories. We are unsure of the scope, the reasoning and the amount of work involved:

- #1074 
- #1077 

The stories themselves contain more information but will require input from the technical lead.

**Comment by andrewsparkes** [comment]
Email from Sara today (30th May). Attempting to arrange a meeting time to discuss stories.

**Comment by andrewsparkes** [comment]
Added lots of details to the 2 linked stories. Set both as medium size, with value 3 as the benefits are limited to the users of the DuplexSeq and Targeted NanoSeq pipelines. The DPL-376 merged file story will help to prevent some errors they've been experiencing with matching up wells, and the DPL-378 story allows them to properly track what they are already doing in the lab around filtering out samples.
