### ISSUE TITLE
DPL-420 Cardinal - re-process banked samples 

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1106]
**User story**
As a Cardinal team member, I would like the ability to re-process tubes that have previously been 'banked' (using the Cardinal cell banking pipeline), and send them down the Cardinal library prep pipeline.

**Who are the primary contacts for this story**
Stephen W, Katy

**UAT tester**
Stephen W (for checking pipeline), Tris (for checking sequencing bit), Marina (for checking warehouse data)

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] I can scan the barcodes of FluidX cryotubes into the sample arraying screen - this is the first step in the Cardinal pipeline, when a 'LCA Blood Array' plate is made. (Currently I think it only accepts tubes that are of purpose 'LCA Blood Vac'. The cryotubes will be of purpose 'LCA Bank Stock', and have FluidX foreign barcodes of format FDXXXXXXXX)
- [ ] The pipeline then proceeds as normal - make sure the same key sample information available as if starting the pipeline using LCA Blood Vac tubes (supplier name contains original tube barcodes, linked to the correct study, collection site is in sample metadata "collected by" field, etc.)

**Additional context**

I think all that is required is to add 'LCA Bank Stock' to the list of 'acceptable_purposes' for the 'limber_cardinal' request type. However, careful end to end testing will be required to check that everything downstream works as expected.

The banked tubes contain PBMCs (cells), while the tubes that normally get scanned into the arraying screen contain blood. The material from the banked tubes will actually be added to the plate at a later step, after PBMC extraction. However, spaces in the array plate will be saved for them. This is the same way in which the 'control' addition currently works (although these are in tubes of type 'LCA Blood Vac', along with the normal blood samples) - see more information about controls here - https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Cardinal+Controls. 

**Questions**

1. Blood aliquoting automation - does it affect this story?

2. Do they need the ability to start the pipeline from the screen of a 'LCA Bank Stock' tube as well as a 'LCA Blood Vac' tube?It would be needed if they wanted to process a plate with _only_ 'LCA Bank Stock' tubes. 
Two options for this would be:
    - add 'LCA Bank Stock' as a valid alternative start to the existing pipeline
    - make an alternative entry point to the pipeline, with 'LCA Bank Stock' -> 'LCA PBMC' - this would be more accurate but less consistent with the other data, and more difficult as the existing submission mechanism would not work.

**Comment by stevieing** [comment]
Closed as Cardinal is no longer active.
