### ISSUE TITLE
DPL-442 - Process Chromium 10X libraries using Bespoke PCR pipeline

### ISSUE THREAD

**Issue by stevieing** [sanger/limber#1129]
**User story**
As a bespoke user we would like several library types added to the Limber-Bespoke-PCR family of templates (including library only templates) so we can manually process different flavours of 10x libraries. These library types include ones that are currently processed down the automated 10x pipelines (3pv3, 5p, TCR, BCR), and some new ones for the future (the ones ending in HT).

**Who are the primary contacts for this story**
Matt M (Bespoke)
Stephen L (NPG)

**Acceptance criteria**
To be considered successful the solution must allow the use of the following library types:
- [ ] Manual Chromium single cell 3 prime v3
- [ ] Manual Chromium single cell 3 prime HT v3
- [ ] Manual Chromium single cell 5 prime v2
- [ ] Manual Chromium single cell 5 prime HT v2
- [ ] Manual Chromium single cell TCR
- [ ] Manual Chromium single cell BCR
- [ ] Manual Chromium single cell BCR HT
- [ ] Manual Chromium single cell TCR HT

These next two do not have the 'Manual' prefix as versions of existing ones without.
- [ ] Chromium single cell surface protein HT
- [ ] Chromium Visium FFPE (this is distinct from the existing "Chromium Visium" library type)

These library types must be available for the following submission templates:

- Limber-Bespoke - PCR
- Limber-Bespoke - PCR - Pool
- Limber-Bespoke - PCR - HiSeq 2500 Paired end sequencing
- Limber-Bespoke - PCR - HiSeq 2500 Single end sequencing
- Limber-Bespoke - PCR - HiSeq 4000 Paired end sequencing
- Limber-Bespoke - PCR - HiSeq 4000 Single end sequencing
- Limber-Bespoke - PCR - HiSeq V4 Paired end sequencing
- Limber-Bespoke - PCR - HiSeq V4 Single End sequencing
- Limber-Bespoke - PCR - HiSeq X Paired end sequencing
- Limber-Bespoke - PCR - MiSeq sequencing
- Limber-Bespoke - PCR - NovaSeq 6000 Paired end sequencing

and for the following Limber pipeline:
- Bespoke PCR (file is bespoke_pcr.yml)

- [ ] Additionally: NPG (speak to Stephen L) need to make a change to the analysis pathway for Chromium to look for the word 'Chromium' anywhere in the library type name, not just at the start. So a small piece of work for NPG to do there. 

**Additional context**
For background, the automated / high throughput Chromium 10 pipelines in Limber are:
- Bespoke Chromium 3pv3
- Bespoke Chromium 5p
- Bespoke Chromium BCR
- Bespoke Chromium TCR

And the manual pipeline is:
- Bespoke PCR

Bespoke Chromium 3pv2 was also manual but not used any more.

**Comment by andrewsparkes** [comment]
Current four Limber pipelines and library types (all expect request type to be limber_chromium_bespoke, and all start with the LBC Cherrypick plate created by aggregation):
1. Bespoke Chromium 3pv3 - library type: Chromium single cell 3 prime v3
2. Bespoke Chromium 5p - library type: Chromium single cell 5 prime
3. Bespoke Chromium BCR - library type: Chromium single cell BCR
4. Bespoke Chromium TCR - library type:  Chromium single cell TCR

Not clear from the requirements above which of those library types are new and should be added to which one of these 4 pipelines.
And not sure I understand the question. Limber uses the combination of request type and library type to determine pipeline, so if they don't match as above you won't get the correct suggested actions.

Otherwise should be just a config change for us (small effort).
NPG would need to know how to process these new library types (down which analysis routes they should go).

**Comment by KatyTaylor** [comment]
And in case it's useful, library types currently associated with the limber_chromium_bespoke request type are:

- Chromium exome
- Chromium single cell 3 prime v2
- Chromium single cell 3 prime v3
- Chromium single cell 5 prime
- Chromium single cell TCR
- Chromium single cell BCR
- Chromium genome
- Chromium single cell
- Chromium single cell CNV
- Chromium single cell ATAC

**Comment by andrewsparkes** [comment]
These all to be added to the bespoke_pcr pipeline in limber, no change to existing high throughput ones.

Want to be able to submit both manual and HT submissions on same samples [needs testing]

**Comment by KatyTaylor** [comment]
Update 01/08/2022 as I'm not here for 3 days.

Draft pull requests:
- https://github.com/sanger/limber/pull/1137
- https://github.com/sanger/sequencescape/pull/3652

I've tested the following:
- running `bundle exec rake record_loader:all` - library types get created in database
- that the new library types appear in the 'library type' dropdown in the bulk submission UI, when any submission templates starting with 'Limber-Bespoke PCR -' are selected

In UAT, the submissions involving these new library types should be more thoroughly tested by an SSR.

**Comment by andrewsparkes** [comment]
Library type usage from Stephen L:

| Chromium exome                       |      772 |
| Chromium genome                      |     7751 |
| Chromium single cell                 |    33466 |
| Chromium single cell 3 prime v2      |     1771 |
| Chromium single cell 3 prime v3      |    10428 |
| Chromium single cell 5 prime         |    15718 |
| Chromium single cell ATAC            |     8104 |
| Chromium single cell BCR             |     3453 |
| Chromium single cell CNV             |      312 |
| Chromium single cell HTO             |      197 |
| Chromium single cell surface protein |     4103 |
| Chromium single cell TCR             |     5200 |
| Chromium Visium                      |     1599 |

**Comment by TWJW-SANGER** [comment]
If UAT requires sample submission or manifest creation of samples please contact the SSR team for help via Rich C.
