### ISSUE TITLE
DPL-445  - Rename ‘Chromium single cell surface protein’ library type

### ISSUE THREAD

**Issue by stevieing** [sanger/limber#1132]
**User story**
To aid clarity could the  ‘Chromium single cell surface protein’ library type be amended to ‘Chromium single cell surface protein (CITE-seq)’

**Who are the primary contacts for this story**
Matt M

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] The library type 'Manual Chromium single cell surface protein (CITE-seq)' should be available for bespoke_pcr, instead of the existing ‘Chromium single cell surface protein’ library type

**Dependencies**
This story is blocked by the following dependencies:
- #1129 

**Additional context**
Other library types contain brackets so this should not be an issue
NB. there will also be a HT version, i.e. Manual Chromium single cell surface protein (CITE-seq) HT

**Comment by KatyTaylor** [comment]
On DPL-442 - https://github.com/sanger/limber/issues/1129 - it has the following:

Chromium single cell surface protein (CITE-seq) HT

- should there be an 'HT' on the end or not?

**Comment by andrewsparkes** [comment]
Both
Chromium single cell surface protein (CITE-seq)
and
Chromium single cell surface protein (CITE-seq) HT

Brackets exist in other library types so that should be fine.
NPG need to know about change.

**Comment by KatyTaylor** [comment]
Updated to add the 'manual' prefix, as per email chain "RE: 10X Genomics LIMS changes for Bespoke"

**Comment by andrewsparkes** [comment]
Decided not to change to add Cite Seq as it might be confusing.
