### ISSUE TITLE
DPL-446 - Track intermediate 10X norm pool tubes

### ISSUE THREAD

**Issue by stevieing** [sanger/limber#1133]
**User story**
Currently a ‘norm’ pool of 5’GEX and 5’TCR/BCR libraries is made by combining stock pools of each flavour.  To fit in with how the process operates in the lab can this be changed so that the final ‘norm’ pool is made from individual ‘norm’ pools for each 10X flavour

**Who are the primary contacts for this story**
Matt M
Lynda, Liz H, Rich C - SSRs who might be able to do UAT for us

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] The final norm pool tube should be made from individual norm pool tubes for each 10x flavour (5p, TCR and BCR).

**Dependencies**
None

**Additional context**
This is not required for the 3p or bespoke pipelines.
Need to understand what labware creators and presenters should be used for the new plate purposes, as unlikely they should be 'final' tube.

**Comment by andrewsparkes** [comment]
Want to go from PS tube to a new tube, then on to LB Lib Pool Norm tube. For 5p, TCR and BCR ht routes.
e.g.
LBC 5p Pool Norm
LBC TCR Pool Norm
LBC PCR Pool Norm

Need to clarify what creator/presenter to use for the purposes. And if quant required.

**Comment by KatyTaylor** [comment]
The transfer from the 'PS tube' to these new norm tubes is simple - no calculations etc required (these are done outside of the LIMS). They will need to record the concentration in the UI though - not sure if this feature is available for all tubes or only certain ones.
