### ISSUE TITLE
DPL-451 Retrospective fails / cancels shouldn't remove data from MLWH

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1141]
**User story**
As NPG and Data QC, I would like any failing / cancelling of plates / wells that is done in Limber to not affect any data that is already in the iseq_flowcell table of the warehouse. This is because deleting data at this stage will break links with NPG tables, and thus cause data integrity issues. Also, it is useful for the data to remain accessible for failure reporting purposes.

Failing / cancelling plates / wells earlier in the process, before the data has reached the iseq_flowcell table, should continue to behave in the same way (removing samples from downstream labware).

**Who are the primary contacts for this story**
@KatyTaylor, @neilsycamore, Sara Stott (Heron lab), Carol Scott (NPG), Ed Jenner (Quality Assurance)

**Who is the nominated tester for UAT**
I think it's OK to test it purely within PSD.
We should communicate the change in behaviour clearly, though, especially to lab teams that use Limber, SSRs, NPG and Data QC.

**Acceptance criteria**
When failing / cancelling a well / plate:
- [ ] ~~If the labware has descendants that are involved in a sequencing batch that has been released, do not remove any data from downstream aliquots, or from the MLWH. (Plate / transfer state should still be updated to 'failed' / 'cancelled' as normal).~~ **UPDATE mail: 1 Nov: Re: Requirements for story DPL-451** If we cancel a plate that is an ancestor of an already existing sequencing batch (it doesn’t matter the state), then we don’t remove the aliquots from Sequencescape, and also we won’t remove them from multilims warehouse because Sequencescape and warehouse are in sync with the same information
- [ ] Otherwise, leave behaviour as it is.
- [ ] Update information text in failing / cancelling UI to make the behaviour clear to users.

**Additional context**
This came out of RT 755844, to try to prevent similar mistakes from happening in the future, and from a meeting on 1/8 between parties affected by that RT.

An alternative solution was also considered, where the failing/cancelling behaviour was more drastically changed to 'flag' rather than delete dodgy wells (in a similar way to 'suboptimal aliquot' behaviour). However, it would involve making code changes to NPG's automated analysis and QC pipelines, as well as affecting reporting of failures, and library prep processes like pooling. It wasn't clear whether the change in behaviour was positive when it came to failing individual wells.

**Comment by TWJW-SANGER** [comment]
Looks good.
One question, in the case where there is related data in the iseq_flowcell table, the plate is cancelled/failed and we inform the users that a descendant has been sequenced, then what if anything could/should happen in the lab?

I guess the question is really what if anything is the process in this scenario for the lab?

**Comment by neilsycamore** [comment]
Question on batch state. If the batch is at pending how would this be handled?

**Comment by neilsycamore** [comment]
I think this should be "Do not remove aliquots if batch is pending"

This is because between being 'pending' and 'released' the aliquots in the labware can be removed. This results in the loading team unable to release the batch AND requires manual intervention by us as the reverting batch utility in SS also doesn't like empty labware.

**Comment by TWJW-SANGER** [comment]
Performance issue detected on testing. Logging added to investigate.

**Comment by emrojo** [comment]
Some work was done also in the integration suite which I was using as well, however would need more work if we want to use it as a general solution that could be applied in the whole project, so I will keep it as a separate branch without merging. https://gitlab.internal.sanger.ac.uk/psd/integration-suite/-/merge_requests/69
