### ISSUE TITLE
DPL-510 Bioscan OKR: Pooling 9216 Samples

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/limber#1173]
**Description**
How can we as PSD pool up to 9216 samples via Limber and Sequencescape? Consider practical issues with Limber UI for scanning/selection of the source plates, with performance of making the pool, with Limber and Sequencescape UIs for viewing the child Tube, the list of parents etc. This will inform what additional stories are required to build this functionality.

**Who the primary contacts are for this work**
PSD

**Knowledge or Stake holders**
Scott T
Emma B

**Additional context or information**
The pooling process is in 2 stages.
Stage 1 is a single 384-well plate into 1 tube (up to 384 samples + controls total)
Stage 2 is up to 24 stage 1 tubes into 1 tube (up to 9216 samples + controls total)
The pooled tube is likely to be cleaned (XP) and normalised as the next steps before export to Traction (i.e. 2 tube stamp steps)

**Comment by TWJW-SANGER** [comment]
The output of this story will be the result of testing this process as much as possible in the UAT environment to identify any performance issues that cause this project to fail, before we implement too much of the logic.

**Comment by harrietc52** [comment]
Learnings
- Can't pool straight of the first plate, as there will be no transfer requests. So doing a straight stamp, and then pool from the stamp, so there are transfer requests
- Can create Tag Groups using an "offset" or `initial`
- Getting timeouts when creating 384's at the same time, so create plate in individual steps

**Comment by andrewsparkes** [comment]
- To generate unique tags across multiple plates for testing we modified the 'generate tag group' UAT action to make use of the 'initial' parameter in the OligoEnumerator class. This allows you to generate tag groups with an offset so you can create tag groups that have different tag sequences.

**Comment by andrewsparkes** [comment]
- UAT test for 24 x 384 samples pooled down into 1 tube with 9216 samples took 36 minutes in total (vs 2hrs on local laptop)
- so workable, but may need some paging in UI screens listing the samples (labware summary in SS)
