### ISSUE TITLE
DPL-569 Bioscan - Limber Library Preparation pipeline configuration

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/limber#1197]
**User story**
Add new pipeline, purpose, robot bed verification and QC file export configs (plus any further changes identified e.g. new or modified labware creators).

**Who are the primary contacts for this story**
Scott T
Emma B

**Who is the nominated tester for UAT**
TBC

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] use of Bioscan library prep pipeline via Limber
- [ ] Bioscan library prep integration test should run

**Dependencies**
This story is blocked by the following dependencies:
NA

**References**
This story has a non-blocking relationship with:
Integration suite test: https://github.com/sanger/General-Backlog-Items/issues/234
Sequencescape pipeline configs: https://github.com/sanger/sequencescape/issues/3704

**Additional context**
This is the Limber part of the Bioscan Library prep pipeline.
See diagram [here](https://lucid.app/lucidchart/b21a6020-df09-4be1-af69-26403ed467a1/edit?viewport_loc=1860%2C1619%2C1885%2C1065%2Cwi47cHrbc6ZW&invitationId=inv_44a43cc4-479b-4e19-924c-2a0182f4255c)

**Comment by harrietc52** [comment]
Removing story from board as referencing story in EPIC issue https://github.com/sanger/limber/issues/1270
