### ISSUE TITLE
DPL-570 Bioscan - Robot bed verification step for Stock plate

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/limber#1198]
**User story**
This simply needs to check that the Stock plate is in the correct robot bed. Scan Stock plate barcode and the bed. Includes set up of new robot for the Beckman non-destructive extraction.

**Who are the primary contacts for this story**
Scott T

**Who is the nominated tester for UAT**
Scott T

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] bed verification of location of Insect Stock plate on Beckman Bioscan robot
- [ ] integration suite test for Insect Lysate prep pipeline should run

**Dependencies**
This story is blocked by the following dependencies:
NA

**References**
This story has a non-blocking relationship with:
Integration test - https://github.com/sanger/General-Backlog-Items/issues/233
Limber pipeline configuration - https://github.com/sanger/sequencescape/issues/3703
Sequencescape pipeline configuration - https://github.com/sanger/sequencescape/issues/3703
Limber bed verification for Stock to Lysate plate - https://github.com/sanger/limber/issues/1199

**Additional context**
This is a small companion story to set up a new robot and bed verification for the new Beckman robot.
See diagram [here](https://lucid.app/lucidchart/b21a6020-df09-4be1-af69-26403ed467a1/edit?viewport_loc=1860%2C1619%2C1885%2C1065%2Cwi47cHrbc6ZW&invitationId=inv_44a43cc4-479b-4e19-924c-2a0182f4255c)

**Comment by harrietc52** [comment]
Removing story from board as referencing story in EPIC issue https://github.com/sanger/limber/issues/1270
