### ISSUE TITLE
DPL-571 Bioscan - Robot bed verification step for Stock to Lysate transfer

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/limber#1199]
**User story**
Add a bed verification for the Stock to Lysate plate transfer. This should follow on from the previous bed verification for the Stock plate and require the same 'robot'. Scan parent Stock and child Lysate plates and their beds.

**Who are the primary contacts for this story**
Scott T

**Who is the nominated tester for UAT**
TBC

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] bed verification for transfer of Insect Stock plate into Lysate plate on Beckman Bioscan robot
- [ ] integration suite test for Insect Lysate prep pipeline should run

**Dependencies**
This story is blocked by the following dependencies:
NA

**References**
This story has a non-blocking relationship with:
Integration test - https://github.com/sanger/General-Backlog-Items/issues/233
Limber pipeline configuration - https://github.com/sanger/sequencescape/issues/3703
Sequencescape pipeline configuration - https://github.com/sanger/sequencescape/issues/3703
Limber bed verification for Stock plate location - https://github.com/sanger/limber/issues/1198

**Additional context**
This is a small companion story to set up a bed verification for transferring the Insect Stock plate into the Lysate plate on the new Beckman robot.
See diagram [here](https://lucid.app/lucidchart/b21a6020-df09-4be1-af69-26403ed467a1/edit?viewport_loc=1860%2C1619%2C1885%2C1065%2Cwi47cHrbc6ZW&invitationId=inv_44a43cc4-479b-4e19-924c-2a0182f4255c)

**Comment by harrietc52** [comment]
DPL-571
Stock Plate bed 9, Lysate Plate P14, & Control Plate P19

**Comment by harrietc52** [comment]
Removing story from board as referencing story in EPIC issue https://github.com/sanger/limber/issues/1270
