### ISSUE TITLE
DPL-577	Heron: Create new ARTIC primer panel

### ISSUE THREAD

**Issue by neilsycamore** [sanger/limber#1204]
**User story**
the Heron lab would like to be able to transition over to a new version (v5.3.2) of the ARTIC panel fairly soon. 
Based on the naming convention previously used, I’ve created a primer panel `nCoV-2019/V5.3.2` in Sequencescape already.

**Who are the primary contacts for this story**
sg21 (primary), nr6, ss50, ag25

**RT story**
Detailed in [RT](https://rt.sanger.ac.uk/Ticket/Display.html?id=765884) with link to NPG RT (detailing what they have done and are ready for the test runs)

**Acceptance criteria**

These need to be performed at the time that the lab would like to switch over, to avoid confusion and mistakes.  The steps have already been performed in UAT, with the exception of the Limber updates.

- [x] Add V5 specific tag groups to SequenceScape using https://sequencescape.psd.sanger.ac.uk/tag_groups/new.
    - [x] i7 tag group:
        - Name: `ARTIC_V5_384_i7`
        - Adapter Type: `TruSeq PCR`
        - List of Oligos: As found on https://sequencescape.psd.sanger.ac.uk/tag_groups/195
    - [x] i5 tag group:
        - Name: `ARTIC_V5_384_i5`
        - Adapter Type: `TruSeq PCR`
        - List of Oligos: As found on https://sequencescape.psd.sanger.ac.uk/tag_groups/194
- [x] Add tag layout templates to SequenceScape.
  - Navigate to https://sequencescape.psd.sanger.ac.uk/tag_layout_templates to see existing templates.
  - Also navigate to https://sequencescape.psd.sanger.ac.uk/tag_layout_templates/new to create new layout templates.
  - [x] Create one new template with (these can't be changed later so don't make typos):
    - Name: `TSsc384-PCR1-nCoV-2019/V5/B`
    - Tag group: `ARTIC_V5_384_i7`
    - Tag2 group: `ARTIC_V5_384_i5`
    - Tag direction: `InColumns`
  - [x] Create another new template, all the same as above except the name is `TSsc384-PCR2-nCoV-2019/V5/B`.
- [x] Confirm the presence of the new tag layouts on https://gatekeeper.psd.sanger.ac.uk/lots/new?lot_type=Pre+Stamped+Tags
- [x] Disable the new tag layout templates until they are needed by the lab.
    - [x] Confirm the absence of the new nCoV-2019 tag layouts on https://gatekeeper.psd.sanger.ac.uk/lots/new?lot_type=Pre+Stamped+Tags
- [ ] Update the config of Limber (attached PR only to be merged when ready to deploy)
  - [x] Update https://github.com/sanger/limber/blob/develop/config/purposes/heron_lthr_384.yml
    - [x] Replace the list at `LTHR-384 Lib PCR 1/tag_layout_templates` with the single item `TSsc384-PCR1-nCoV-2019/V5/B`.
    - [x] Replace the list at `LTHR-384 Lib PCR 2/tag_layout_templates` with the single item `TSsc384-PCR2-nCoV-2019/V5/B`.
  - [x] Update https://github.com/sanger/limber/blob/develop/config/purposes/heron_lthr_entry.yml
    - [x] Change BOTH primer panel names to `nCoV-2019/V5.3.2`

**When the lab are ready to go live:**

- [ ] Re-enable the new tag layout templates in Sequencescape.
    - [ ] Confirm the presence of the new nCoV-2019 tag layouts on https://gatekeeper.psd.sanger.ac.uk/lots/new?lot_type=Pre+Stamped+Tags
- [ ] Deploy the updated Limber package to Production.
- [ ] Disable un-needed nCoV-2019 tag layout templates as selected by the lab managers.
    - [ ] Confirm the absence of those nCoV-2019 tag layouts on https://gatekeeper.psd.sanger.ac.uk/lots/new?lot_type=Pre+Stamped+Tags

**Blocking Issues**
The following block this story from becoming completed:
- https://github.com/sanger/sequencescape/issues/3721

**Additional context**
There will be some initial testing where intervention will be required to change the primer panel on the LTHR-384 RT-Q (update aliquots) this will require an RT ticket to be raised by the Heron team when the RT-Q plate has been created.
Once this has been raised the Heron team can continue progressing the plate through the pipeline.

**Update the primer panel the same day as the RT is raised OR al least within 24 hours**
This will allow continuity in the downstream NPG analysis pipeline
Script to update primer panel is [here](https://gitlab.internal.sanger.ac.uk/psd/data-patch-archive/-/tree/main/patches/2022/1118-update-primer-panel-on-heron-test-plates)

**Comment by sdjmchattie** [comment]
I've emailed the primary contacts asking for information about the tag groups required for these primers to be created.  Once I have these I can create the tag layouts.

**Comment by sdjmchattie** [comment]
I've updated the requirements as a list of actions to take.  I will get the changes made to Limber on a branch, but it won't get merged until we're ready to deploy this.

**Comment by TWJW-SANGER** [comment]
This is now Arctic **5.2.3**
The tag layout set used in v4 is incorrect. Please speak to Neil about which tag set to use - I think it should be the same as V3.

NB. The version of the tag set and the version of the Arctic primer panel are independent variables. So in theory the tag set could be updated without updating the primer panel and vice versa. Can we consider if the versions in the names for the tag sets could be clearer?

**Comment by TWJW-SANGER** [comment]
Duplicate tag layout template V3 and call it V5
Duplicate tag groups V3 and call them V5
Primer name is Arctic 5.2.3

Coordinate with Lab before deploying  the feature making V5 automatically used by Limber.
