### ISSUE TITLE
DPL-662 Bioscan - Create Tube view presenter with panel for 'Export to Traction'

### ISSUE THREAD

**Issue by harrietc52** [sanger/limber#1237]
**User story**
As the lab users responsible for exporting Bioscan tubes into Traction, we would like an 'Export to Traction' button and visual feedback of success or failure to be visible on the XP tube in Limber at the end of the library preparation pipeline.

**Who are the primary contacts for this story**
Andrew S
Harriet C

**Who is the nominated tester for UAT**
TBC

**Acceptance criteria**
To be considered successful the solution must allow:

- [ ] In Limber, create a new Bioscan XP tube view presenter displaying an extra panel with an 'Export to Traction' button and status field to indicate state of export.
- [ ] only after the creation and transfer of the samples into the XP tube, is the button visible (i.e. tube state is 'Passed' for button to be accessible)
- [ ] On clicking this button, a Sequencescape job is created
- [ ] User is prevented from clicking the button multiple times (button is disabled)
- [ ] There is visual feedback to indicate where in the export process we are at (job submitted, export message created, feedback received etc.). Could use a 'export state' here and use it to update GUI panel above
- [ ] If the export process has any errors these are visible to the user
- [ ] Add pagination for displaying list of samples

**Dependencies**
This story is blocked by the following dependencies:
None

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**
Button triggers creation of an asynchronous Sequencescape job (the job in turn creates the compound sample, the mBrave file and the RabbitMQ message to export the compound sample to Traction). See other story.
Status field on the XP tube GUI should indicate state of the export, whether: not started, job submitted, export message created, and imported into traction successfully or not. 
As the job and message queue make progress, we could update either the Tube state itself (unsure that's a good idea) or a separate 'export state' stored in metadata somewhere, and use that state to drive the GUI.
We could also add comments to the tube as we progress, e.g. like logs, and maybe at the end a link to the Traction object created.

**Comment by TWJW-SANGER** [comment]
Just checking - I assume we don't this story for the MVP now?

**Comment by stevieing** [comment]
Closed in favour of #1617
