### ISSUE TITLE
DPL-703	GbS bed verification changes

### ISSUE THREAD

**Issue by neilsycamore** [sanger/limber#1258]
As R&D (Ben) we would like to implement a change to the bed verification steps on the mosquitoes to allow two plates at a time to be processed in two steps to reduce the risk of contamination presently seen in the pipeline.

Currently Short Read have a situation that causes contamination during the bed verification steps on the mosquitoes where 4 96 well stock plates are scanned onto beds 1-4 and the 384 well PCR plate is scanned onto bed 5. Making this a two step process reduces the risk of contamination as this allows for the tips to be changed over an empty position. We are currently working without LIMS support for this stage so would like to implement this ASAP.

**Who are the primary contacts for this story**
Ben F(bf4) James L(jdl)
**Who is the nominated tester for UAT**
Ben F(bf4) James L(jdl)

**Acceptance criteria**

1. Confirm that the new bed requirements are configured in Limber for the GBS bed verification pipeline.
2. Update the corresponding Integration Suite test to match.

**Proposed Option**
Plate name
- Q1 - Q4 = GBS-96 Stock
- 384 = GBS PCR1

Bed verification ID in Limber robots.rb config file is 'mosquito-gbs-96-stock-to-gbs-pcr1'. This story is to modify that existing bed verification as detailed in the following table.

Mosquito Robot Bed Location | Bed Barcode | Old layout in LIMS | New Proposal
-- | -- | -- | --
Bed 1 | 580000001806 | Q1 | Q1
Bed 2 | 580000002810 | Q2 | Q2
Bed 3 | 580000003824 | Q3 | 384
Bed 4 | 580000004838 | Q4 | Q3
Bed 5 | 580000005842 | 384 | Q4

_Acceptance criteria last updated on 03 May 2023 strikethrough in light of new requirements._
~~1. Identify and document alternative process approaches to help resolve the sample contamination concerns~~

~~Current program~~
~~Plate name , LIMS plate name , Example plate barcode , bed , bed barcode~~
~~Q1 , GBS-96 stock , SQPP-5001-K , 1 , 580000001806~~
~~Q2 , GBS-96 stock , SQPP-5002-L , 2 , 580000002810~~
~~Q3 , GBS-96 stock , SQPP-5003-M , 3 , 580000003824~~
~~Q4 , GBS-96 stock , SQPP-5004-N , 4 , 580000004838~~
~~384 , GBS PCR1 , SQPP-17632-N , 5 , 580000005842~~

~~New program 1~~
~~Plate name , LIMS plate name , Example plate barcode , bed , bed barcode~~
~~Q1 , GBS-96 stock , SQPP-5001-K , 1 , 580000001806~~
~~Q2 , GBS-96 stock , SQPP-5002-L , 2 , 580000002810~~
~~384 , GBS PCR1 , SQPP-17632-N , 3 , 580000003824~~

~~New program 2~~
~~Plate name , LIMS plate name , Example plate barcode , bed , bed barcode~~
~~Q3 , GBS-96 stock , SQPP-5003-M , 3 , 580000003824~~
~~Q4 , GBS-96 stock , SQPP-5004-N , 4 , 580000004838~~
~~384 , GBS PCR1 , SQPP-17632-N , 5 , 580000005842~~

~~2. Confirm compatibility of the identified alternative approaches with the program requirements of the pipeline~~
~~3. Confirm the feasibility of the approved solution~~ 
~~4. Identify and document the timeline of implementation of the approved solution~~

References
Story generated from [RT775027](https://rt.sanger.ac.uk/Ticket/Display.html?id=775027)

LIMS Proposal 
[ToR_166 - Mosquito LIMS proposal.pptx](https://github.com/sanger/limber/files/11818106/ToR_166.-.Mosquito.LIMS.proposal.pptx)

**Comment by neilsycamore** [comment]
@andrewsparkes mentioned in Slack: I don't think it's currently possible to split the transfer from parents to the child into two separate stages like that. Limber bed verification is two steps, first validate positions, then transfer everything. So sounds like a research story to start with to work out what could be done.

**Comment by SujitDey2022** [comment]
@TWJW-SANGER I have updated the acceptance criteria based on our previous discussion around this research story.

**Comment by TWJW-SANGER** [comment]
Message from Neha W
_I have been speaking with Lesley and Ian re: LIMS for Mosquito bed verification and there maybe some potential options that will be worth exploring. Therefore, a decision was made to pause the LIMS research story while we look further into these potential alternatives to combining the plates on the mosquito._

Putting story on hold for now.

**Comment by KatyTaylor** [comment]
Pull requests opened in Limber - https://github.com/sanger/limber/pull/1303/files and Integration Suite - https://gitlab.internal.sanger.ac.uk/psd/integration-suite/-/merge_requests/77/diffs
