### ISSUE TITLE
DPL-738 As SSM (Richard R) I would like to reuse existing NovaSeq 6000 pipelines in Limber but submit samples on to the new NovaSeqX sequencing machine.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/limber#1275]
**User story**
As SSM (Richard R) I would like to reuse existing NovaSeq 6000 pipelines in Limber but submit samples on to the new NovaSeqX sequencing machine.

**Who are the primary contacts for this story**
Richard R

**Who is the nominated tester for UAT**
Liz C
Tris B

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Users can take a samples on an existing pipeline process (e.g. GBS) and submit them to the new NovaSeqX machine.
- [ ] Users can still submit samples on these pipelines to NovaSeq 6000, HiSeq 2500 and MiSeq machines.

**Dependencies**
This story is blocked by the following dependencies:
- https://github.com/sanger/General-Backlog-Items/issues/287

**Additional context**
Note the new NovaSeqX has a different flow cell type and different number of lanes per flow cell than the NovaSeq 6000 machines.
It is likely that completing [DPL-711](https://github.com/sanger/General-Backlog-Items/issues/287) will give this feature for free - however this story exists to check that happens, make any modifications needed and test the submission functionality from existing pipelines works as expected.

If it turns out that existing pipelines cannot use a different sequencing machines - we can clone the existing NovaSeq 6000 pipelines and make the changes required to submit to the NovaSeqX under this user story.

**Comment by emrojo** [comment]
Done as part of https://github.com/sanger/General-Backlog-Items/issues/287
