### ISSUE TITLE
DPL-802 Write up an SOP for the Bioscan tag plate generation process

### ISSUE THREAD

**Issue by SujitDey2022** [sanger/limber#1305]
**User story**
As R&D and PSD we would like to document the processes for creating new versions of Bioscan tag layout templates, and for creating instance sets of tag plates. This document would be used by both sides as a reference when new templates and plates are needed.

**Who are the primary contacts for this story**
Emma B
Scott T
Andrew S
Eduardo MR
Abdullah Y

**Who is the nominated tester for UAT**
Scott T for R&D and Eduardo MR for PSD

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] document created and shared, with all parties agreeing on content
- [x] document lists steps required from all parties involved to create:
     - [x] a new version of the tag layout templates e.g. when tags are changed by R&D
     - [x] a set of tag plate instances from a specific version of the tag plate templates for use in the Lab

**Dependencies**
This story is blocked by the following dependencies:
None

References
This story has a non-blocking relationship with:
None

**Additional context**
This story came out of UAT discussion meeting on 27th June 2023.
Aim is to clearly define steps required so that nothing is missed.

**Comment by andrewsparkes** [comment]
Link to draft google doc:
https://docs.google.com/document/d/1EK0dYo_wufDAKDIOdKSIkc51onsBrUO96pHDyJj_DVw/edit?usp=sharing

**Comment by andrewsparkes** [comment]
Will transfer doc into Confluence once approved.
