### ISSUE TITLE
DPL-807 Duplicate Cardinal banking pipeline for 007c

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1310]
**User story**
It would be a good starting point for development of the 007c banking pipeline if we duplicated the Cardinal banking pipeline - then any changes required can be made from there. We should make new plate and tube purposes so that they are easy to distinguish from the Cardinal plate and tube purposes. 

**Who are the primary contacts for this story**
Katy, Lesley

**Who is the nominated tester for UAT**
We can just test this internally as it's a technical story which forms the basis for 007c development.

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Cardinal banking pipeline is duplicated, and given a new name "scRNA core cell extraction"
    - This pipeline can be "disabled" in production for now in the config.
- [ ] Integration Suite test for the above is also duplicated
    - see https://gitlab.internal.sanger.ac.uk/psd/integration-suite/-/merge_requests/84
- [ ] New pipeline uses new plate and tube purposes (similar to Cardinal banking pipeline, but "LCA" prefix replaced with "LRC", for "Limber RNA Core"):
    - _LRC Blood Vac_ (donor vacutainer tubes)
    - _LRC Blood Bank_ (input plate for Hamilton PBMC isolation protocol)
    - _LRC PBMC Bank_ (output plate from Hamilton PBMC isolation protocol / input plate for the cell counting and cell banking protocols)
    - _LRC Bank Seq_ (FluidX tube for freezing and output of cell banking protocol) (name TBC)
    - _LRC Bank Spare_ (FluidX tube for freezing and output of cell banking protocol) (name TBC)
- [ ] In the pipeline, there is a branch where LRC PBMC Bank leads to either LRC Bank Seq or LRC Bank Spare
- [ ] Submission + associated things are duplicated, and given appropriate names
    - see https://github.com/sanger/sequencescape/pull/3894
    - [ ] submission template
    - [ ] request type
    - [ ] (library type should not be needed, as this is not a library prep pipeline)

**Comment by Lesley84** [comment]
1. What should the new pipeline be named? (in Limber - names will be seen and used by developers mostly, but may also appear to users e.g. in the "work in progress view") I'm comfortable with the suggestion of 'scRNA core' otherwise I'll spend too much time overthinking it. 

2. What should the new plate and tube purposes be called? Cardinal ones, for comparison, are:
**LRC Blood Vac (tube)**
LCA Blood Bank (plate) / LCA PBMC Bank (plate) - I assume one of these plates is for the banking workflow and the other for the sequencing pipeline? Do you know which is which?
LCA Bank Stock (tube) - is this the stock tube for the banking workflow?

**Comment by Lesley84** [comment]
Hi Katy, would this approach allow us to vary the number of isolations per donor? and could we run isolations for banking, returns to collaborators, and sequencing on the same plate?

**Comment by KatyTaylor** [comment]
Hi @Lesley84, thanks for the comments.

Thanks for confirming, we'll use "scRNA core" as the name of the pipeline.

"LCA Blood Bank" and "LCA PBMC Bank" are actually sequential in the Cardinal banking pipeline. 

So the blood arrives in "LCA Blood Vac" tubes. These are then aliquoted manually into places on the "LCA Blood Bank" plate. Then the PBMC extraction happens and for some reason there's that extra plate "LCA PBMC Bank" involved, before it gets transferred into the FluidX tubes. If that doesn't sound right to you then it might be worth checking with Stephen W whether:
a) That extra plate is not actually needed and it's something that changed since the initial LIMS development, or 
b) What that extra plate is used for

Yes, "LCA Bank Stock" is the FluidX tube that gets sent to the BioResource team.

Finally, RE isolations:
In Cardinal, when they manually aliquot "LCA Blood Vac" tubes into a "LCA PBMC Bank" plate, they can scan a single tube into any number of well positions in the destination plate. So I think that meets the requirement for multiple / varied number of isolations at that first stage? It definitely complicates matters at the transfer to tube rack stage, but that's in another story (https://github.com/sanger/limber/issues/1314).

**Comment by Lesley84** [comment]
Hi Katy,

Thank you for that explanation that all makes sense.

LRC Blood Vac (donor vacutainer tubes)
LRC Blood Bank (input plate for Hamilton PBMC isolation protocol)
LRC PBMC Bank (output plate from Hamilton PBMC isolation protocol) - this will then become the input plate for the cell counting and cell banking protocols.
LRC Bank Stock (FluidX tube for freezing and output of cell banking protocol.

**Comment by KatyTaylor** [comment]
Update from meeting yesterday:

- Confirmed the same number of tubes and plates used as for Cardinal, and the suggested names are OK.
- Confirmed the requirement for multiple / varied number of isolations per donor is met by the sample arraying screen.

**Comment by LauraLetchford** [comment]
Does the intermediate tube from DPL-844 need to be added in here once it's name is confirmed?

**Comment by KatyTaylor** [comment]
@LauraLetchford I have that as a separate story (https://github.com/sanger/limber/issues/1347) so as to keep this one an easy "duplicate pipeline" story

**Comment by LauraLetchford** [comment]
Ah got you now, that makes sense, thanks!

**Comment by KatyTaylor** [comment]
Update on submission:

We should be able to do an automated submission similar to Cardinal, but instead of specifying a hardcoded study and project in the submission template ("Project Cardinal Combined", for Cardinal), we can use the `autodetect_studies_projects` flag - because all the samples on a plate should be under the same study for 007c Phase 1 (Lesley, in Slack).

(For Phase 2, they may be mixed on the same 10X chip, but that doesn't affect this story as will be a separate submission).
