### ISSUE TITLE
DPL-810 Record PBMC isolation cell count

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1313]
**User story**
As a user of the scRNA Core Banking pipeline, I would like to be able to record the cell count (as produced by the Cellaca instrument) against a PBMC plate, so that:
a) it's available later to send back to collaborators.
b) it can be compared against the equivalent post-thaw data to asses the impact of freeze/thawing and time spent in storage.

**Who are the primary contacts for this story**
Lesley, Katy

**Who is the nominated tester for UAT**
Lesley

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] I can upload a Cellaca output file and the cell count and viability results are saved as qc results against the plate (as in Cardinal banking pipeline).
- [x] (Not MVP but may as well deliver it if easy to copy over) In the failing wells interface, I can see the cell count and viability and use sliders to set a threshold for passes / fails (as in Cardinal banking pipeline).
- [x] (Not MVP but may as well deliver it if easy to copy over) I can download Cellaca input files from the PBMC plate screen (as in Cardinal banking pipeline).

**Dependencies**
This story is blocked by the following dependencies:
- https://github.com/sanger/limber/issues/1310

**Comment by LauraLetchford** [comment]
We'll need to know the cell count to enter in to Titian Mosaic as we have to send this information to collaborators when we send PBMCs back to them. But that won't directly be the cell count from the Cellaca as it is likely that several wells will be pooled into each tube for banking?

**Comment by KatyTaylor** [comment]
@LauraLetchford so if 3 wells (PBMC isolations) are pooled into a single tube for banking, would the number you need just be the sum of the 3 cell counts?

**Comment by LauraLetchford** [comment]
Yes should be sum of the counts for the wells that were pooled into the tube. I think Cellaca file will also contain viability (%) for each well, it would probably make most sense to average the viability for the wells that get pooled in order to give a viability for the tube.

**Comment by andrewsparkes** [comment]
What are the QC thresholds for the cell count well failing step? Set same as Cardinal for now.

**Comment by Lesley84** [comment]
Yes the same as Cardinal
