### ISSUE TITLE
DPL-811 Transfer PBMC isolations into FluidX tube racks

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1314]
**User story**
As a user of the scRNA Core Cell Extraction pipeline, I would like Limber to support the transfer of PBMC isolations into the FluidX tube rack at the end of the pipeline.

**Who are the primary contacts for this story**
Lesley, Katy

**Who is the nominated tester for UAT**
Lesley

**Acceptance criteria**
- [x] Input plate is "LRC PBMC Bank"
- [x] Output is FluidX tubes, in 2 tube racks
- [x] User uploads tube rack scan csv files of the 2 destination tube racks, to tell Limber the destination tube barcodes
    - [x] During upload, user specifies which rack is destined for sequencing, and which for contingency (e.g. two separate labelled upload boxes)
    - [x] Tubes in the sequencing rack become "LRC Bank Seq" tubes
    - [x] Tubes in the contingency rack become "LRC Bank Spare" tubes
- [x] Destination tubes and transfer requests etc. are created in Limber, as per all transfers.
- [x] Failed wells are not transferred.

Transfer logic:
- [x] Transfer is 1:1 - each well in the plate will go into one destination tube
- [x] Labware creator should look at groups of wells that contain the same samples, and...
    - [x] 1 well in each group should go into a "LRC Bank Seq" tube, in the first rack
    - [x] any remaining wells in each group (2 expected) should go into a "LRC Bank Spare" tube, in the second rack
    - [x] If there is only 1 well in the group, the priority is to make a "LRC Bank Seq" tube

Note about reworks:
Sometimes an isolation will fail and will have to be reworked, and they will start again from the LRC Blood Aliquot tube at the start of the pipeline to get more cells. In this case, they may only want to produce "LRC Bank Spare" tubes (as the "LRC Bank Seq" will already have been produced from the first isolation). 
- [x] If they don't upload a rack scan file for the sequencing rack, allow this and only produce "LRC Bank Spare" tubes.

**Dependencies**
This story is blocked by the following dependencies:
- https://github.com/sanger/limber/issues/1310

**Related Stories**
The following are related to this story:
- https://github.com/sanger/limber/issues/1333
- https://github.com/sanger/limber/issues/1333
- https://github.com/sanger/limber/issues/1331

**Additional information**
Although destination tubes are in tube racks, we will probably not represent the tube racks fully in the LIMS - see discussion here - https://github.com/sanger/limber/issues/1333#issuecomment-1682484672

Wireframes showing user experience, using screenshots from a mixture of the two Cardinal pipelines, and notes as to how will differ for this pipeline -https://docs.google.com/presentation/d/1giqhtjqjGErm1iZWbbw4mSLHsNBRSG68S1oAaFsuRlU/edit?usp=sharing 

This is a different process to how it works for Cardinal but it may still be useful to look at how that works, for instance because it also has the tube rack scan upload and the destination labware are FluidX tubes. See documentation for existing Cardinal pooling process here - [Pooling into FluidX tube rack (for cell banking)](https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Cardinal+Pipeline+Documentation#CardinalPipelineDocumentation-PoolingintoFluidXtuberack(forcellbanking))

**Comment by KatyTaylor** [comment]
Basic version:
- 1 source plate, 1 destination rack, upload rack scan, custom pooling - user specifies well-tube mappings

Additional (edge case but needed):
- As above but multiple source plates & LIMS check only one donor per destination tube

Bed verification:
- Check rack barcode is same as the one in the upload file

Future:
- Automatic pooling decisions - when projects are more certain of requirements

Saving data:
- add up cell counting, avg viability, volume (amount picked up * num source wells)

**Comment by LauraLetchford** [comment]
Did we talk about adding logic here to prevent source wells from different samples (original vacutainer barcodes) being pooled into the same fluidx tube?

**Comment by KatyTaylor** [comment]
@LauraLetchford I think we said that would be a requirement when dealing with multiple source plates? I thought I had it in this other story - https://github.com/sanger/limber/issues/1332 - but apparently not, so I will add it. Thanks

**Comment by LauraLetchford** [comment]
thanks Katy, I think it might be required even with one source plate but Lesley will be better placed to make that decision than me.

**Comment by KatyTaylor** [comment]
From meeting just now with Lesley and Abby - 
We need to support 2 destination racks for MVP. 
Validation that all source wells going into a common destination tube have the same original vacutainer barcode - this can be an enhancement rather than MVP.

**Comment by KatyTaylor** [comment]
Custom pooling - relevant code is in:
- limber > app > models > labware_creators > custom_pooled_tubes.rb
- limber > app > models > labware_creators > custom_pooled_tubes > csv_file.rb
- limber > app > models > labware_creators > custom_pooled_tubes > csv_file > header.rb
- limber > app > models > labware_creators > custom_pooled_tubes > csv_file > row.rb

The version for this story will have to support multiple source plates and multiple destination tube racks - but there should be lots of shared functionality with the above.

Mapping file could look something like this:
![Screenshot 2023-08-16 at 12 23 01](https://github.com/sanger/limber/assets/10407809/e11ed790-16a5-4036-956f-1fb2f8b5c6b4)

**Comment by KatyTaylor** [comment]
About to modify this story significantly, so pasting the original text here for reference:

**User story**
As a user of the scRNA Core Banking pipeline, I would like Limber to support the pooling from the "LRC PBMC Bank" plate into the FluidX tube rack at the end of the cell banking process.

**Who are the primary contacts for this story**
Lesley, Katy

**Who is the nominated tester for UAT**
Lesley

**Acceptance criteria**
- [ ] Layouts of destination tube racks are uploaded (tube rack scan csv files) to tell Limber the destination tube barcodes
    - [ ] User specifies which rack is destined for sequencing, and which for contingency (e.g. two separate labelled upload boxes)
    - [ ] Tubes in the sequencing rack become "LRC Bank Seq" tubes
    - [ ] Tubes in the contingency rack become "LRC Bank Spare" tubes
- [ ] Custom pooling: user uploads a spreadsheet with the mapping of source wells to destination tubes (see screenshot in comment)
    - [ ] It can be a many to many mapping - multiple source plates, multiple destination racks
    - [ ] A column specifies which purpose each destination tube will be ("LRC Bank Seq" or "LRC Bank Spare")
- [ ] Destination tubes and transfer requests etc. are created in Limber, as per all transfers.

**Dependencies**
This story is blocked by the following dependencies:
- https://github.com/sanger/limber/issues/1310

**Additional information**
Wireframes showing user experience, using screenshots from a mixture of the two Cardinal pipelines, and notes as to how will differ for this pipeline -https://docs.google.com/presentation/d/1giqhtjqjGErm1iZWbbw4mSLHsNBRSG68S1oAaFsuRlU/edit?usp=sharing 

This is a different process to how it works for Cardinal but it may still be useful to look at how that works, for instance because it also has the tube rack scan upload and the destination labware are FluidX tubes. See documentation for existing Cardinal pooling process here - [Pooling into FluidX tube rack (for cell banking)](https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Cardinal+Pipeline+Documentation#CardinalPipelineDocumentation-PoolingintoFluidXtuberack(forcellbanking))

**Comment by Lesley84** [comment]
Happy with the rewrite :-)
