### ISSUE TITLE
DPL-828 (Deprecated) Additional source plate for transfer into FluidX tubes

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1332]
This has been absorbed back into https://github.com/sanger/limber/issues/1314, as I think it makes most sense to implement them both at the same time.

**User story**
As a user of the scRNA Core Banking pipeline, I would like the option to use an additional source plate in the transfer from the "LRC PBMC Bank" plate to the "LRC Bank Stock" FluidX tubes, to cover the edge case where the wells in the source plate don't contain enough cells to fill a FluidX tube for sequencing.

**Who are the primary contacts for this story**
Lesley, Katy

**Who is the nominated tester for UAT**
Lesley

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] I can scan an additional source plate when doing the transfer from the "LRC PBMC Bank" plate to the "LRC Bank Stock" FluidX tubes
- [ ] The custom pooling takes into account wells from both source plates
- [ ] The Hamilton driver file takes both source plates into account
- [ ] Add logic to prevent source wells from different samples (as indicated by the original vacutainer barcodes) being pooled into the same fluidx tube

**Dependencies**
This story is blocked by the following dependencies:
- https://github.com/sanger/limber/issues/1314

**Comment by KatyTaylor** [comment]
N.B. Cardinal pipeline also had multiple source plates as a requirement but it never got implemented - they actually use a workaround where they pool source wells --> destination tubes 1:1, and then use the poolings/new page in Sequencescape to pool the tubes together. Perhaps this strategy could be used for 007c, since the requirement for an additional source plate is an edge case?

**Comment by stevieing** [comment]
Closed as deprecated.
