### ISSUE TITLE
DPL-830 PBMC isolation bed verification

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1334]
**User story**
As a user of the scRNA Core Banking pipeline, I would like bed verification support for the "LRC Blood Bank" plate to the "LRC PBMC Bank" plate transfer, to try to avoid lab mistakes.

**Who are the primary contacts for this story**
Lesley, Katy

**Who is the nominated tester for UAT**
Lesley

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Robot name: Hamilton PBMC Isolation
- [x] Robot type: Hamilton STAR
- [x] LRC Blood Bank plate is scanned as source plate into bed 15
- [x] LRC PBMC Bank plate is scanned as destination plate into bed 10

**Dependencies**
This story is blocked by the following dependencies:
- https://github.com/sanger/limber/issues/1310

**Comment by Lesley84** [comment]
LRC PBMC Bank plate is scanned as destination plate into bed 12 - this needs to be corrected to bed 10

**Comment by Lesley84** [comment]
I'm happy with this story

**Comment by andrewsparkes** [comment]
Wasn't sure what the acceptance criteria for Robot name was for. Are we setting up a robot in SS?
We have a convention for naming the bed verifications which I've followed.

**Comment by KatyTaylor** [comment]
> Wasn't sure what the acceptance criteria for Robot name was for. Are we setting up a robot in SS? We have a convention for naming the bed verifications which I've followed.

I got the name from the R&D diagram - I'll check in Slack with them
