### ISSUE TITLE
DPL-833 Cell counting bed verification (research needed)

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1335]
**User story**
As a user of the scRNA Core Banking pipeline, I would like bed verification support for the cell counting procedure, to try to avoid lab mistakes.

**Who are the primary contacts for this story**
Lesley, Katy

**Who is the nominated tester for UAT**
Lesley

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Robot name: Hamilton Cell Counting
- [ ] Robot type: Hamilton STAR
- [ ] Source "LRC PBMC Bank" plate scanned into bed 15
- [ ] Destination untracked plates scanned into beds 2, 3, 4, 5

**Dependencies**
This story is blocked by the following dependencies:
- https://github.com/sanger/limber/issues/1310

**Outstanding questions**
How do bed verification if the destination plates are not tracked in LIMS?

**Comment by SujitDey2022** [comment]
Hi @KatyTaylor, wanted to check if this was the story Lesley mentioned is not required as per new requirements.
