### ISSUE TITLE
DPL-878 Driver file for PBMC plate --> FluidX rack transfer

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1362]
**User story**
As a user of the scRNA Core pipeline, I would like Limber to generate a robot driver file for the "LRC PBMC Bank --> FluidX tubes" transfer.

**Who are the primary contacts for this story**
Katy, Abby, Lesley

**Who is the nominated tester for UAT**
Lesley

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Hamilton robot driver file can be downloaded, to tell the robot which transfers to make, between the "LRC PBMC Bank" plates and the FluidX tube racks.

Driver file example, showing layout:
<img width="888" alt="Screenshot 2023-08-17 at 13 31 20" src="https://github.com/sanger/limber/assets/10407809/1fa7753d-5fb1-469a-b66e-d8396a90132e">

N.B. I believe important columns are: Source Plate ID, Source Plate Well, Purpose, Destination Tube Position - if any of the others cause you difficulty, check with Abby or Lesley whether they're needed.

**Dependencies**
This story is blocked by the following dependencies:
- https://github.com/sanger/limber/issues/1314

**Comment by KatyTaylor** [comment]
Relevant code to use for reference:
- limber > config > exports > exports.yml
- limber > app > views > exports > hamilton_lca_pbmc_bank_to_lca_bank_stock.csv.erb

**Comment by KatyTaylor** [comment]
Screenshots showing the an example of prompts that the robot gives the user, telling them which plates to place on which beds:
![hamilton_aggregate_cherrypick_010823 src bed layout](https://github.com/sanger/limber/assets/10407809/d91a38ae-1dd8-417b-ac6e-a46921a47acc)
![hamilton_aggregate_cherrypick_010823 dest bed layout](https://github.com/sanger/limber/assets/10407809/cf31e1e5-e656-45c9-b571-d9ff0cb63a1d)

**Comment by KatyTaylor** [comment]
Updated this story to remove references to multiple source plates, as there will now only ever be one source plate.

**Comment by ac38** [comment]
Will confirm regarding the driver file columns required once the banking protocol is modified but I suspect the shared layout will be okay.
