### ISSUE TITLE
DPL-882 LCMB bed verification changes needed

### ISSUE THREAD

**Issue by neilsycamore** [sanger/limber#1366]
As Team Lead for RNA (Liz E) the bed verification is not yet fully functional for the LCMB line. We need to enable the end prep plate to be in different locations at different places in the prep.

Background
Unfortunately during UAT we tested the steps in Limber, but had no plates in to library create, so wasn’t able to run it alongside.

The first draft had a plate in the wrong place and it was changed, but his has changed the bed for both occasions when the end prep plate is used in the prep.  We need to enable the end prep plate to be in different locations at different places in the prep.

![Screenshot 2023-08-22 at 14 47 52](https://github.com/sanger/limber/assets/299768/8a52a298-93de-4750-86d5-5e1d3bb2151d)

In the format Andrew wrote the steps to me

1
Bravo
Perform Single Transfer
LCMB Cherrypick-Bed 4 : LCMB End Prep –Carriage 1 slot 4

2
Bravo (must scan robot)
LCMB End Prep – Bed 5
[NB. Copy of existing bed verification with id ‘bravo-lb-end-prep’, with LCMB purpose changes]

3
Bravo (check same robot as previous)
Perform single transfer
LCMB End Prep – Bed 7 : LCMB lib PCR – Bed 6
[NB. Copy of existing bed verification for LB, with LCMB purpose changes]

References
Relates to [RT786154](https://rt.sanger.ac.uk/Ticket/Display.html?id=786154)

**Additional context**

**Comment by Sangeetha-Bheeman** [comment]
Screenshots for more clarity of the issue:

<img width="1288" alt="Screenshot 2023-08-30 at 15 06 44" src="https://github.com/sanger/limber/assets/93536758/b37c25f2-d3f4-480b-8c40-97b8b3b65aac">
<img width="1293" alt="Screenshot 2023-08-30 at 15 07 11" src="https://github.com/sanger/limber/assets/93536758/fe5ba64c-7659-4ba3-af5d-a47b2eff49fb">

Links:
https://uat.limber.psd.sanger.ac.uk/robots/bravo-lcmb-end-prep
https://uat.limber.psd.sanger.ac.uk/robots/bravo-lcmb-end-prep-to-lcmb-lib-pcr
