### ISSUE TITLE
DPL-884 Add ability to fail LSW-96 Stock wells

### ISSUE THREAD

**Issue by neilsycamore** [sanger/limber#1368]
As GSLP operational lead (Anna S) I would like to be able to fail LSW-96 Stock plate wells, currently this is only possible at the 384 format RT-Q plate within our RVI/Heron pipeline.

Background
We are in the process of stamping archived deep well (LDW-96 Stock) covid negative samples for RVI. We come across a pierced seal on a daily basis which poses a high risk for contamination and should not be selected for further processing. Our current protocol is to make a comment in SS of the affected wells.
The plan is to consolidate these stamped plates further by cherry-picking on a Tecan. When we come to make the manual submissions we will need to cross check in SS every plate to not select the contaminated wells. We have 17k plates to stamp, to date have transferred ~2k all which will require cross checking.

**Who are the primary contacts for this story**
Anna S

**Who is the nominated tester for UAT**
Anna S

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] option visible in Limber to fail wells
- [ ] Any failed wells will not be selected for any subsequent cherry picking operations.

References
This story raised via [RT785931](https://rt.sanger.ac.uk/Ticket/Display.html?id=785931)

**Comment by TWJW-SANGER** [comment]
Agreed that this is not needed for historic plate stamping....
