### ISSUE TITLE
DPL-908 Consolidate PBMC isolations

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1382]
**User story**
As a user of the scRNA Core Cell Extraction pipeline, I would like the PBMC isolations to be pooled in pairs before cell counting, so that I don't have to do as many runs on the Cellaca (cell counting), as it's time consuming.

**Who are the primary contacts for this story**
Katy, Andrew, Lesley, Abby

**Who is the nominated tester for UAT**
Lesley, Abby

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] New labware creator (on creation of LRC PBMC Bank plate).
    - [x] Looks at a group of source wells that contain the same sample, and groups them into pairs to go into destination wells (number of source wells to be consolidated could be in kept config, for future-proofing).
        - [x] If there are an odd number of source wells, transfer the last one into a well on its own.
    - [x] Ignores any source wells that have been failed (might be standard Limber behaviour).
- [x] Driver file (see example attached in comment).
- [x] Update Integration Suite test if needed.

**Comment by Lesley84** [comment]
We don't need to add new labware the un-pooled plate which was previously the destination plate 'LRC PBMC bank' will now not need tracking in the LIMS and this new pooled plate will now become the 'LRC PBMC bank' plate. However, the bed it's scanned onto will change from 10 to 3.

**Comment by Lesley84** [comment]
Yes we will need a driver file, Abby to add attachment example.

**Comment by ac38** [comment]
[hamilton_lca_pbmc_bank_to_lca_bank_stock_noheader.csv](https://github.com/sanger/limber/files/12671438/hamilton_lca_pbmc_bank_to_lca_bank_stock_noheader.csv)

**Comment by Lesley84** [comment]
3. No additional bed verification required apart from change referenced in question 1.

**Comment by Lesley84** [comment]
4. Process on its own if that's feasible and it will be assumed it's a contingency sample

**Comment by KatyTaylor** [comment]
Pasting previous outstanding questions sections - answered in Lesley's comments above.

1. Which plate is this on? (Undecided at time of writing)
2. Do we need to generate a driver file for this transfer?
3. Do we need a bed verification for this? (If it's part of the isolation protocol, might be a double step?)
4. What if there are an odd number of source wells for a sample? Do we a) use the odd one on its own, b) add it to a pair to make 3, or c) leave it.

**Comment by Lesley84** [comment]
Do you need a fixed pattern or can it be random? Samples will be routinely plated on the parent plate in a fixed pattern. However, there may be edge cases where samples are randomly plated so we need to able to deal with these cases.

At the moment we assume pairs of source wells by sample but we are adding a config to set number of source wells. How does this affect the method in the future? If I've understood correctly I don't think this will be a problem as the sample number should always align with the number of source wells.

If there are odd number wells, e.g., failed or not enough sample for even number, how to arrange wells in the destination, compress to top-left by column, or by row, or something else ? Compress to top left my column :-)
