### ISSUE TITLE
DPL-914 Create tube rack containing banked PBMC tubes

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1388]
**User story**
As a user of the scRNA Core pipeline, I would like to be able to create a plate (that represents a tube rack) in the LIMS that holds tubes containing banked PBMCs, so that I can track it and use it in bed verifications.

**Who are the primary contacts for this story**
Katy, Lesley, Abby

**Who is the nominated tester for UAT**
Lesley, Abby

**Acceptance criteria**
- [x] The LIMS supports the creation of "LRC PBMC Cryostor" tube racks (represented as a plate in the LIMS for now) from a group of "LRC Bank Seq" and "LRC Bank Spare" tubes.
- [x] UX will look like:
    - User goes to tube page
    - Clicks green 'add an empty...' button to go to next labware in pipeline
    - Uploads rack scan to tell Limber which tubes are being transferred into which wells
    - Page checks all tubes exist in the LIMS already - error if not
    - Page checks all tubes have active requests of the correct type (limber_scrna_core_donor_pooling, from https://github.com/sanger/sequencescape/issues/3900)
    - Lands on plate page (user will print out plate barcode and stick on tube rack)
- [x] Update Integration Suite test to include this transfer.

**Comment by Lesley84** [comment]
1) How will they make sure they've got the same selection of tubes as specified on the submission? Tubes will be in FluidX tubes and scanned on a 2D rack scanner. Perhaps discussion to be had as to whether this activity sits within Bioresource or DNAP? 

2) What should the interface look like? **Ideally, the submission will align with the plate layouts of the stored PBMCs for easy retrieval. It would rely on the SSRs having access to the plate rack scan that was used for submission to the Bioresource Team.**

**Comment by andrewsparkes** [comment]
Could we treat this as a kind of manual cherrypick + auto-submission?
Upload a tube rack scan in the Thaw plate labware creator, then auto-submission on the resulting plate?

**Comment by andrewsparkes** [comment]
To raise in UAT:
Would users like an export file download on the plate to list the original tube barcodes?
