### ISSUE TITLE
DPL-915-a Count thawed cells

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1389]
**User story**
As a user of the scRNA Core pipeline, I would like the LIMS to support cell counting on the plate containing the thawed PBMCs. 

**Who are the primary contacts for this story**
Katy, Lesley, Abby

**Who is the nominated tester for UAT**
Lesley, Abby

**Acceptance criteria**
On the output plate of https://github.com/sanger/limber/issues/1483:
- [ ] I can upload a Cellaca output file and the cell count and viability results are saved as qc results against the plate (as in Cardinal banking pipeline).
- [ ] In the failing wells interface, I can see the cell count and viability and use sliders to set a threshold for passes / fails (as in Cardinal banking pipeline).
- [ ] I can download Cellaca input files from the plate screen (as in Cardinal banking pipeline).
Bed verification not needed for MVP.
- [ ] ~Integration Suite test is updated to include this step.~ - split out into https://github.com/sanger/limber/issues/1575

**Comment by Lesley84** [comment]
The plate type here will not be 'LRC PBMC Thaw' as the cells will have gone through a defrosting method and transferred into a fresh plate. Suggestion for the plate name 'LRC PBMC defrost'? 

We don't need the bed verification for here as per phase 1

**Comment by KatyTaylor** [comment]
OK thanks for raising, there may be an extra labware in here that I wasn't aware of. Screenshot from process map below. In the diagram, is "LRC PBMC Thaw" a tube rack or a plate, and does it need to be tracked in LIMS? 

![Screenshot 2023-10-16 at 11 45 28](https://github.com/sanger/limber/assets/10407809/c45580d8-2211-4879-bc51-6dba10572c1e)
