### ISSUE TITLE
DPL-916 PBMC donor pooling - create plate

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1390]
**User story**
As a user of the scRNA Core pipeline, I would like the LIMS to support the pooling of the PBMCs ready to go on the 10X chip.

**Who are the primary contacts for this story**
Katy, Lesley, Abby

**Who is the nominated tester for UAT**
Lesley, Abby

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Input is "LRC PBMC Defrost PBS" plate
- [x] Output is "LRC PBMC Pools" plate
- [ ] Number of pools (destination wells) determined based on number of source samples, ~according to [this table]. (https://github.com/sanger/limber/blob/develop/config/cardinal_pooling.csv)~ Moved to [Y24-007](https://github.com/sanger/limber/issues/1611)
- [x] Do not allow combining of different studies
- [x] Do not allow combining of different projects
- [x] Samples are labelled with 'tag_depth' index to prevent tag clash 
- [x] Requests should be passed and next requests linked up - see 'StateChangers::AutomaticPlateStateChanger'
- [ ] Integration Suite test is updated to include this transfer.
- [ ] TBC - there may be a requirement around collection sites, as with Cardinal, but may not - R&D to check . Moved to [Y24-007](https://github.com/sanger/limber/issues/1611)
- [x] If samples have the same donor_id they should not be pooled in the same well but can be processed on the same plate.

**Assumption**
- Only one chip type is supported in this step.
- Cell counting data does not affect the target number of pools / donors per pool for this step.
- There may be an additional constraint to generate even number of pools, but this is not relevant to new GEM-X chip.

**Additional information**
Probably useful to look at the equivalent step in the Cardinal pipeline:
- Documentation [here](https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Cardinal+Pipeline+Documentation#CardinalPipelineDocumentation-CreatingpoolsforPBMCPoolsplate)
- See class CardinalPoolsPlate

Validation around studies and projects is because:
- Combining studies can be risky from a data protection point of view
- We have been told it is not intended
- There is equivalent validation at the point of creation of compound samples (just prior to sequencing), so we don't want to allow it now if it will be rejected then
- Each pool (compound sample) will be represented by just one study and project (= cost code) in the iseq_flowcell table in the MLWH

**Comment by yoldas** [comment]
Until we have a new lookup table to map number of samples to number of pools, I am using a copy of the cardinal table, which covers number of samples up to 96. From 97 to 160 samples, I am using 16 pools for now. 

FYI, attached image that shows the pattern for the number of pools up to 96 samples. Labels show at which number of samples, the number of pools changes, for example 76 samples => 6 pools, 77 samples => 7 pools.

![number_of_samples_vs_number_of_pools](https://github.com/sanger/limber/assets/91894/dc3a80cf-b534-4ee5-bd0d-e1c05f563a6b)

**Comment by yoldas** [comment]
The integration suite GitLab Merge Request was at https://gitlab.internal.sanger.ac.uk/psd/integration-suite/-/merge_requests/119

They are now merged into the scrna_core_pipeline branch. [MR: Draft: scRNA Core, Phase 2](https://gitlab.internal.sanger.ac.uk/psd/integration-suite/-/merge_requests/111)

It misses a check for driver file download and we do not have the pools input scenario yet.
