### ISSUE TITLE
DPL-918 Extra cell counting step - pooled PBMCs

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1391]
**User story**
As a user of the scRNA Core pipeline, I would like the LIMS to support cell counting on the plate containing the pooled PBMCs. 

**Who are the primary contacts for this story**
Katy, Lesley, Abby

**Who is the nominated tester for UAT**
Lesley, Abby

**Acceptance criteria**
On the LRC PBMC Pools plate:
- Add extra QC barcode labels, as on the 'LRC PBMC Bank' and 'LRC PBMC Defrost PBS' plates (see 'plate_quad_qc' in purpose config)
- Allow upload of Cellaca QC result files, as on the 'LRC PBMC Bank' and 'LRC PBMC Defrost PBS' plates (don't think any development work is needed for this, but should test that it works)

**Additional context**
Generation of driver files for the transfer to the Cellaca plates will not be needed for now, as the exact structure of these is still under discussion.

This story may be replicated in future for the LRC Pools Input plate, but this is still under discussion.

**Comment by Lesley84** [comment]
No, bed verification is not needed :-)

**Comment by Lesley84** [comment]
On further discussion, we're going to drop this step from the pipeline. It's likely we'll cell count in the early days of the pipeline going live to gauge robustness, but we can do this off LIMS.

**Comment by KatyTaylor** [comment]
Update: this is now desired, so I have updated the description and will remove 'deprecated' from the story title.

**Comment by yoldas** [comment]
Upload of Cellaca QC result files, as on the 'LRC PBMC Bank' and 'LRC PBMC Defrost PBS' plates are already tested in integration suite. 

For LRC PBMC Bank, we have two Cellaca counts: FIRST and SECOND. Downloads show which wells to count. The results are uploaded to the page. Generated results are uploaded and they correspond to the wells in downloads.

For LRC PBMC Defrost PBS, all wells are counted. Generated results are uploaded and they are for all wells.

**Comment by yoldas** [comment]
There is some incorrect logic in the description of this story I think. Donor Pooling validation required that cell count must be available on all wells. It is too late to have cell count and upload on this plate, unless it is a re-count. There must be QC on defrost plate before pooling.

**Comment by sabrine33** [comment]
Feedback From Abby: Hi Sabrine,
Thank you for this.
The viability threshold looks good for both.
For the total cell count slider, this is present on the LRC PBMC Defrost PBS plate but missing on the Pools plate (see attached).
Please could this also default to 500000 total cells/ml?
