### ISSUE TITLE
DPL-921 Stamp to cDNA PCR plate

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1394]
**User story**
As a user of the scRNA Core pipeline, I would like LIMS support for the transfer between the GEMs plate and the cDNA PCR plate.

**Who are the primary contacts for this story**
Katy, Lesley, Abby

**Who is the nominated tester for UAT**
Lesley, Abby

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Input plate is "LRC HT 5p GEMs" 
- [x] Output plate is "LRC HT 5p cDNA PCR"
- [x] Straight stamp (no pooling or splitting)
- [x] Bed verification:
    - [x] Hamilton STARlet
    - [x] Input on bed 15
    - [x] Output on bed 5
 - [x] Integration Suite test is updated to include this transfer.

**Additional information**

This should mostly be covered already by the pipeline set up story - https://github.com/sanger/limber/issues/1479 - but leaving this story here to cover the bed verification and for extra testing.

**Comment by yoldas** [comment]
### Config

Pipeline config contains the correct relationships

Excerpt from `config/pipelines/high_throughput_scrna_core_cdna_prep.wip.yml`

```
scRNA Core cDNA Prep:
  relationships:
    LRC HT 5p GEMs: LRC HT 5p cDNA PCR
```

```
scRNA Core cDNA Prep Input:
  relationships:
    LRC HT 5p GEMs: LRC HT 5p cDNA PCR
```

Purpose config contains the correct settings

Excerpt from `config/purposes/scrna_core_cdna_prep.wip.yml`

```
LRC HT 5p GEMs:
  :asset_type: plate
  :stock_plate: false
  :input_plate: false
```

```
LRC HT 5p cDNA PCR:
  :asset_type: plate
  :stock_plate: false
  :input_plate: false
```

After running the Limber `config:generate` task, the purpose config for `LRC HT 5p cDNA PCR` contains the correct labware creator under the UUID section. For development environment, excerpt from config/settings/development.yml

```
:name: LRC HT 5p cDNA PCR
:creator_class: LabwareCreators::StampedPlate
```

TODO
Bed verification
Integration suite

**Comment by yoldas** [comment]
Updates to Integration Suite test on GitLab: [DPL-921 Stamp to cDNA PCR plate](https://gitlab.internal.sanger.ac.uk/psd/integration-suite/-/merge_requests/124)
