### ISSUE TITLE
DPL-922 Transfer into cDNA PCR XP plate

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1395]
**User story**
As a user of the scRNA Core pipeline, I would like bed verification support for the transfer between the cDNA PCR plate and the cDNA PCR XP plate.

**Who are the primary contacts for this story**
Katy, Lesley, Abby

**Who is the nominated tester for UAT**
Lesley, Abby

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Bed verification (`robots.rb`): 
    - [x] Robot: Hamilton
    - [x] Input: LRC GEM-X 5p cDNA PCR plate on bed 13 
    - [x] Output: LRC GEM-X 5p cDNA PCR XP plate on bed 3
- [x] Integration Suite test is updated to include the bed verification.

**Comment by KatyTaylor** [comment]
MVP - no driver file, user enters number of samples
Enhancement - driver file telling robot number of samples, or API call for the same.

**Comment by KatyTaylor** [comment]
Updated in anticipation of the GEM-X decision (1:1 transfer rather than 2:1)

**Comment by KatyTaylor** [comment]
Removed on hold label following decision to go with GEM-X chip.

**Comment by KatyTaylor** [comment]
Taking this out of 'to do' and putting it on hold, because I think there is actually nothing to do for this story until the bed verification details are provided - the actual transfer between plates is already implemented due to the basic pipeline setup (because it's a straight stamp).

**Comment by KatyTaylor** [comment]
This is still not defined but ideally would be in MVP. (V small though!)

**Comment by KatyTaylor** [comment]
Updated with bed numbers so ready to go now.

**Comment by yoldas** [comment]
Integration Suite changes: [DPL-922 PR [Integration] Transfer into cDNA PCR XP plate](https://gitlab.internal.sanger.ac.uk/psd/integration-suite/-/merge_requests/200)
