### ISSUE TITLE
DPL-924 10X PCR binning strategies change

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1397]
**User story**
As a user of the scRNA Core pipeline, I would like Limber to generate a robot driver file for the "10X HT 5' Cherrypick --> 10X HT 5' cDNA Dil" transfer (exact naming to be finalised).

This should be similar to the current 10x pipeline (“LBC Cherrypick --> LBC 5p GEX Dil” transfer/ step to ‘Download Cherrypick to Sample Dilution CSV’) however the current process sets volumes to pick based on concentration and bins samples into either 12 or 14 PCR cycles. For the scRNA pipeline, the volume to pick should be set at 20ul and the range of cycles to bin into should be increased (see additional context for rules).

**Who are the primary contacts for this story**
Lesley, Abby

**Who is the nominated tester for UAT**
Lesley, Abby

**Acceptance criteria**
- [x] Hamilton robot driver file can be downloaded, to tell the robot which transfers to make, between the "10X HT 5' Cherrypick" and “10X HT 5' cDNA Dil” plates.

Driver file example for existing pipeline, showing layout:
![image](https://github.com/sanger/limber/assets/10407809/9d783e14-b207-40b2-bc03-620c229e8373)

- [x] The samples in the "10X HT 5' Cherrypick" plate should be binned for PCR into different columns across the “10X HT 5' cDNA Dil” plate according to their concentrations (see table in ‘Additional context’ for details).
- [x] The new positions should be displayed to the user in Limber on the “10X HT 5' cDNA Dil” plate page and ordered so that each column only allows one number of PCR cycles (see Additional context’ for an example in a pre-existing line).
- [x] The new well locations should be captured in the ‘Destination Plate Well’ column of the driver file.
- [x] The ‘Sample Vol’ column should be set to ‘20’ and ‘Dilution Vol’ to ‘0’ for all samples.
- [x] Integration Suite test is updated

**Dependencies**
Blocked by:
- https://github.com/sanger/limber/issues/1444 

**Additional context**
Table of corresponding sample concentrations and PCR cycles. **We still need to determine the exact cycle numbers where a range is given. I will update you once we know.**
![image](https://github.com/sanger/limber/assets/10407809/8b91c31d-c1e6-4203-8e60-b1da1d60c6ee)

Image of an existing line sharing similar logic:
![image](https://github.com/sanger/limber/assets/10407809/16c08647-61f2-4191-bbaa-b9cde4767e35)

**Comment by ac38** [comment]
Hi Katy,
For the existing line, they need to be able to support both binning routes. Eventually the original method may fall out of use (determined by which 10x kit Faculty use for their sample prep) but they will need both options available for some time. Faculty should be able to let the SSRs know which kit has been used at sample submission though and therefore which line to go down.

**Comment by KatyTaylor** [comment]
Thinking that it would make sense to duplicate the pipeline and add 'HT' into all the purpose names. This story would be just relevant in the 'HT' pipeline. Just the 5' pipeline --> 5' HT for now.

**Comment by andrewsparkes** [comment]
Wondering if we can modify the existing labware creator for binning for PCR cycles to be useable for this (possibly with additional purpose config options for the changed rules) rather than duplicate it.

**Comment by KatyTaylor** [comment]
If GEM X kit is used, numbers in table / volume might change but overall strategy is the same.

**Comment by andrewsparkes** [comment]
Integration suite test branch PR here:
https://gitlab.internal.sanger.ac.uk/psd/integration-suite/-/merge_requests/128

**Comment by KatyTaylor** [comment]
TO DO: generate data to allow Abby to test this step.

**Comment by KatyTaylor** [comment]
UAT notes from Abby:

> I created SQPU-85893-C from this cherrypick plate. Attached is the concentration file. What strategy is it currently using to bin the samples (pic attached)? For GEM-X I know we haven't specified the exact cycle numbers but there should only be 6 options total. Is it helpful to set a number for now and then change it later?
For the 'hamilton_lrc_ht_5p_cherrypick_to_lrc_ht_5p_gex_dil' driver file, the sample vol should be set to '10' for GEM-X (and same thing with name changes to replace 'HT'. 

Concentration file used for above UAT - [concentrations_ngul (3).csv](https://github.com/sanger/limber/files/15482242/concentrations_ngul.3.csv)

Screenshot from above UAT:
![image (2)](https://github.com/sanger/limber/assets/10407809/c06f4586-ad8d-47a1-bfe5-186212a31c44)


Note from Katy:
- Sample volume needs to be updated to '10' rather than '20' - this is a change in requirement due to the GEM-X chip.
- Config in [config/purposes/scrna_core_cdna_prep.wip.yml](https://github.com/sanger/limber/pull/1673/files#diff-f13aa1c4920621203e7d6d381cdd227084b4a90b48432f6380477ae5ecdc9650) should be changed to match bins in screenshot in story description - although the table shows a range for PCR cycles (e.g. 14-16) and a single number will have to be guessed (needs to be tested in the lab before the 'correct' number can be decided).

**Comment by KatyTaylor** [comment]
Moving this to done as Abby is happy with it. PR mentioned in above comment is merged and tested. The PCR cycle numbers in the config will probably need to be changed once R&D have figured out what numbers they'd like - Abby to let us know when that change is needed.
