### ISSUE TITLE
DPL-929 [Limber] Add new 'tag swap' tag template

### ISSUE THREAD

**Issue by neilsycamore** [sanger/limber#1405]
As Head of Short Read Sequencing Services (Rich R) I would like a new tag template added to Limber to enable the use of a large amount of (at present on hold) index plates across all our short read library prep lines that have a tag swap in them. 

Presently there are tag plates associated with tag template TS_pWGSC_UDI96 where oligos with map ids 60 and 61 are swapped [this is for both i5 (tag group id 200) and i7 (id 201)]

In [RT788165](https://rt.sanger.ac.uk/Ticket/Display.html?id=788165) new tag groups were created to account for this swap.
![Screenshot 2023-09-21 at 14 11 16](https://github.com/sanger/limber/assets/299768/128dc926-8265-40da-aefe-aa4eb9402b4a)
We now need a new tag template created with name 'TS_pWGSC_UDI_tag60_61_swap' and added to limber config/purpose files where TS_pWGSC_UDI96 appears.

**Who are the primary contacts for this story**
Jamie L (jdl)
Rich R

**Who is the nominated tester for UAT**
Jamie L (jdl)

**Acceptance criteria**
To be discussed with Jamie L (jdl)

Further details and discussion in [RT788165](https://rt.sanger.ac.uk/Ticket/Display.html?id=788165)

**Comment by andrewsparkes** [comment]
Added to following pipeline config files (where TS_pWGSC_UDI96 currently appears):

- config/purposes/combined_lcm_dna_and_rna_seq.yml (DNA and RNA Lib PCR)
- config/purposes/duplex_seq.yml
- config/purposes/heron_lthr_96.yml (Lib PCR 1 and 2)
- config/purposes/heron.yml (legacy pipeline but added anyway)
- config/purposes/lcmb.yml
- config/purposes/scrna.yml
- config/purposes/targeted_nanoseq.yml
- config/purposes/wgs_isc_top.yml
