### ISSUE TITLE
DPL-938 - As an R&D scientist I would like the bed verifications for the in-house Bait Capture library preparation pipeline for RVI to be implemented

### ISSUE THREAD

**Issue by stevieing** [sanger/limber#1407]
**User story**
As an R&D scientist I would like the bed verifications for the in-house Bait Capture library preparation pipeline for RVI to be implemented

**Who are the primary contacts for this story**
Di / Scott / Steve

**Who is the nominated tester for UAT**
Di / Scott

**Acceptance criteria**
To be considered successful the solution must allow:

- [ ] New BCL pipeline bed verifications are useable

**In Limber:**

- [ ] Update robots.rb bed verification config to create BCL bed verifications with correct purposes names

**In Integration Suite:**

- [ ] Update BCL test to include robot bed verification steps and confirm test runs successfully (see _fill_in_robot_ code in steps in existing pipelines for examples)

**Dependencies**
This story is blocked by the following dependencies:
- sanger/sequencescape#3897
- sanger/sequencescape#3895
- sanger/sequencescape#3902

**Additional context:**

[TBC may turn into a 2 step process which would require different bed verifications]
1. Bravo
state change
RVI cherrypick : Bed 8

2. Bravo?
state change
RVI cherrypick : Bed 8

3. Bravo?
state change
RVI cherrypick : Bed 8

4. Bravo?
transfer
RVI cherrypick: Bed 8 
RVI cDNA XP : Carousel 4,3

5. Bravo
transfer?
RVI cDNA XP: Bed 8
RVI Lig Bind: Carousel 3,5

6. Bravo?
transfer or state change?
RVI cDNA XP: Bed 5
[process map shows RVI lig bind. Think this can be removed?

7. Bravo?
8. transfer
RVI Lig Bind : Bed 7 
RVI Lib PCR : Bed 6

8. Hamilton
9. transfer
RVI Lib PCR : Bed 7 
RVI Lib PCR XP : Bed 9
+
RVI Lib PCR : Bed 12 
RVI Lib PCR XP : Bed 14
(if 2-plate protocol)

10. ??
transfer
RVI Lib PCR XP 1 : Bed 2
RVI Lib PCR XP 2 : Bed 5
RVI Lib PCR XP 3 : Bed 3
RVI Lib PCR XP 4 : Bed 6
RVI Hyb : Bed 4

11?
transfer
RVI Hyb : Bed 4
RVI Cap Lib : Carousel 1,3

12. optional Bravo?
transfer
RVI Cap Lib : Bed 4 
RVI Cap Lib PCR : Carousel 4,5

13. ?
transfer
RVI Cap Lib PCR : Bed 7 
RVI Cap Lib PCR XP : Bed 9
+
RVI Cap Lib PCR : Bed 12 
RVI Cap Lib PCR XP : Bed 14
(if 2-plate protocol)

14. ?
transfer
RVI Cap Lib PCR XP : Bed 4 
RVI Cap Lib Pool : Bed 2

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional Context**

[Lucid Chart showing LIMS steps](https://lucid.app/lucidchart/c1a5c6a6-f4d4-4cfe-b216-e5a8e9dc34ce/edit?viewport_loc=-1348%2C-774%2C2367%2C1395%2C0_0&invitationId=inv_14681694-a000-47a8-bca7-104cf2537d80)

**References**

- sanger/general-backlog-items#334

**Comment by andrewsparkes** [comment]
For the bed verifications that are tracking state changes of the same plate, is determining those state changes and coding them part of this story or the main pipeline story?
Ben will likely need help with setting up the state changes, Eduardo or Katy can help, or myself if available.
Doing the bed verification would transition the labware through the state change. The plate purpose config I think will need to specify a state changer class (in Limber) to be used. And you would want the presenter for the purpose to only display the buttons relevant to that state (i.e. so it does not show all the bed verification buttons at once, and doesn't show the Add child green button till you've transitioned through to the final state).

**Comment by BenTopping** [comment]
> @BenTopping Would you please link the PR?

This work has already been merged in to develop but there is an additional [small PR here](https://github.com/sanger/limber/pull/1478) which adds an additional bed verification.

**Comment by BenTopping** [comment]
Closing as in done
