### ISSUE TITLE
DPL-944 - Bioscan - Create v3 of Bioscan tags

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/limber#1416]
**User story**
As R&D we have developed v3 of the Bioscan tags and would like to be able to use them in the pipeline. v3 tag index files supplied.

**Who are the primary contacts for this story**
Emma B

**Who is the nominated tester for UAT**
Emma B

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] use of v3 tag templates to Limber purpose config
- [ ] use of v3 tags in Limber mBrave file creation
- [ ] creation of Bioscan v3 tag plates

**Dependencies**
This story is blocked by the following dependencies:
None

References
This story has a non-blocking relationship with:
None

**Additional context**
**Time sensitive**: v3 Tag plates to be used w/c 23rd October in Limber Bioscan pipeline

Modify mBrave.yml to include v3 tags and groups
Modify config/purposes/bioscan.yml to include v3 templates

Generate v3 tags and tag groups and templates via script (ask EMR) - DONE

Files:
[BIOSCAN Forward Indexes V3.csv](https://github.com/sanger/limber/files/12891881/BIOSCAN.Forward.Indexes.V3.csv)
[BIOSCAN Reverse Indexes V3.csv](https://github.com/sanger/limber/files/12891882/BIOSCAN.Reverse.Indexes.V3.csv)

**Comment by emrojo** [comment]
Also in gilab: /psd/integration-suite/-/merge_requests/99
