### ISSUE TITLE
DPL-971 Create 007c version of 'Bespoke Chromium 5 prime' pipelines

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1444]
**User story**
Duplicate the 'Bespoke Chromium 5 prime' pipeline in Limber, but with new purposes containing the word 'GEM-X'. This is so we can make the change in https://github.com/sanger/limber/issues/1397 in just the GEM-X version, and so that plates going down the GEM-X route can be distinguished visually from plates going down the standard route. In the future, we will probably want 'GEM-X' versions of the other Chromium pipelines (3', BCR, TCR), but just make the 5 prime version for now.

**Who are the primary contacts for this story**
Katy, Lesley, Abby

**Who is the nominated tester for UAT**
It can be tested along with https://github.com/sanger/limber/issues/1397 when that's ready.

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Replace references to 'HT' in new aggregation pipeline, purposes, submission templates etc. with references to 'GEM-X' - see this PR - https://github.com/sanger/limber/pull/1673/files - for the scope.
- [ ] 'Bespoke Chromium 5p' pipeline is duplicated, and called 'Chromium GEM-X 5p'.
  - [ ] Purposes are:
      - [x] LRC GEM-X 5p Cherrypick (new)
      - [x] LRC GEM-X 5p Dil (new) [We named this as LRC GEM-X 5p GEX Dil]
      - [x] LRC GEM-X 5p Frag 2XP (new)
      - [x] LRC GEM-X 5p LigXP (new)
      - [x] LRC GEM-X 5p PCR 2XP (new)
  - [x] Library type is 'Chromium single cell 5 prime GEM-X v2' (new)
  - [x] Request type is 'limber_chromium_gem_x' (new) [We named it as limber_scrna_core_chromium_gem_x_5p]
  - [ ] New submission template - 'Limber - GEM-X Chromium' (plus standard variants including multiplexing and sequencing) [We named this as Limber-Htp - scRNA Core Chromium GEM-X]
- [ ] 'Bespoke Chromium 5p MX' multiplexing pipeline is duplicated, and called 'Chromium GEM-X 5p MX'. [See config/pipelines/bespoke_chromium_5p.yml in Limber]
  - [x] Purposes (all new except final) are:
      - LRC GEM-X 5p GEX PCR 2XP
      - LRC GEM-X 5p GLibPS
      - LRC GEM-X 5p Pool Norm
      - LB Lib Pool Norm (existing)
  - [x] No library type
  - [x] Request type is 'limber_multiplexing' (existing)
- [ ] Integration Suite test for this new pipeline
- [ ] Plates from the cDNA Prep pipeline (output of https://github.com/sanger/limber/issues/1395), and cDNA plates coming straight from faculty (https://github.com/sanger/sequencescape/issues/3937) should be able to enter this GEM-X pipeline.
- [x] Verify library type name version suffixes. The v3 (5 prime) and v4 (3 prime) suffixed were added. [Discussed over emails. Our changes are fine.]

**Additional context**
At some point after the GEM-X pipeline is set up, the library type 'Chromium single cell 5 prime HT v2' should probably be removed from the 'Bespoke Chromium 5p' pipeline? **Is this comment still relevant after the change from 'HT' to 'GEM-X'?**

When we renamed the Library Type names from HT to GEM-X. We were not sure about the suffixes at the end of the name. We have incremented the versions to v3 and v4 now. Slack Thread: https://sanger-global.slack.com/archives/C05F21NKATD/p1718119423377069
```
Chromium single cell 5 prime GEM-X v3
# Chromium single cell 3 prime GEM-X v4
# Chromium single cell BCR GEM-X
# Chromium single cell TCR GEM-X
```

**Comment by KatyTaylor** [comment]
Ideas from Andrew for bed verification on aggregation steps:
- robot bed verification config file allows an array of purposes for a bed
- Allow "LRC HT 5p cDNA PCR XP" and "LRC HT 5p cDNA Input" as inputs?
- Allow "LRC HT 5p Aggregate" and "LRC HT 5p Cherrypick" as outputs (to allow them to skip the aggregation step if wanted)?

**Comment by andrewsparkes** [comment]
Ticked off some checkboxes for config that got created as part of the DPL-924 story.

**Comment by KatyTaylor** [comment]
Updated description, anticipating the decision to go with the GEM-X chip rather than the HT chip.

**Comment by KatyTaylor** [comment]
Removing on hold label following decision to go with the GEM-X chip. Also discussed whether to provide option to skip aggregation and cherrypicking steps - decided not.

**Comment by yoldas** [comment]
I have done the name change for the below in the story DPL-919 #1392 . They are within the scope of the DPL-919 PR #1673 referred by the first criterion. 

LRC GEM-X 5p Chip
LRC GEM-X 5p GEMs
LRC GEM-X 5p cDNA PCR
LRC GEM-X 5p cDNA PCR XP
LRC GEM-X 5p cDNA Input
LRC GEM-X 5p Aggregate
LRC GEM-X 5p Cherrypick
LRC GEM-X 5p GEX Dil
limber_scrna_core_chromium_gem_x_5p_aggregation
hamilton_lrc_gem_x_5p_cherrypick_to_lrc_gem_x_5p_gex_dil
limber_scrna_core_chromium_gem_x

**Comment by KatyTaylor** [comment]
PRs:

SS - https://github.com/sanger/sequencescape/pull/4157
Limber - https://github.com/sanger/limber/pull/1733
Int Suite - https://gitlab.internal.sanger.ac.uk/psd/integration-suite/-/merge_requests/136
