### ISSUE TITLE
DPL-1010 Change robot for GBS PCR1 plates

### ISSUE THREAD

**Issue by neilsycamore** [sanger/limber#1480]
As GSLP Team lead (Ruth W) The robot that is listed at the GBS PCR1 step is a Mosquito however in reality we use a Bravo.
Could this be reflected in the LIMS please as we are unable to perform bed verification without this in place.
![limber_bravo_mosi](https://github.com/sanger/limber/assets/299768/8b93e8a9-494a-4932-a774-94a08bc0132b)

**Who are the primary contacts for this story**
Ruth W

**Who is the nominated tester for UAT**
Ruth W

**Acceptance criteria**
To be considered successful the solution should:
Display: Bravo  GBS PCR1 =>  GBS PCR2

References
[RT792578](https://rt.sanger.ac.uk/Ticket/Display.html?id=792578)

**Comment by neilsycamore** [comment]
Functionality was added to limber in story https://github.com/sanger/limber/issues/1039

**Comment by andrewsparkes** [comment]
Yes confirmed, Bravo option exists in the Limber configs now.
