### ISSUE TITLE
DPL-1011 Re-use of tube racks

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1482]
**Description**
In the scRNA Core pipeline, the frozen PBMC tubes will be sent from the BioResource team to SeqOps in a tube rack, along with a rack scan detailing the positions of the tubes in the rack. We will need to track this tube rack in Limber, in order to provide a bed verification for the subsequent thawing protocol. 

The UX is planned to be as follows:

1. SSR makes submission on the tubes 
2. Lab staff goes to the page of one of the tubes, clicks 'Add an empty...' green button
3. Intermediate page allows them to upload a rack scan + checks all the tubes exist in the LIMS and have active submissions
4. Resulting tube rack / plate is created

We could represent the tube rack as a plate here quite easily. The etched tube rack barcode could be saved against the plate as a 'foreign barcode'. However, if that tube rack was reused (with different tubes) in the future, this would cause problems, as Sequencescape would not allow the creation of a second plate with the same barcode. 

Another option is to print out a new plate barcode and stick it on the tube rack, and then generate a new barcode for it when it is reused. However, there are problems this could cause in the lab - labels falling off, the etched barcode still being visible on the bottom of the rack, etc.

Can we find a way to represent tube racks properly, allowing reuse with different tubes, while retaining the history of the tube rack - which tubes it used to contain:
- do we need any changes to the data model?
- how would the tube rack and tube screens look?
- how much work would it be?
- do we need to also add a feature to allow 're-arraying' of tube racks?
- should the rack have a 'purpose' or not (considering it might change in a future life)?

**Who the primary contacts are for this work**
Katy, Andrew, Lesley

**Additional context or information**
See previous team research around tube racks - https://ssg-confluence.internal.sanger.ac.uk/pages/viewpage.action?pageId=101361052 - might have some useful ideas.

See summary of current level of support for tube racks in Limber - https://github.com/sanger/limber/issues/1333#issuecomment-1682484672

**Comment by yoldas** [comment]
Lucid document for discussion: [Reusing TubeRacks](https://lucid.app/lucidchart/1b3d7411-38be-40f2-8f6b-89a9ff046d24/edit?viewport_loc=1080%2C-466%2C2225%2C1565%2C~XbxvqItdMT9&invitationId=inv_0f71be41-99fb-457a-aa10-d68add85d983)

**Comment by yoldas** [comment]
TubeRack New model Use Cases (TW notes from 26th April meeting):

- Creation
- The New Model should be able to live alongside most of the existing workarounds and models.
- The New Model should be able to cope with existing data related to tube racks used by the current workarounds.
- Support the Banking operation.
- Support the ability to re-array tubes (in the future).
- Support the existing use of Plate Purposes to limit the scope of change.
- Support the transfer of samples In / Out.
- Support the pooling operation.
- Support the Bed Verification Operation.
- Ideally the model should be compatible with JSON-API implementation & limitations. Of all the use cases I think this is the least important for me. Creating better endpoints / APIs / namespaces is not a bad thing.

Additional:
- Submissions on tubes
- Events
- Reracking

**Comment by KatyTaylor** [comment]
Not sure where to put this (in every story?) but we also need to keep running the Int Suite test as we go to make sure it still passes. I guess the bits most likely to break it are where the UX changes:
- In banking, the fact that a list of child tube racks will be shown after the transfer step, instead of a list of child tubes.
- In defrosting... should be v similar UX - maybe won't break?

**Comment by yoldas** [comment]
I have added a Lucid doc [TubeRack Stories](https://lucid.app/lucidchart/d88bdcfd-9628-4fec-8b5a-453f680ee06b/edit?viewport_loc=-840%2C-355%2C2712%2C1596%2C0_0&invitationId=inv_13d74286-1cc2-4c2f-aaf0-30887764601c) to show the relationships between stories. WIP.

**Comment by yoldas** [comment]
I have added integration suite criteria in the following top-level stories
- #1713
- #1715

I have not added separate Sequencescape API, Transfer Requests, and Presenter stories for Defrosting because once the Banking is done, they should be already there.
