### ISSUE TITLE
DPL-1015 Bed verification - support sequencing-only

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1486]
**User story**
As a user of the scRNA Core Cell Extraction pipeline, I would like the bed verification for the LRC PBMC Bank plate to the LRC Bank Seq and LRC Bank Spare tubes to support the scenario where there is one destination sequencing rack, and NOT support the scenario where there is one destination contingency rack.

**Who are the primary contacts for this story**
Abby, Lesley, Katy, Andrew

**Who is the nominated tester for UAT**
Abby

**Acceptance criteria**
In the transfer from LRC PBMC Bank plate to the LRC Bank Seq and Spare tubes:
- [ ] Bed verification accepts scenario where there is just one destination rack and it contains 'LRC Bank Seq' tubes
- [ ] Bed verification rejects scenario where there is just one destination rack and it contains 'LRC Bank Spare' tubes
- [ ] Bed verification accepts scenario where there are two destination racks, 1 containing 'LRC Bank Seq' tubes and 1 containing 'LRC Bank Spare' tubes (as currently)

**Additional context**
Original text from Abby:

> Currently we restrict the user to only be able to upload either all contingency or a mix of both tube types. Since there have been some changes to the line (namely cell counting removal) and due to the mechanism for assigning tube purposes, we do not think there is a scenario where the user would be in a position to only upload contingency tubes. As we discussed though on Monday, there could be a niche case where the user may only have sequencing tubes. In light of this, would it be possible to please alter the tube rack scan upload to accommodate sequencing only and prevent contingency only? 

- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by KatyTaylor** [comment]
`PlateToTubeRacksRobot` and `PlateToTubeRacksBed` control the bed verification for this transfer.
And `robots.rb` has all the config for all the bed verifications.

**Comment by seenanair** [comment]
`prepare_beds` method in PlateToTubeRacksRobot performs the check in a generic way. Bed verification builds some “virtual tube racks” based on the children of the parent plate. This is created after the validation performed as part of tube rack file upload which will be covered in [DPL-1014 ]
During bed verification  checks using `prepare_beds` it validates what is stored in `labware_store_purposes`, created using the “virtual tube rack" object. So, a specific validation is not required in this context. 

(https://github.com/sanger/limber/issues/1485#issuecomment-2326101482) . Therefore, it appears that there is no separate validation required in the bed verification context.

`  def prepare_beds
      @relationships.each do |relationship|
        relationship_children = relationship.dig('options', 'children')
        labware_store_purposes = labware_store.values.map(&:purpose_name)

        bed_barcodes_to_remove =
          relationship_children.select { |barcode| labware_store_purposes.exclude?(beds[barcode].purpose) }

        delete_beds(bed_barcodes_to_remove, relationship_children)
      end
    end`

**Comment by seenanair** [comment]
Outstanding questions: (@yoldas , Please feel free to edit this if you feel appropriate)

Can they cancel the tubes that were created?
If so, how can we identify all tubes created as a batch?
These questions are significant in this context because, while looking for stored purposes, the method fetches all tubes created as part of a tube rack.

For example, if the user scans in both a Seq tube and a Contingency tube, but later changes their mind and decides to use only the Seq tube after canceling the originally created tubes, the existing code will still pick up all the tubes created in both cases. This can lead to incorrect validation results because the system will validate against all previously created tubes, even the ones that were canceled. 

@KatyTaylor @yoldas It would be great to have a catchup on this.

**Comment by dasunpubudumal** [comment]
This story did not require code changes. However, there are some bugs identified when testing this story which were encapsulated in subsequent stories. Those bugs will be addressed in the said stories.
