### ISSUE TITLE
DPL-1025 PBMC donor pooling - bed verification

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1504]
**User story**
As a user of the scRNA Core pipeline, I would like the LIMS to support the pooling of the PBMCs ready to go on the 10X chip, based on cell count, by performing a bed verification on the Hamilton STAR robot.

**Who are the primary contacts for this story**
Lesley, Katy, Andrew

**Who is the nominated tester for UAT**
Lesley, Abby

**Acceptance criteria**
- [x] Input is "LRC PBMC Defrost PBS" plate
- [x] Output is "LRC PBMC Pools" plate
- [x] Include the 'require_robot' flag on both below options, so that the user is required to scan the robot barcode & we have an audit of which robot they used.

Robot option 1 (Hamilton STAR):
- [x] Source plate on bed 15
- [x] Destination plate on bed 14

Robot option 2 (Hamilton STARlet):
- [x] Source plate on bed 15 
- [x] Destination plate on bed 14

**Comment by Lesley84** [comment]
Happy with the plate names. 
We have 2 Hamilton robots we could make available for this method providing additional capacity in the lab. However, they will have different bed layouts. 

Could we have 2 available robots?
1) Robot name - STAR - bed layouts as detailed above 
2) Robot name - STARlet - we will need to define the bed positions on this robot

**Comment by KatyTaylor** [comment]
Updated to require just one source plate, in anticipation of GEM-X chip decision.

**Comment by KatyTaylor** [comment]
Feedback from Abby:

> For DPL-1025, we would want it to be the same beds regardless of instrument so we haven’t looked at the protocol yet but that is what we’ll aim for. I understand that changing the beds in retrospect is not too bad if it lets you proceed with the story? So the same beds can be used for the STARlet as are set for the STAR.

Have updated the story description accordingly and taken it off hold.

**Comment by KatyTaylor** [comment]
Added this into To Do as a story that can be done in parallel to others. (Because I reduced the possibility for parallel work by removing a story and marking another as blocked).
