### ISSUE TITLE
DPL-1054 Add Vac tube barcode to the Aliquot tube labels

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1546]
**User story**
As a user of the scRNA Core Cell Extraction pipeline, I would like the LRC Blood Aliquot labels to display the parent LRC Blood Vac tube barcode (as well as the current information), so that it is easier to see the relation between the two tubes.

**Who are the primary contacts for this story**
Abby, Katy

**Who is the nominated tester for UAT**
Abby

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] LRC Blood Aliquot barcode label should display the parent LRC Blood Vac tube barcode (as well as the current information)
- [ ] Printing label is tested using the relevant printer (r152-bc1)

**Dependencies**
Probably best to implement https://github.com/sanger/limber/issues/1536 first, as it might change how this story is implemented.

**Additional context**
This request came out of the training sessions.

**Comment by andrewsparkes** [comment]
Is there room to fit any more information onto a tube label, isn't it already crammed?
A pic of an existing LRC Blood Aliquot tube label and where they want the new barcode to go would be useful here.

**Comment by yoldas** [comment]
There was a similar story for Bioscan: [DPL-749](https://github.com/sanger/limber/issues/1343) and there was a Lucid document: [Label Printing](https://lucid.app/lucidchart/13b6e4e1-a2f2-4896-b0b3-bcc7425c5a44/edit?viewport_loc=607%2C-1476%2C3389%2C2261%2CTlYc~I8iYymU&invitationId=inv_d1466b0a-9840-41e5-9ca9-9c47b9dde361)

**Comment by KatyTaylor** [comment]
From Abby on Slack:

> On the LRC Blood Aliquot labels we would want:
The scannable blood aliquot barcode
The human readable blood aliquot barcode
The tube purpose (LRC Blood Aliquot)
The human readable LRC Blood vac barcode.
Could we treat this like how the cherry pick plate ID is normally carried through a line? It's usually on the left side of the scannable barcode with the date and the actual plate purpose and barcode is on the right
