### ISSUE TITLE
DPL-1087 [Limber] Extra QC barcode label for RVI Lib PCR XP plate

### ISSUE THREAD

**Issue by yoldas** [sanger/limber#1570]
**User story**
As R&D (Scott T) I would like the text on the extra QC label for the RVI Lib PCR XP plate not to overlap with the barcode image.

**Who are the primary contacts for this story**
Scott T
Abdullah Y

**Who is the nominated tester for UAT**
Scott T

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] The barcode on the bottom left does not overlap with the barcode image

**Dependencies**
No dependencies

References
No non-blocking relationship

**Additional context**
See Slack [thread](https://psd-team.slack.com/archives/C052904MWUR/p1702994113453429) about the printing issues during RVI UAT testing. For instance, the barcode labels for SQPU-70641-F QC ([Limber UAT](https://uat.limber.psd.sanger.ac.uk/limber_plates/342ea6ea-9e73-11ee-9cd8-02420e1e76ad)), SQPP-43211-S QC ([Limber Production](https://limber.psd.sanger.ac.uk/limber_plates/d25bfa7e-8943-11ee-becc-024224dd57f4))
Check if any existing label templates can be used first. If necessary, create a new label template and update configuration.

**Comment by stevieing** [comment]
Closed as deprecated. This label is not scanned.
