### ISSUE TITLE
Y24-014 - As a user (Di R) I would like to be able to rerun the RVI BCL pipeline from the RVI Lib PCR XP plate

### ISSUE THREAD

**Issue by BenTopping** [sanger/limber#1615]
**User story**
 As a user (Di R) I would like to be able to rerun the RVI BCL pipeline from the RVI Lib PCR XP plate.

This may require some initial research into how Re-ISC works. The behaviour should be similar to how ReISC works where an additional submission in Sequencescape is performed which re-generates requests that allows the pipeline to be re-run? This currently exists in the ISC pipeline so we can copy the behaviour from there to allow it to be done on the RVI BCL pipeline.

**Dependent** on https://github.com/sanger/sequencescape/issues/4023 (Adding Novaseq 6000 sequencing request to RVI pipeline)

**Who are the primary contacts for this story**
Di R, Ben T, Andrew S

**Who is the nominated tester for UAT**
Di R

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Adds a submission (or uses existing) to Sequencescape to add requests to given RVI plates.
- [ ] Able to re-run the ISC section of the RVI Bait Capture Library Prep pipeline (from RVI Lib PCR XP) onwards.
- [ ] Contains a Novaseq 6000 sequencing request as described in DPL-1104.

**Comment by TWJW-SANGER** [comment]
I need to check if this is still required.

**Comment by andrewsparkes** [comment]
The ability to Re-ISC was added to Targeted NanoSeq on the LTN Lib PCR XP plate, so maybe that is a useful example of what is required.

**Comment by TWJW-SANGER** [comment]
NB Tableau billing report will be checked by Anna G when this happens to ensure this is correctly captured.
