### ISSUE TITLE
Y24-022 Add new UI for submitting the Pool XP tube to Traction

### ISSUE THREAD

**Issue by sdjmchattie** [sanger/limber#1617]
**User story**
A new panel should be shown on Pool XP tubes with a button that will submit the tube to Traction.  What actually happens when this button is pressed is that a message is published to the RabbitMQ queue for the action.  Exactly how this happens is undecided, but the most robust method will be for Limber itself to publish the message so that it doesn't rely on another system being available to take that action.

After the message is published, the UI should update to disable the button and indicate that the message has now been submitted.  This could be a label accompanied by a good quality icon indicating waiting (an hour glass?).  The page should start polling Traction's API directly to see whether the tube was created.  When it is, the UI can change to a green tick and a confirmation message.

If the Traction Service API is unavailable, this can be displayed in a way that shows the information about submission isn't available right now.  On refresh, the button should start disabled the page should try to check just one time for the presence of the Pool XP tube on Traction Service API in case it was previously submitted.  If so, the button should remain disabled and the UI show that the tube is already there.  The button will become enabled when the tube cannot be found on Traction Service API.

**Who are the primary contacts for this story**
Stuart McHattie

**Who is the nominated tester for UAT**
Andrew Sparkes + PSD

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] The Pool XP tube page has a button to submit to Traction.
- [ ] Clicking the button causes the tube to be submitted and within a few seconds it will show that the tube is now on Traction.
  - [ ] Optional:  A link is given to the tube on Traction.
- [ ] Once submitted, it should be difficult to submit again by keeping the button disabled unless we confirm the tube isn't on Traction.
  - It's not the end of the world if a second submission occurs because the second one will fail in Traction Service.

**Comment by KatyTaylor** [comment]
Endpoint to call in Sequencescape:

`ExportPoolXpToTractionController`

Job in SS:

`ExportPoolXpToTractionJob`
