### ISSUE TITLE
Y24-023 [BUG] Reconcile handling of default states

### ISSUE THREAD

**Issue by StephenHulme** [sanger/limber#1619]
**Describe the bug**

The default states of some labware is handled inconsitently within Limber itself.

This is partly due to the RVI Cherrypick purpose being able to cherry pick to itself, but is indicative of a lack of central handling of state defaults.

**RT Ticket Number**

None
PR - #1594 

**To Reproduce**

Steps to reproduce the behaviour:
1. Go to the [RVI Pipeline Progress page](https://uat.limber.psd.sanger.ac.uk/pipeline_work_in_progress/RVI%20Bait%20Capture%20Library?date=1970-01-01)
2. Note that Labware `SQPU-55837-C` in RVI Cherrypick is stated as `pending`
3. Click the [link on the labware](https://uat.limber.psd.sanger.ac.uk/limber_plates/4c5882e0-68ef-11ee-854b-02420e1e76ad)
4. Note that the labware page indicates the status as `passed`

**Expected behaviour**

Both of these states should be the same (probably `passed`)

**Screenshots**

<img width="982" alt="Screenshot 2024-03-11 at 11 46 13" src="https://github.com/sanger/limber/assets/135011085/75518999-9c97-4eab-9788-98232669ce20">

<img width="925" alt="Screenshot 2024-03-11 at 11 45 49" src="https://github.com/sanger/limber/assets/135011085/d60b4187-7b86-4948-bc5d-7586ad9b563d">

**Additional context**

See the [progress controller](https://github.com/sanger/limber/blob/develop/app/controllers/pipeline_work_in_progress_controller.rb#L92-L94) for one potential cause of this inconsistency

First noticed in #1596

**Comment by TWJW-SANGER** [comment]
I think needs scoping from the business point of view.

Want to display correct and useful data for users.

**Comment by TWJW-SANGER** [comment]
The Deprecate? label applies to this bug/issue/user story. 
It means we are considering taking off the board as it is unlikely to be prioritized in a reasonable period of time.

It's a nice tidy up thing to do -- but I think we need business user involvement to refine this - for which they need to a) understand it and b) see it as worth investing their time in than other stories in the backlog.

**Comment by stevieing** [comment]
closed as deprecated
