### ISSUE TITLE
Y24-029 [BUG] Limber tagging screen not showing wells with tag index

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1631]
**Describe the bug**
The tagging screen in Limber seems to have stop showing a preview of the wells, with the tag index inside the well. Reported in RT 798827 (and 799378).

**RT Ticket Number**
798827

**To Reproduce**
Steps to reproduce the behaviour:
1. Run 'Bespoke PCR' spec in Integration Suite, stopping the test when you get to the tagging screen 
![Screenshot 2024-03-15 at 15 20 47](https://github.com/sanger/limber/assets/10407809/f2434c94-2284-42a8-af39-9b0a434c7f20)

2. See that wells are blank

**Expected behaviour**
Coloured boxes appear indicating wells, with numbers inside indicating tags. See screenshots.

**Screenshots**
Screenshot from a while ago showing tagging screen with yellow wells:
![Limber Tagging Screen - Page 2](https://github.com/sanger/limber/assets/10407809/4bd58c8c-f640-4b8f-b9bb-3f87b106fd81)

Screenshot from the RT showing blank wells:
![Limber tagging screen issue](https://github.com/sanger/limber/assets/10407809/14924d83-2272-4482-88cc-04e7bde4fe87)

**Desktop (please complete the following information):**
* My test was on a Mac, using Google Chrome (Version 122.0.6261.128 (Official Build) (x86_64))

**Comment by neilsycamore** [comment]
Was discussed and mentioned at stand up (19/3) that there were JS changes a few weeks ago. The contacts in the RT mention that this has been a noted issue for the "..past few weeks"
