### ISSUE TITLE
Y24-030 [BUG] Limber not allowing plate creation on TCR chromium plate

### ISSUE THREAD

**Issue by neilsycamore** [sanger/limber#1636]
When attempting to assign tags to a LBC TCR Post Lig 1xSPRI plate when 1 group of tags are selected there is the option to create the plate (This is the case regardless of whether it is the i7 or i5 tags that are selected)
![image001 3](https://github.com/sanger/limber/assets/299768/1f31bb2c-4170-49ec-bcee-5bff61be2c2d)

When the second group of tags is selected creating a plate is no longer an option
![image002 3](https://github.com/sanger/limber/assets/299768/44b93773-1995-4891-8c6c-9b18b11c4416)

**RT Ticket Number**
[RT799378](https://rt.sanger.ac.uk/Ticket/Display.html?id=799378)

**To Reproduce**
(nts) The previous plate to the LBC TCR Post Lig 1xSPRI is LBC TCR Dil 2 in training I found SQPP-50916-O could be used to reproduce this. If non chromium tag sets are selected (i.e pWGSD) then the create plate option remains

'Possible' additional info:
Was discussed and mentioned at stand up (19/3) that there were JS changes a few weeks ago. The contacts in the RT mention that this has been a noted issue for the "..past few weeks"

Contacts:
Jo (jc32) Team Lead - Chromium 10X
Steve (sw32) SSR PaM

**Comment by andrewsparkes** [comment]
See crossed through wells now we've fixed the other issue in Y24-029. Investigating.
![Screenshot 2024-03-19 at 14 10 53](https://github.com/sanger/limber/assets/3169253/94f54f2a-302e-4485-b882-56a5f017d96c)

**Comment by andrewsparkes** [comment]
![Screenshot 2024-03-19 at 14 21 37](https://github.com/sanger/limber/assets/3169253/ff2d2f59-1cd2-4d57-b144-176222f63fe3)

**Comment by neilsycamore** [comment]
resolved by https://github.com/sanger/limber/issues/1631
