### ISSUE TITLE
Y24-037 Cell count spot-checking

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1653]
**User story**
As a user of the scRNA Core Cell Extraction pipeline (007c Phase 1), I would like to alter the way the cell counting step works, in order to reduce costs. Instead of counting cells in all wells on the LRC PBMC Bank plate, I would like the LIMS to select a subset of the wells to count, and generate the Hamilton driver file for the transfer to the Cellaca plate. 

**Who are the primary contacts for this story**
Abby, Katy

**Who is the nominated tester for UAT**
Abby

**Acceptance criteria**
On the LRC PBMC Bank plate, I can produce a Hamilton driver file with the following columns:
- LRC PBMC Bank plate barcode
- well position on the LRC PBMC Bank plate
- LRC Blood Vac tube barcode (stored in the supplier_name on sample_metadata)
- A composite of plate barcode and well position - plate_barcode:well_position
- Sample name (sample.name)

There are 2 options for what rows of the file contains: 
- [x] (routine use) The LIMS selects 4 wells from the plate, using the following rules:
    - If wells in the plate come from ≥4 original LRC Blood Vac tubes (barcode is stored in `sample_metadata` `supplier_name`), select 4 wells that came from different vac tubes.
    - If wells in the plate come from <4 original LRC Blood Vac tubes (barcode is stored in `sample_metadata` `supplier_name`), select 1 well for each original vac tube.
    - Do not select empty wells
    - Where possible, pick wells that are distributed across the plate - e.g. if we had 12 original vac tubes on the plate (in numerical order), ideally a sample would be selected from vac tube 1, 5, 9 and 12 rather than 1-4
- [x] (occasionally) Pick one sample per vac tube (`sample_metadata` `supplier_name`). (this option would be for kit testing or training for example).
- [x] In both of the above cases, where there are multiple samples per vac tube, the first one (in column order) should be selected, as this is the one that will be destined for sequencing.

Also:
- [x] Get rid of the 4 existing Cellaca files on this plate, and any associated code or tests (e.g. Integration Suite test).
- [ ] Update the Integration Suite test to include this new file.
- [x] This plate has the option to print up to 4 extra QC barcode labels. Do not remove this - it's still useful.

Additional feedback:
- [x] Move 'Well name' to the final column of the CSVs
- [x] Add workflow header i.e. 'scRNA Core LRC PBMC Bank Cell Count'
- [x] Add an empty line between Workflow header and Column headers
- [x] File names describe exactly what they do i.e. 'hamilton_lrc_pbmc_bank_to_cellaca_?_count' and 'hamilton_lrc_pbmc_bank_to_cellaca_all_count' [we still don't know the ? no. and if it is 12, it is effectively the same csv as the 2nd option, pending discussion 4th July]
- [x] Buttons: Content report and Bank Seq/Spare options not appear until the LRC PBMC Bank plate is passed.
- [x] Buttons: Name the cellaca files fairly differently to the other csv files or colour code these. i.e. 'Download Cellaca LRC PBMC Bank Hamilton ?/ALL count CSV' [Name change is done]

**Additional context**
Currently, the Cellaca files that are generated are in a different format, and are not Hamilton driver files but are uploaded directly to the Cellaca instrument. This will no longer be the case. Since they will only be using a few wells on the Cellaca plates, they want to be able to reuse the same Cellaca plates over multiple runs. They will keep track of which wells have been used, and generate the Cellaca input files off-LIMS, using the Hamilton robot software.

Suggested UX is to have 2 separate file download buttons for the 2 file options (3 once the below story is also done).

A third file is requested in https://github.com/sanger/limber/issues/1654

**Comment by ac38** [comment]
- For the Hamilton driver columns, would it be okay to also include the sample name? This is only to make it consistent with the isolation and banking files.
- For the donor repick of up to 4 samples, if there are >4 donors, could the selection choose different donors from the initial pick where possible? I appreciate this will make the step more complicated though.
- Not sure if there were any plans for this but I think it would still be useful for users to be able to print the QC1-4 Cellaca plate labels. As the plates are being reused the labels would have to be removed/replaced between runs but they would allow users to track the plate order within a run more easily.

**Comment by KatyTaylor** [comment]
Hi @ac38 , thanks for the comments.

> For the Hamilton driver columns, would it be okay to also include the sample name? This is only to make it consistent with the isolation and banking files.
Yes no problem. I'm looking at 2 existing files, called 'hamilton_lrc_pbmc_bank_to_lrc_bank_seq_and_spare' and 'hamilton_lrc_blood_bank_to_lrc_pbmc_bank' - hopefully those are the ones you're talking about. They include the sample name. I'll add this to the acceptance criteria.

> For the donor repick of up to 4 samples, if there are >4 donors, could the selection choose different donors from the initial pick where possible? I appreciate this will make the step more complicated though.
Ah I see what you mean. Different donors as well as different wells. I will add that.

> Not sure if there were any plans for this but I think it would still be useful for users to be able to print the QC1-4 Cellaca plate labels. As the plates are being reused the labels would have to be removed/replaced between runs but they would allow users to track the plate order within a run more easily.
Yes, we can leave in the QC1-4 barcode labels, no problem.

**Comment by ac38** [comment]
Hi @KatyTaylor, Yes as you have said. Sounds great thank you!

**Comment by KatyTaylor** [comment]
I've sized it as medium assuming we'll do it as 3 separate buttons. If we do a different user interface it might become a large.

**Comment by ac38** [comment]
I think 3 separate buttons is fine. Is there an easy way to have these visually separate from the other driver files? Just otherwise it might look a bit busy

**Comment by KatyTaylor** [comment]
TODO: test how the failing wells interface looks if there's no cell count data for a well

**Comment by KatyTaylor** [comment]
Discussed this with Abby yesterday -

This is currently 'on hold' because there are 2 current uncertainties:
1. Whether they want the 'Pick all available samples' option, or a 'Pick one well from each donor' option instead.
2. How to handle the printing of the QC1-4 barcode labels.

It is not required for go-live of the cell extraction pipeline, because they are planning to start with:
- Counting all the samples on the plate
- Not using the existing Cellaca files on the plate
- Generating the Hamilton driver file using a file download on the previous plate, and an Excel template to transform this into the correct driver file format

**Comment by KatyTaylor** [comment]
Updates:

> At the meeting today, they have said they would like option 2 for Y24-037 to be for picking 1 sample per LRC Blood Vac i.e. up to 12 samples.

> To make it easier for users to manually plate the blood without making mistakes, we have set a limit that they will only process 12 Blood Vacs/plate i.e. 1 per column 

> Can we also guarantee that the well counted is taken from the first appearance i.e. the sample destined for sequencing?
(for both 4 well and one-per-donor options)

QC labels still under discussion. I estimated that providing an option for the user to pick how many of the QC1-4 labels they wanted to pick would be a large story. Abby is checking with Lesley and will get back to us.

**Comment by KatyTaylor** [comment]
I moved this into To Do, to make sure there's enough in there for parallel work, because I removed a different story (https://github.com/sanger/limber/issues/1395) and another one is blocked (https://github.com/sanger/limber/issues/1393).
