### ISSUE TITLE
Y24-042 'Cryostor' tube rack scan file improvements

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1659]
**User story**
As a user of the cDNA Prep part of the scRNA Core pipeline, I would like the rack scan format (used for the initial Seq/Spare tubes --> Cryostor plate/rack step) to match that required by a previous step in the pipeline, so that the tube rack scanner only has to have one output format, reducing scope for user error.

**Who are the primary contacts for this story**
Abby, Katy

**Who is the nominated tester for UAT**
Abby

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Upload page accepts files that include an extra (first) column, containing the tube rack barcode (example file - [Cryostor plate rack scan_3col_correct (1).csv](https://github.com/sanger/limber/files/14837111/Cryostor.plate.rack.scan_3col_correct.1.csv)).
- [ ] It could also accept the previous format, but does not need to. [Not done as not easy to implement]
- [x] This first column of data does not need to be saved (plate barcode is printed out and stuck on the tube rack).
- [x] Currently, if the attached file is uploaded, the LIMS throws an exception. It should handle errors gracefully if the file format is not as expected.

**References**
This is an enhancement to https://github.com/sanger/limber/issues/1388

**Additional context**
This came up during UAT.

**Comment by andrewsparkes** [comment]
Thoughts
The tube rack (represented by the Cryostor plate in LIMS) has not been created yet (this file upload is the start of the create process). So how is the barcode label printed out and stuck on the rack?
Presumably it's not, so the 'rack' barcode in the file must be the etched one on the rack (or worse a barcode label from a previous use).

**Comment by andrewsparkes** [comment]
See line 77 in `app/models/labware_creators/multi_stamp_tubes_using_tube_rack_scan.rb`

`@csv_file ||= CommonFileHandling::CsvFileForTubeRack.new(file) if file`

Change this to use `CsvFileForTubeRackWithRackBarcode`


For the error handling it is supposed to capture a problem and write to errors, but clearly isn't with unexpected columns.
See `CommonFileHandling::CsvFileBase` and `CsvFile::RowForTubeRackWithRackBarcode` (and `CsvFile::RowForTubeRack`)
