### ISSUE TITLE
Y24-047 Restrict plate purpose - PBMC donor pooling [Deprecated]

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1664]
**User story**
As a user of the scRNA Core pipeline, when scanning in 1 or 2 source plates to create the LRC PBMC Pools plate, I would like the LIMS to only accept source plates of the expected plate purpose (LRC PBMC Defrost PBS), to avoid user error.

**Who are the primary contacts for this story**
Abby, Katy

**Who is the nominated tester for UAT**
Abby

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] When creating the LRC PBMC Pools plate, only LRC PBMC Defrost PBS plates are accepted as source plates.
- [ ] If a different type of plate is scanned in, the user is presented with an informative error.

**Additional context**
This request came out of UAT.

**Comment by KatyTaylor** [comment]
This will not be needed if the GEM-X chip decision goes ahead, because there will only be one source plate in this transfer, so the page where source plates are scanned in will not be needed.

**Comment by SujitDey2022** [comment]
@KatyTaylor marked as closed
