### ISSUE TITLE
Y24-068 Create new Bravo RVI stamping step

### ISSUE THREAD

**Issue by neilsycamore** [sanger/limber#1678]
As the RVI automation team (Tobi A.) I would like to add a "Bravo LDW-96 Stock ==> LSW-96 Stock" option to Limber in the robot step of the RVI Deepwell Plate to Shallow-well plate stamping process. This should have its own button which gives users the option to select the Bravo as their instrument for bed verification over the Hamilton.

**Who are the primary contacts for this story**
Tobi A.
Scott T.

**Who is the nominated tester for UAT**
Tobi A.

**Acceptance criteria**
To be considered successful the solution must allow:
- Option to select the "Bravo LDW-96 Stock ==> LSW-96 Stock" under 'Suggested Actions' then 'Robots' menu
- When the Bravo is the selected robot, LDW-96 Stock plate's expected bed barcode is bed 4. LSW-96 Stock plate's expected bed barcode should be bed 6.
- The landing page and functionality once the Bravo robot button is pressed should be similar to the Hamilton and follow the same logic

**Additional context**
[RT802093](https://rt.sanger.ac.uk/Ticket/Display.html?id=802093)
- SS of the current Limber landing page attached
![limber robot 1](https://github.com/sanger/limber/assets/299768/c4398b4f-6e96-4cba-ad6c-e8ca527bc2f0)
![limber robot 2](https://github.com/sanger/limber/assets/299768/7a189f7d-2fa0-4785-a972-bf2ab0064b9f)

**Comment by andrewsparkes** [comment]
Integration suite branch for this story here:
https://gitlab.internal.sanger.ac.uk/psd/integration-suite/-/merge_requests/131

**Comment by andrewsparkes** [comment]
New button added

![Screenshot 2024-06-06 at 09 44 24](https://github.com/sanger/limber/assets/3169253/9059a2c6-af13-4e67-b05f-f5cf4e38a612)

**Comment by andrewsparkes** [comment]
And beds

![Screenshot 2024-06-06 at 09 48 19](https://github.com/sanger/limber/assets/3169253/e132279c-4436-45b8-b33e-70ab5a59036e)
