### ISSUE TITLE
Y24-074 [BUG] Pooling tab improvements for "LRC PBMC Pools" plate

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1679]
N.B. see update section at bottom.

**Describe the bug**
From Abby during UAT of the scRNA Core pipeline:

> I have attached the Limber page for an LRC PBMC Pools plate that has 21 samples pooled across 2 wells.
> The display under the pooling tab shows a 'pool' for every sample the plate contains i.e. 21 pools. Pools 3-21 do not exist though so the information is a bit redundant. What would be ideal would be if it displayed which sample well from the previous plate went into which pool. Is that possible?

See screenshot further down.

N.B. we have another bug open relating to this same part of the Limber UI - https://github.com/sanger/limber/issues/1667 

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the scRNA Core integration suite pipeline up to the LRC PBMC Pools plate. You might have to increase the numbers of samples being used so that there are enough samples to make >1 pool.
2. On the page for the LRC PBMC Pools plate, click on the pooling tab.
3. See redundant information as described above.

**Expected behaviour**
The information shown here should be useful. 
- See Abby's suggestion above (display source wells for a pool)
- Look into what information this tab is meant to display - I presume that it's not working correctly for this plate, maybe because these are not traditional 'pools', because the samples are not tagged.

**Screenshots**
![image (1)](https://github.com/sanger/limber/assets/10407809/8a25eed3-38a6-4210-84aa-b8365cc4061f)

**Update**
On looking into this it appears the 'pooling' tab is intended to show the planned future pooling of the samples in the plate according to the submissions / requests set up by the SSR in the submission. It is NOT intended to show the contents for current pools on this plate. i.e. it is not suitable for this plate or pipeline, and was probably intended to show Multiplex pooling strategies for the older sequencing pipelines.

The 'samples' tab is probably better suited for the information that Abby is requesting. This tab is supposed to list the sample composition of each well. The current code will display each sample in a well as `<sanger_sample_id>-<species>`. 

Unfortunately both these fields were not being set on sample creation for tube manifests in the Sequencescape UAT action used for testing this pipeline, so the tab was not displaying anything except the list of occupied wells (fix for that 
created here - https://github.com/sanger/sequencescape/pull/4114). 
This sample information does not include parent well either, so we will likely need to override the sample tab content for this plate in the scRNA pipeline. 

The story then became partly a research story to investigate and document how the tabs are currently constructed and capture possible ways to improve these summary tabs so that they are only displayed if relevant to the labware.

The research output of the story is a document capturing this investigation. See here:
[Document](https://docs.google.com/document/d/1MJHUyrIwwWIgBAhiRFp-NlYzk9GkF2iPutnrlF7n_9Q/edit?usp=sharing)

**Comment by andrewsparkes** [comment]
Added update to description and converted into research story.
See link to research document in description.

**Comment by andrewsparkes** [comment]
Abby clarified requirements. Pooling tab is not required. Samples tab would be improved if it showed the parent well of each sample.

Created a PR for these changes, partly as doing this aided with understanding of the code structure around Presenter tabs and their contents.
