### ISSUE TITLE
Y24-083 Cell counting driver file (LRC PBMC Defrost PBS plate)

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1688]
**User story**
As a user of the scRNA Core pipeline, I would like the LIMS to generate a Hamilton driver file for me on the LRC PBS Defrost plate, so that the user experience is consistent with the cell counting on the LRC PBMC Bank plate, and the Hamilton robot software can also be consistent between the two steps. These changes allow us to lower costs with regards to reusing partial cellaca plates too.

**Who are the primary contacts for this story**
Abby, Katy

**Who is the nominated tester for UAT**
Abby

**Acceptance criteria**
On the LRC PBS Defrost plate:
- [x] There is the option to download a driver file for the Hamilton robot to transfer into the QC plates, with the following columns:
    - LRC PBMC Bank plate barcode
    - well position on the LRC PBMC Bank plate
    - LRC Blood Vac tube barcode (stored in the supplier_name on sample_metadata)
    - Sample name (sample.name) 
    - A composite of plate barcode and well position - plate_barcode:well_position
- [x] The existing 4 'Cellaca Input' file download options are removed
- [x] All filled wells on the plate should be included in the file, except if marked as 'failed'
- [x] The option to print 'QC1-4' barcode labels should be retained (although there is ongoing discussion about whether the existing functionality is sufficient or not.
- [x] The functionality where cell count result files are uploaded to the page is retained.

**Blockers**
This story has a non-blocking relationship with:
- https://github.com/sanger/limber/issues/1653 

(not technically blocking, but there is a lot of overlap so makes sense to wait until the above is done, then copy paste solutions over)

**Comment by KatyTaylor** [comment]
I've sized this as 'small' with the assumption that we'll do https://github.com/sanger/limber/issues/1653 first, so will have an example to copy and tweak.

**Comment by ac38** [comment]
Yes, we would like a consistent approach to cell counting for the user as much as possible. These changes allow us to lower costs with regards to reusing partial cellaca plates too.
Also correct, please don't include failed wells in the driver file.
Thanks!

**Comment by yoldas** [comment]
_"All filled wells on the plate should be included in the file,"_

This is not the same as #1653 , because in that story the well selection is done as one well per Vac Tube.
