### ISSUE TITLE
Y24-100 Tube Rack Banking Uploads

### ISSUE THREAD

**Issue by yoldas** [sanger/limber#1697]
**User story**
As PSD, we would like to support Limber tube rack scan file uploads for new tubes using the versioned tube rack model proposed in Reuse of TubeRacks document.

**Who are the primary contacts for this story**
Abdullah, Katy, Andrew

**Who is the nominated tester for UAT**
TBD

**Acceptance criteria**
- [ ] Uploading 3-column tube rack scan files, creates the destination tube racks along with the new tubes; not only the tubes (DPL-811)
- [ ] Tube rack purposes are set to LRC Bank Seq and LRC Bank Spare respectively

**Dependencies**
This story is blocked by the following dependencies:
- #1482 
- https://github.com/sanger/limber/issues/1695
- https://github.com/sanger/limber/issues/1696

References
This story has a non-blocking relationship with:
- #1314 
- #1713

**Additional context**
The versioned tube rack model is researched in DPL-1011 Re-use of tube racks and the model is summarised in the Google Document[ DPL-1011 Re-use of tube racks](https://docs.google.com/document/d/1rvPXeCk5rBEf72VkchHCD2FRmWANboke2pln_Lt_j5U/edit?usp=sharing)

This story is part of re-implementation of [DPL-811 Transfer PBMC isolations into FluidX tube racks](https://github.com/sanger/limber/issues/1314) (Banking) using the versioned tube rack model.

Story relationships are shown in the Lucidchart diagram [TubeRack Stories](https://lucid.app/lucidchart/d88bdcfd-9628-4fec-8b5a-453f680ee06b/edit?viewport_loc=-1051%2C-316%2C2770%2C1486%2C0_0&invitationId=inv_13d74286-1cc2-4c2f-aaf0-30887764601c) .

It is not possible to release the implementation of this story in isolation.

**Comment by TWJW-SANGER** [comment]
Just a note to mention that we may need to help / instruct the lab on how to configure their rack scanners to produce the desired output.

**Comment by KatyTaylor** [comment]
Is this one blocked by the other more technical stories:
- https://github.com/sanger/limber/issues/1695
- https://github.com/sanger/limber/issues/1696
?

**Comment by KatyTaylor** [comment]
I think "Support for creation of a TubeRack with new Tubes" is probably the only one that doesn't exist already, is that correct? The other 3 acceptance criteria are just there to make sure we retain that functionality?

**Comment by yoldas** [comment]
@KatyTaylor I have removed the redundant criteria and made a reference to DPL-811. I have also added the other two stories as dependencies.

**Comment by yoldas** [comment]
Use of rack scanners to generate 3-column output can be discussed and agreed in UAT.

**Comment by KatyTaylor** [comment]
Think this will actually be done as part of https://github.com/sanger/limber/issues/1696

**Comment by KatyTaylor** [comment]
Closing this as part of Y24-099
