### ISSUE TITLE
Y24-101 Tube Rack Banking Transfer Requests

### ISSUE THREAD

**Issue by yoldas** [sanger/limber#1698]
**User story**
As PSD, we would like to support creation of transfer requests from Limber upon upload of tube rack scan files using the versioned tube rack model proposed in Reuse of TubeRacks document.

**Who are the primary contacts for this story**
Abdullah, Katy, Andrew

**Who is the nominated tester for UAT**
TBD

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] LRC Bank Seq and LRC Bank Spare TubeRacks can be viewed in Sequencescape, with location, tubes, and samples. 
- [ ] LRC PBMC Bank plate is parent of LRC Bank Seq and LRC Bank Spare TubeRacks in Sequencescape.
- [ ] LRC PBMC Bank wells are parents of LRC Bank Seq and LRC Bank Spare tubes in Sequencescape.
- [ ] LRC PBMC Bank Children tab shows the LRC Bank Seq and LRC Bank Spare TubeRacks in Limber.

**Dependencies**
This story is blocked by the following dependencies:
- #1482 
- #1697

References
This story has a non-blocking relationship with:
- #1314
- #1713

**Additional context**
The versioned tube rack model is researched in DPL-1011 Re-use of tube racks and the model is summarised in the Google Document[ DPL-1011 Re-use of tube racks](https://docs.google.com/document/d/1rvPXeCk5rBEf72VkchHCD2FRmWANboke2pln_Lt_j5U/edit?usp=sharing)

This story is part of re-implementation of [DPL-811 Transfer PBMC isolations into FluidX tube racks](https://github.com/sanger/limber/issues/1314) (Banking) using the versioned tube rack model.

Story relationships are shown in the Lucidchart diagram [TubeRack Stories](https://lucid.app/lucidchart/d88bdcfd-9628-4fec-8b5a-453f680ee06b/edit?viewport_loc=-1051%2C-316%2C2770%2C1486%2C0_0&invitationId=inv_13d74286-1cc2-4c2f-aaf0-30887764601c) .

A TubeRack looks like the following in Sequencescape: https://sequencescape.psd.sanger.ac.uk/labware/27083543

It is not possible to release the implementation of this story in isolation.

**Comment by TWJW-SANGER** [comment]
I might suggest that the acceptance criteria is better phrased from the users point of view (if only for testing), so something like:
The user can see the link between source and destination tube on pages X,Y,Z
And maybe
The user can see the link between source and destination tube **racks**  on pages X,Y,Z

Linking the objects/tables is needed but is not sufficient to meet the criteria above (as you may need UI / API changes too...)

**Comment by KatyTaylor** [comment]
Agree with Tom that I generally prefer acceptance criteria from the user POV if poss. In this case though, I think the user-facing bit of transfer requests will be that the wells appear to be filled in / the plate state changes when the transfer requests are passed...

The parent child links seen in Sequencescape (and the children tab in Limber) are using a different model... asset links I think?

**Comment by yoldas** [comment]
I have changed the criteria to focus on the relationships between the LRC PBMC Bank Plate and LRC Bank Seq and LRC Bank Spare TubeRacks, and wells and tubes. These relationships should be visible in Sequencescape if transfer requests are created correctly. In Limber, I have included only the LRC PBMC Bank Children tab for this story. I have also added a TubeRack page as an example in Sequencescape.

**Comment by KatyTaylor** [comment]
Transfer requests are created as part of Y24-099.

LRC Bank Seq and LRC Bank Spare TubeRacks can be viewed in Sequencescape, with location, tubes, and samples.
- This is met by Y24-099?? - Andrew to check what it looks like

LRC PBMC Bank wells are parents of LRC Bank Seq and LRC Bank Spare tubes in Sequencescape.
- This is not going to be met, as the asset_link relationships are between labware. The wells and tubes should be linked via transfer requests.

LRC PBMC Bank Children tab shows the LRC Bank Seq and LRC Bank Spare TubeRacks in Limber.
- This is met by Y24-099, except for the state-related issue in the Relatives tab, which should be solved in [the presenter story.](https://github.com/sanger/limber/issues/1700)
