### ISSUE TITLE
Y24-089 GEM-X chip representation [Deprecated]

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1705]
**Description**
Look into how difficult it would be to represent the 10x Chromium GEM-X in a more realistic way in Limber.

The chip is shown in the screenshot below. Only the row labelled '1' will be represented in the LIMS, because this is the only row that contains samples.

In Limber, the chip will be represented in a similar way to a plate. 
- Ideally, it would be horizontally-orientated, so as to look similar to the real chip for users.
- Ideally, the row would be labelled '1' and the columns 'A-H', so as to look similar to the real chip for the users.

This is transposed from how the LIMS normally represents plates, as normally the rows are 'A-H' and the columns '1-12'.

This research story is to find out how much work it would be to represent the chip as described above. If it's too much work, we will probably go with the option of horizontal, but with the row and column labels swapped.

![image](https://github.com/sanger/limber/assets/10407809/f384003a-8b47-4065-b01b-ec014e33b835)

**Who the primary contacts are for this work**
Katy, Abdullah, Andrew, Abby, Lesley

**Comment by KatyTaylor** [comment]
Deprecating this story, after Slack conversation with Abby:

The below screenshot is how the chip would look in Limber without further work, if you ignore the second row of wells (taken from [this research story](https://github.com/sanger/sequencescape/issues/3936) :

![image](https://github.com/sanger/limber/assets/10407809/e933edce-9516-45e3-9a9b-216fe46d03de)

- Labelling wells with just numbers 1-8 is desired, as this is how the Hamilton represents it.
- The presence of the 'A' is not a big deal, so let's leave it there.
- When the Hamilton driver file is made, we should remove the 'A' so that the wells are represented by numbers 1-8.

**Comment by stevieing** [comment]
Closed as deprecated.
