### ISSUE TITLE
Y24-096 Make barcode shorter - LRC Blood Aliquot

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1707]
**User story**
As a user, I would like to adjust the content / layout of the LRC Blood Aliquot label so that it fits on the tube. (The barcode is not scannable - see screenshot in separate comment.)

Note that we are using a plate label shape / size because the lab doesn't have a tube label printer. 

We have discussed options with Abby and think the way forward is to use a 2D barcode (they have appropriate scanners to use in the lab). 

**Who are the primary contacts for this story**
Abby, Katy, Andrew

**Who is the nominated tester for UAT**
Abby

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Label is scannable and readable on the tube and contains all the required information
    - [x] Barcode uses the 'human readable' form (NT...) and is a 2D barcode
    - [x] Barcode contains all the existing text (might need to check if it all fits on OK)

**References**
Bear in mind these 2 previous stories around this label:
- https://github.com/sanger/limber/pull/1595
- https://github.com/sanger/limber/pull/1567

**Additional context**

We did consider using a 1D barcode but changing it to use ean13 encoding rather than code39 or code128 (see [here](https://sprint.psd.sanger.ac.uk/?labelType=plate_96&printRequest=%7B%22layouts%22%3A%5B%7B%22textFields%22%3A%5B%5D%2C%22barcodeFields%22%3A%5B%7B%22x%22%3A1%2C%22y%22%3A1%2C%22value%22%3A%22NT1739237I%22%2C%22cellWidth%22%3A0.1%2C%22height%22%3A2%2C%22rotation%22%3A%22north%22%2C%22barcodeType%22%3A%22code128%22%7D%2C%7B%22x%22%3A%2226%22%2C%22y%22%3A1%2C%22value%22%3A%22NT1739237I%22%2C%22cellWidth%22%3A0.1%2C%22height%22%3A2%2C%22rotation%22%3A%22north%22%2C%22barcodeType%22%3A%22code39%22%7D%2C%7B%22x%22%3A%2256%22%2C%22y%22%3A1%2C%22value%22%3A%223981739237738%22%2C%22cellWidth%22%3A0.1%2C%22height%22%3A2%2C%22rotation%22%3A%22north%22%2C%22barcodeType%22%3A%22ean13%22%7D%5D%7D%5D%7D) that ean13 is shorter). However, this would cause problems because ean13 only accepts numeric characters and therefore we would need to use the 'machine readable' form of the barcode (13 digits). Users would prefer to use the 'human readable' form of the barcode (NT...). Using a 2D barcode means that we can use the 'human readable' version, and fit it easily onto the tube.

See the label `tube_traction_compatible` as an example of a 2D barcode in Limber (however, note that that is using a 'tube' label, whereas here we want to use a 'plate' label).

**Comment by KatyTaylor** [comment]
This is on hold, pending a final decision on whether a tube printer will be purchased or not.

**Comment by KatyTaylor** [comment]
Taken 'off hold' after comment from Abby in Slack:

> For this story, we are happy with a 2D barcode on a plate label if you can do that?
We have a suitable scanner and we have tested this label setup and it seems to work for us

**Comment by yoldas** [comment]
@SHIV5T3R Could you write down somewhere in the story or the PR which locations on the printed barcode is showing what information please?
2D barcode image, top-left, bottom-left, top-right, bottom-right.

**Comment by SHIV5T3R** [comment]
> @SHIV5T3R Could you write down somewhere in the story or the PR which locations on the printed barcode is showing what information please? 2D barcode image, top-left, bottom-left, top-right, bottom-right.

<img width="1123" alt="Screenshot 2024-06-21 at 11 08 01" src="https://github.com/sanger/limber/assets/44001656/c7b97196-8a75-4855-816c-9465b7bc7ac9">

Top-left - Date
Bottom-left - Barcode
Top-right - Parent barcode
Bottom-right - Name
