### ISSUE TITLE
Y24-119 Add 'SGE Library v0.2' library type to Limber Bespoke PCR templates

### ISSUE THREAD

**Issue by neilsycamore** [sanger/limber#1721]
As Short Read team (Matt M) we would like the library type  added to the following Limber Bespoke templates so that they apprea on the Submissions new page

Limber-Bespoke - PCR - MiSeq sequencing
Limber-Bespoke - PCR - NovaSeq 6000 Paired end sequencing
Limber-Bespoke - PCR - NovaSeqX paired end sequencing
Limber-Bespoke - PCR - Pool

![Screenshot 2024-06-04 at 16 56 05](https://github.com/sanger/limber/assets/299768/0128d1bc-d2d6-455e-a49f-0b93ceed27de)

**Who are the primary contacts for this story**
mm7, slw

raised in [RT803442](https://rt.sanger.ac.uk/Ticket/Display.html?id=803442)

**Comment by andrewsparkes** [comment]
Library type already exists in the SS database so just need to add it to the list in the request type in the SS configs.

**Comment by andrewsparkes** [comment]
Tested and all 4 submission templates mentioned above are serviced by the one list changed in the PR
