### ISSUE TITLE
Y24-165 - As PO I would like the an initial backlog of user stories to be drafted to deliver the EMSeq pipeline.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/limber#1747]
**Description**
SeqOps would like to move the DNA - EMSeq pipeline from R&D / Bespoke to production to support a larger number of samples coming through.

**Additional Context or Information**
[Google Doc description](https://docs.google.com/document/d/1HcQFBiFNBCYqKC6FDYGJX6FV-XbLYxrRJfJV_L14hj4/edit?usp=sharing)

[Process Map](https://lucid.app/lucidchart/b71a82e4-ca5c-4fb4-a2bb-4f16e21f6376/edit?viewport_loc=-20210%2C-15946%2C26935%2C33976%2CpY0tJQ3FKvrSt&invitationId=inv_80dd70e7-82ea-4415-b592-c507c64af359)

**Acceptance Criteria**
- [x] Annotated Process Map with User Stories created (on tab in existing Lucid chart above)
- [x] Backlog of labelled and roughly sized user stories written to deliver the pipeline.
- [x] Creation of page on Confluence under Pipelines to link to these resources.
- [x] Any outstanding questions or risks captured and documented in stories or Confluence as appropriate. [initial questions are in overview google doc]

**Knowledge or Stake holders**
Scott G created the process and the process map
Sara W is the manager responsible.

**Stories created**
1. [Research story](https://github.com/sanger/sequencescape/issues/4200)
2. [Pipeline configuration story](https://github.com/sanger/sequencescape/issues/4199)
3. [Bed verifications story](https://github.com/sanger/limber/issues/1782)

**Comment by andrewsparkes** [comment]
Initial thoughts on stories:
1. research story to determine how to do the submissions (small to medium)
2. pipeline configuration story, SS and Limber plus integration suite test with placeholder manual transfer steps where robots will be used (medium to large)
3. bed verifications story, plus update integration suite test with robot steps (small)

**Comment by andrewsparkes** [comment]
Might have to fold 1 into 2 as you'd need some of the pipeline built in order to test the options?

**Comment by andrewsparkes** [comment]
Added stories to description
