### ISSUE TITLE
Y24-171 - Driver file: PBMC pools --> 10x chip

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1753]
**User story**
As a user of the scRNA Core pipeline, I would like a csv driver file for the robot transfer from the PBMC pools plate to the 10x chip.
(We do not need a csv for the transfer out of the chip)

**Who are the primary contacts for this story**
Abby, Andrew, Katy

**Who is the nominated tester for UAT**
Abby

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Robot driver file for transfer from LRC PBMC Pools Input --> LRC GEM-X 5p Chip
- [x] Robot driver file for transfer from LRC PBMC Pools --> LRC GEM-X 5p Chip
- [x] Columns: 
    - Source Plate ID (= plate barcode)
    - Source Plate Well (= map description e.g. 'A1')
    - Destination Plate ID (= plate barcode - using a normal plate barcode even though it's a 10x chip)
    - Destination Plate Well (= numbers 17-24 as this is how the robot will label the chip's 8 wells)
    - Sample Vac Tube ID (held in sample metadata supplier name for this pipeline)
    - Sample Name (= sample.name)
 - [x] Driver file name to include the barcode of the source plate at the start of the file (see https://github.com/sanger/limber/issues/1521 for how).

Updates 10 July:

- [x] 1. Sharing the same button for both LRC PBMC Pools and LRC PBMC Pools Input is fine. [Button: Download Hamilton LRC PBMC Pools (or Input) to LRC GEM-X 5p Chip CSV]
- [x] 2.a. Change Workflow header to 'scRNA Core GEM-X 5p Chip Loading'
- [x] 2.b The filename is too long (>60 characters); shorten it to 'SQPD-9144_hamilton_gem_x_5p_chip_loading.csv
- [x] 2.c At this stage we just need to list the pools on the pool plate i.e. up to 8 lines. If we don't have any identifying information for these (that could be captured as 1 name per pool/well) then we could leave out the sample name/vac tube columns. [Removed the sample name/vac tube columns columns]
- [x] 2.d As mentioned at c., we would actually omit the vac tube column now they are pools of various ones. [Removed the sample name/vac tube columns columns]
- [x] 2.e we will be loading variable volumes of sample onto the chip so we would like a volume column to be included in this csv. This volume will be decided by the pooling strategy which is still not yet finalised however [Created Story: #1779]

**Additional context**
See Slack thread [About Y24-171 - Driver file: PBMC pools --> 10x chip](https://sanger-global.slack.com/archives/C05F21NKATD/p1720598036896949)

**Comment by yoldas** [comment]
See also GitLab Integration Suite branch [Y24-171 Driver file PBMC Pools to 10x Chip](https://gitlab.internal.sanger.ac.uk/psd/integration-suite/-/merge_requests/140)
