### ISSUE TITLE
Y24-177 - Modify Aggregation submission

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1767]
**Background**
We decided in a meeting with Abby & Liz H to make the Library Prep submission 'generic': the template name is:

`Limber-Htp - scRNA Core Library Prep`

rather than 

`Limber-Htp - scRNA Core GEM-X 5p Library Prep`

This mirrors the equivalent submission template for the Bespoke Chromium pipelines, which is:

`Limber-Bespoke - Chromium`

The downside is that there could be user error when making a submission, in that they could include a GEM-X 5p purpose, but use a GEM-X 3p library type, for instance (when other variants of the pipeline come in).

The upside is that we won't have proliferation of submission templates when other variants come in.

**This story**
I suggest we do the same for the aggregation step - make it more generic - for the same reasons discussed above, and to make it consistent with the library prep submission.

**Who are the primary contacts for this story**
Katy, Andrew, Abby, Liz H

**Who is the nominated tester for UAT**
Abby (R&D), Liz H (SSR)

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Aggregation submission template is called `Limber-Htp - scRNA Core Aggregation` (I removed the word 'Chromium' as well as it seems redundant with 'scRNA Core')
- [x] Request type is changed accordingly
- [x] [Documentation](https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/scRNA+Core+Pipeline+Documentation) is updated to include this submission, including submission template name, appropriate plate purposes to use and any other information you think is useful.

**Comment by yoldas** [comment]
"The downside is that there could be user error when making a submission, in that they could include a GEM-X 5p purpose, but use a GEM-X 3p library type, for instance (when other variants of the pipeline come in)."

Update of Confluence documentation could be added as acceptance criteria. If the documentation is advertised more and made visible, it may help. [scRNA Pipeline Documentation](https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/scRNA+Core+Pipeline+Documentation)

**Comment by andrewsparkes** [comment]
The TenStamp labware creator used in the aggregation steps might need a validation added to prevent mixtures of source plates being combined. (It might already have this but we should confirm).

Would the Aggregation purpose created here still be specifically named after the sources e.g. with GEM-X 5p in the name? Because on the second stage of aggregation where you are combining the aggregate plates you'd also have to prevent combinations of a mixture of aggregate plates (made from different source types).

**Comment by KatyTaylor** [comment]
Good ideas, thanks both. 

> The TenStamp labware creator used in the aggregation steps might need a validation

We could run this by Abby. We've got a lot of potential enhancements in the backlog to avoid user error, so this could be prioritised against them. Agreed need to test if it already does it first though! I might find time for that today.

> Would the Aggregation purpose created here still be specifically named after the sources e.g. with GEM-X 5p in the name?

Current config is:
```
LRC GEM-X 5p cDNA Input: LRC GEM-X 5p Aggregate
LRC GEM-X 5p cDNA PCR XP: LRC GEM-X 5p Aggregate
LRC GEM-X 5p Aggregate: LRC GEM-X 5p Cherrypick
```

I think that's fine? The purposes are v specific all the way down the pipeline so ties in with that.

**Comment by KatyTaylor** [comment]
Update on the above:

The 'ten stamp' page used for the aggregation pipeline doesn't restrict plate type. In the below screenshot, the first plate was a 'LRC GEM-X 5p cDNA Input plate' (appropriate), and the second was a 'Stock' plate (inappropriate). It let me create the plate.

![Screenshot 2024-07-05 at 14 50 22](https://github.com/sanger/limber/assets/10407809/a6c6bd07-5402-4705-97b7-f71351952fb8)
