### ISSUE TITLE
Y24-197 - Add fail feature to start of GBS pipeline

### ISSUE THREAD

**Issue by neilsycamore** [sanger/limber#1781]
As GSLP Operational Lead (Anna) responsible for the operation of the GBS pipeline we would like the ability to fail wells in the "SWGA Stock" and/ or in the "GBS PCR 1" plate similar to the Heron 384 pipeline.

Context
We have processed GBS Plasmodium samples that could/should have been failed upstream, post extraction. However the samples have continued through the pipeline, sequenced and results sent to partners. The repeat work (6x months after) has now been processed and we have come to find duplicate samples data sets.

Example of where we would like to implement a fail feature
Problem plate: SQPP-15788-1-N
![GBS_fail_feature_low_ng](https://github.com/sanger/limber/assets/299768/58bb6b5b-3c08-4251-bf7c-0f038c306a2d)
Within the QC tab on Sequencescape "quantity in ng"  the drop out in row C can be seen.
It is at this stage in the process, when verifying the quant data that we would like to ability to fail wells in the "SWGA Stock plate" and/ or at the "GBS PCR 1"

**Who are the primary contacts for this story**
Anna(ag25)

**Who is the nominated tester for UAT**
Anna(ag25)

**Comment by andrewsparkes** [comment]
Existing primer panel summary:

![pic1](https://github.com/user-attachments/assets/35a5216a-ff31-4063-81d6-bb8875114614)

**Comment by andrewsparkes** [comment]
New Presenter with plate view plus primer panel:

![pic2](https://github.com/user-attachments/assets/c8ddc7a2-bb74-4186-9d9d-634526cd9e5f)
