### ISSUE TITLE
Y24-250 - Addition of anonymous ids for public data sharing - Plate Genie

### ISSUE THREAD

**Issue by AnnaGalvin** [sanger/limber#1851]
**User story**
As a member of GSU, I would like RVI samples (Brants bridge elution plates) imported via Plate Genie to have an anonymous id added to them, so that when they are shared in public databases, the id does not give any unnecessary information.

**Who are the primary contacts for this story**
Anna G / Adrianne L

**Who is the nominated tester for UAT**
Anna G / Ya-Lin H

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Samples imported via Plate Genie for RVI have an id created and inserted into the public name (?) field
- [ ] Id is created using Baracoda (WSI prefix)

**References**
This story has a non-blocking relationship with:
- https://github.com/sanger/limber/issues/1895
- https://github.com/sanger/limber/issues/1896

**Additional context**
Original request from Anna: "GSU would like to apply additional level of security in relation to sample IDs. This will need to be applied to future and all retrospective samples within RVI." (was split into 3 stories).

N.B. Is it worth checking before doing this story if the Sanger Sample Id would be sufficient? Is this used for existing samples in other studies? We discussed using the accession number but think this is not appropriate because it is specific to EBI and this will potentially be released to other databases as well.

**Comment by TWJW-SANGER** [comment]
@KatyTaylor 
Needs to be split into 3 stories.

**Comment by TWJW-SANGER** [comment]
I know we discussed that the WSI prefix would be used for the Anon ID could it be the RVI one instead. It’s still anon enough not to distinguish location.

**Comment by TWJW-SANGER** [comment]
Using the RVI prefix name for the anon public name.
So this is not required
