### ISSUE TITLE
Y24-276 - (Pre-MVP) Create stories for new scRNA Core PBMC pooling strategy

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1865]
**Description**
https://github.com/sanger/limber/issues/1611 has been on hold while R&D were coming up with the PBMC pooling strategy for scRNA Core. Abby has now shared a draft strategy in the form of an Excel spreadsheet - 
[Phase 2 pooling, cell counting & chip loading approaches for PSD (2).xlsx](https://github.com/user-attachments/files/16729871/Phase.2.pooling.cell.counting.chip.loading.approaches.for.PSD.2.xlsx)

Acceptance Criteria:
- [ ] Create & size stories to implement pooling strategy as described in the shared spreadsheet.
- [ ] Document any remaining uncertainties.

**Who the primary contacts are for this work**
Katy, Abby

**Comment by sdjmchattie** [comment]
Could you confirm what is needed to be reviewed here?  Thanks.

**Comment by KatyTaylor** [comment]
I'm splitting this story to reflect the two stage approach that we've decided to do.

The outcome of this story is the following 5 stories to support the (pre-MVP) end to end pipeline test that R&D are doing:
- https://github.com/sanger/limber/issues/1909
- https://github.com/sanger/limber/issues/1914
- https://github.com/sanger/limber/issues/1915
- https://github.com/sanger/limber/issues/1779
- https://github.com/sanger/sequencescape/issues/4337

The second half, which I will create a new story for, will be to develop whatever else is needed to create the MVP. [I already have the draft stories in this google doc.](https://docs.google.com/document/d/15D9IwpRKB5KochuXYPEkZMYJnOf-KNXxdrxPvIx31Uk/edit?usp=sharing)
