### ISSUE TITLE
Y24-321 - Cell counting driver file for pools plate

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#1915]
**User story**
As a user of the scRNA Core pipeline, I would like the LIMS to generate a driver file for the transfer from the LRC PBMC Pools plate to the Cellaca plate.

**Who are the primary contacts for this story**
Abby, Katy

**Who is the nominated tester for UAT**
Abby

**Acceptance criteria**
- [x] Cell counting driver file download available on LRC PBMC Pools plate.
- [x] Based on `hamilton_lrc_pbmc_defrost_pbs_to_cellaca_count` (as on 'LRC PBMC Defrost PBS' plate).
- [x] Includes columns 'Plate Barcode', 'Well Position', 'Well Name' as in above file.
- [x] Includes additional column, 'Source well volume', which is calculated as:
    - (Number of samples in pool x 30,000 x 0.95238) / 2,400
    - Where:
        - 30,000 is the required number of cells
        - 0.95238 is accounting for wastage of material when transferring between labware
        - 2,400 is the desired chip loading concentration

**References**
Uses same calculation as in https://github.com/sanger/limber/issues/1914 

**Additional context**
This is for the 'pre-MVP' version, to be used for R&D's end to end test. For the MVP version, we may want to refactor to store the constants in a more central place, or do the calculation once and use the stored result for both https://github.com/sanger/limber/issues/1914 and this story.

All wells are counted, like on the LRC PBMC Defrost PBS plate, and unlike on the LRC PBMC Bank plate.

**Comment by dasunpubudumal** [comment]
Integration suite PR (well, "Merge Request" to be precise): https://gitlab.internal.sanger.ac.uk/psd/integration-suite/-/merge_requests/168
