### ISSUE TITLE
GPL-289	As an SSR I would like to be able to create submissions using the submission templates beginning with ‘Limber-Bespoke – PCR’ (excluding ‘PCR Free’ ones) with a new library type called ‘HiC’.

### ISSUE THREAD

**Issue by rl15** [sanger/limber#349]
Acceptance Criteria:
New library type ‘HiC’ (Sequencescape)
Available for request type ‘Limber PCR Bespoke’ (Sequencescape)
This should be configured to go down the ‘Bespoke PCR’ pipeline (Limber)

NB please see https://ssg-confluence.internal.sanger.ac.uk/x/Tqo6BQ

**Comment by KatyTaylor** [comment]
Need to run this after deployment to enable upload of the bulk submission template:

lib = LibraryType.find_by(name: 'Hi-C')
rt = RequestType.find_by(name: 'Illumina-B HiSeq X Paired end sequencing')
rt.library_types << lib
