### ISSUE TITLE
GPL-295 Duplex-Seq New Labware creator for LDS AL Lib Dil plate

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/limber#356]
**Story**: As the Duplex-Seq pipeline developer I need to create a new labware creator class to make the LDS AL Lib Dil plate.

_Acceptance criteria_:

- created a new Labware creator for the LDS AL Lib Dil plate purpose
- includes upload of the CASM modified concentration file
- validates the uploaded file
- stores the extra values from CASM file as Well metadata on the new child Dil plate (PCR cycles, Sub-pool and Coverage)
- uses the PCR cycles values to determine binning for samples in plate (see other binning Labware creators for Chromium as examples)
- creates the new Dil plate

**Comment by KatyTaylor** [comment]
Tasks:

1. Upload of csv file in Limber
2. Saving of data to well metadata
3. Binning calculation
4. Integration Suite update to handle creator
