### ISSUE TITLE
GPL-239	As a lab team lead (Jamie & Sara) we would like a pool plate map visualization with counts to support making pools in the laboratory as ESP is no longer supported by NPG

### ISSUE THREAD

**Issue by rl15** [sanger/limber#375]
From a plate with pooling tab
Link to 'print friendly version' 

Show for each well:
* Pool (by colour)
* Sanger sample id
* Bait Libary if ISC (n/a if not)

And for plate the number lanes / pool

Print friendly should be 1 plate per A4

**Comment by pjvv** [comment]
Tasks:
* ~~Pool (by colour)~~
* ~~Sanger sample ID~~
* ~~Bait library if ISC (n/a if not)~~
* Number of lanes/pool - need more info when subpool (pre cap pools)
* Tests

**Comment by JamesGlover** [comment]
Picked this back up after a long time, requirements are slightly different in that they now need species. Bait library wasn't mentioned, but should be addable

**Comment by neilsycamore** [comment]
When I ask Carol S (NPG) about what data was accessed from the retiring Oracle dbs she replied "..if i remember correctly it's something to do with baits and species"

**Comment by KatyTaylor** [comment]
Closing, as is in Done column.
