### ISSUE TITLE
GPL-351 As development team (Andrew, Katy & Rich) we would like to configure two Heron pipelines to allow a) consolidation 4x96 to 1 384 and then the SC pipeline to Normalised library pool as this is a low cost configuration and simplifies troubleshooting, and b) the same but without consolidation into a 384 plate

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#390]
_**Update - story changed - see later comments**_

Heron (384) pipeline steps:

- Entry plate - LHR Cherrypicked
- 4 into 1 - LHR 384 XP
- Bed verification for above step
- LHR 384 End Prep
- Bed verification for above step
- LHR 384 Lib PCR
- Scan tag plate when creating above – same tag plate as for scRNA 384 pipeline
- LHR 384 Lib Pool XP (tube)
- LB Lib Pool Norm

Heron (96) pipeline steps:

- Entry plate - LHR Cherrypicked
- Stamp to LHR XP
- LHR End Prep
- Bed verification for above step
- LHR Lib PCR
- Scan tag plate when creating above – same tag plates as for scRNA (96) pipeline (pWGS a, b, c & d)
- LHR Lib Pool (extra step here compared with above because is manual pooling, not robot)
- LHR Lib Pool XP
- LB Lib Pool Norm

 
There are no robot driver file downloads or Quanthub uploads. I might have missed some detail on the above pipelines – when developing them we should compare carefully with the PCR Free, scRNA and scRNA-384 pipelines they are based on to check for missing functionality.

**Comment by KatyTaylor** [comment]
See this doc for more detail if needed (will have to request read access) - https://docs.google.com/document/d/1X93VHLjXDUn-iloXt7cgLV5kVFXSD7q1zdUnVypavzU/edit

**Comment by KatyTaylor** [comment]
![heron-pipeline-limber](https://user-images.githubusercontent.com/10407809/76844970-033be100-6836-11ea-8204-cb0305745e03.jpeg)

**Comment by KatyTaylor** [comment]
[Sequence of plate types to support Heron pipeline(s).pdf](https://github.com/sanger/limber/files/4355859/Sequence.of.plate.types.to.support.Heron.pipeline.s.pdf)

**Comment by KatyTaylor** [comment]
Given new understanding of process flow, sub tasks as follows:
1. Create 2 PCR plates from the LHR Cherrypick plate
    - primer panels to be linked to the plates
2. Pool 2 PCR plates into the LHR XP plate
    - 2 aliquots into one well, linked to the same sample
    - insight about avoiding tag clash from James (database constraints)
3. Bed verification on PCR plates -> XP
    - ask Scott Thurston for details
4. Bed verification on XP -> End Prep, and End Prep -> Lib PCR
    - see WGS + ISC for details

**Comment by KatyTaylor** [comment]
Thoughts/Tasks from Andrew:

1. Looks like we need to change the Limber Pipeline code to allow 2 child plates to be made on the suggested route with different purposes (LHR PCR 1 and 2). i.e. 2 green buttons. Doesn't currently allow that. Allow arrays of purposes maybe. [Needs research]

2. We need API v2 functionality to allow the selection and setting of Primer Panels on aliquots (or is it on requests?). The end result should look like whatever GBS currently does but we can't directly re-use that code. [Needs research]

3. We need a new plate creator to make the PCR 1 and 2 plates. Same creator should work for both. Lets the user select a suitable Primer Panel from a list (still not clear what a Primer Panel is, but I can see the Admin page James mentioned), and set it up through the new API v2 call to sequencescape. Otherwise it's a stamp (A1->A1 etc). Maybe the primer panel is always going to be the same and can be set in the Limber purpose config. [Needs research]

4. We need to modify the tag clash prevention index restriction on the database to also include primer panel id to allow us to pool the two PCR plates. I think our tags are null at this stage, so two nulls could not be pooled? [Needs research]

5. We need a new plate creator for the merging of the two PCR plates into the one LHR XP plate. Presumably merging combines 2 aliquots into 1 well for each well? How does that work downstream when tags are applied? Do they have the same requests? At 384 level will this slow the processing time enough to timeout the screen? [Needs research]

6. Modify the Test Suite to incorporate these new changes to allow us to run pipeline tests.

**Comment by KatyTaylor** [comment]
New tasks:

1. Add primer panel to Heron submission and pass to warehouse.

2.

**Comment by JamesGlover** [comment]
Did a bit of research on adding primer-panels to aliquots via the v2 API, and it looks pretty simple.

Json api spec: https://jsonapi.org/format/#crud-updating-to-many-relationships

Changes:
```
diff --git a/app/models/primer_panel.rb b/app/models/primer_panel.rb
index fdbd49591..0cdf48488 100644
--- a/app/models/primer_panel.rb
+++ b/app/models/primer_panel.rb
@@ -19,6 +19,8 @@ class PrimerPanel < ApplicationRecord
   validates :snp_count, numericality: { greater_than: 0, only_integer: true }
   validates :programs, programs: true

+  has_many :aliquots
+
   #
   # A summary of the primer panel behaviour, suitable for embedding in
   # eg. pool information via the API
diff --git a/app/resources/api/v2/aliquot_resource.rb b/app/resources/api/v2/aliquot_resource.rb
index 44fc4f95e..2173815a2 100644
--- a/app/resources/api/v2/aliquot_resource.rb
+++ b/app/resources/api/v2/aliquot_resource.rb
@@ -17,6 +17,7 @@ module Api
       has_one :study
       has_one :sample
       has_one :request
+      has_one :primer_panel

       # Attributes
       attribute :tag_oligo, readonly: true
diff --git a/app/resources/api/v2/primer_panel_resource.rb b/app/resources/api/v2/primer_panel_resource.rb
index aa45bb63a..ac76cd369 100644
--- a/app/resources/api/v2/primer_panel_resource.rb
+++ b/app/resources/api/v2/primer_panel_resource.rb
@@ -12,7 +12,9 @@ module Api
       # model_name / model_hint if required
       attribute :name, readonly: true
       attribute :programs, readonly: true
+
       # Associations:
+      has_many :aliquots

       # Attributes
```

Example post request:
![Screen Shot 2020-03-24 at 16 49 01](https://user-images.githubusercontent.com/1283620/77453989-dff1d280-6def-11ea-918c-381d93a646f2.png)

This adds primer panel 1 to aliquots 1 and 2, and leaves any other aliquots untouched.

**Comment by harrietc52** [comment]
See this doc for UAT testing detail if needed (will have to request read access) - https://docs.google.com/document/d/1-qap-ZHLotUjE7FkxNkWOspLLCW1pEu-hh9F-f4Pn_o/edit
