### ISSUE TITLE
GPL-373 Bed verify RT -> PCR plates

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#404]
**User story**
As Emma Betteridge I would like a bed verification step to be included when transferring material from the LHR RT Cherrypick plate into the 2 PCR plates, to avoid plates being put in the wrong positions.

**Who the primary contacts are for this story**
Emma Betteridge

**Acceptance criteria**
1 - Button for bed verification step appears on the LHR RT Cherrypick plate screen in Limber
2 - Robot is Bravo
3 - Verifies that LHR RT Cherrypick is in bed 9
4 - Verifies that PCR plate 1 (barcode is cherrypick barcode plus suffix of '-PP1') is in bed 4
5 - Verifies that PCR plate 2 (barcode is cherrypick barcode plus suffix of '-PP2') is in bed 6
6 - Does no plate state transitions (because the PCR plates are not currently tracked)
7 - Updated Integration Suite heron pipeline test with new bed verification

**Additional context**
See the recently made bed verification from PCR plates to the XP plate for similar code.

**Comment by harrietc52** [comment]
On the Bravo, the RT (Cherrypick) plate will be position 9, the 2 PCR plates will be on positions 4 and 6.
