### ISSUE TITLE
GPL-375 As R&D we would like to track the 2 PCR plates as there is a handover at this point between labs and teams and it is likely that there will be mistakes especially as throughput increases

### ISSUE THREAD

**Issue by stevieing** [sanger/limber#410]
**User story**
'We tried printing the labels and we got the RT label along with the PCR1 and PCR2 labels. When we scanned into LIMBER the PCR labels weren't recognised, but the RT label did and was going straight from RT to the LHR XP plate. Should there be a step in between where the RT plate generates the PCR plate and then PCR to XP plate?

PSD decided to not track the 2 PCR plates in Limber for now, as it made development quicker. The bed verification step should still recognise the PCR plates barcodes though.

 We are slightly concerned about not tracking the PCR plates as there is a handover at this point between labs and teams. We can manage it via paperwork and training, but it’s likely ops will ask for changes to this part of the pipeline in the future.'

[
Bed verification does recognise the PCR plates.

Deliberately designed this way for version 1 but clearly not communicated properly to Lesley. Adding the Limber plate creators to make the PCR plates and do the merge of the two PCR plates into the XP plate was too expensive in development time for version 1, plus existing restrictions when merging aliquots means the solution may break other Limber pipelines. 
Andrew.
]

**Who the primary contacts are for this story**
Lesley Shirley

**Acceptance criteria**
To be considered successful the solution must allow:
1. PCR plates 1 and 2 are both tracked in Limber and can be scanned
2. Bed verifications for RT to PCR 1 and 2, and from PCR 1 and 2 to XP work.
3. Aliquots from PCR 1 and 2 are merged down to 1 aliquot per well in the XP plate.
4. Primer panel choice from the Submission is retained.

**Sub-tasks**
1. Sequencescape and Limber - Research how to do the merge of aliquots without breaking other pipelines. [James has given details of how this is done in another pipeline. Plus here the aliquots will now have the same primer panel name and we can merge two aliquots down to 1, reducing complexity later in the pipeline. **WIP**]
  - Sequencescape currently enforces a uniqueness constraint on all aliquots within a receptacle such that they have unique tag-tag2 combinations. (untagged aliquots are represented by the id -1, as MySQL acts as though null != null) This is enforces at the database level. 
  - If we were to track primer panels independently this would violate this constraint, as primer panels are being used prior to tagging. The safest fix for this would be to add primer_panel_id to the uniqueness key, and use -1 rather than null to indicate no primer panel.
  - This would slightly increase the risk of tag clashes in GBS if the same tags were used for two different primer panels. Although I think we do enforce these checks as part of the plate creation.
  - If we DON'T track two separate primer panels, and continue with the current system, then we should follow a similar practice to that used in the FlexibleCherrypick pipeline. Here we create transfer requests from both parents, but de-duplicate aliquots with the same information.
2. Limber - modify configuration to allow branching at the RT plate and set the purposes for the PCR plates. [**DONE**]
3. Limber - labware creator for PCR plates, one creator to handle both types. Potentially allow override of submission primer panel choice if required. Otherwise this may be a simple stamp. Will they select 2 distinct primer panel ids, one for each plate? [Simple stamp **DONE**]
4. Limber - labware creator for PCR plates to XP plate. Select / scan both PCR plates and merge aliquots to create XP plate. [**DONE**]
5. Limber - modify bed verifications for both steps [**DONE**]
6. Integration Suite - modify heron test to perform these extra steps. [**DONE**]
7. Limber - Help panel on labware creator to take purposes from heron purposes configuration to make more user-friendly help message possible i.e. Scan the following plates: LHR PCR 1 and LHR PCR 2. [**Not Started**]
8. Sequencescape - Fix bug in tag clash rescue code that is allowing silent failure. [**WIP**] Our understanding is that SS is not returning an http error when a tag clash is happening, so Limber thinks that everything is correct. From API v1, TransferRequestCollection.create should raise a Aliquot::TagClash exception inside an after_create callback, however, that exception is either rescued or ignored by API v1 before reaching the ErrorHandler middleware in Sinatra that would generate a http error.
9. Sequencescape - Add de-duplication for identical aliquots in transfer requests for merging plates without breaking other pipelines. [**Not Started**]

**Additional context**
Need to clarify details with R&D / Ops:
1. Do they want the ability to set / override a distinct primer panel selection for PCR 1 and 2? **NO. Naomi clarified on Friday 3rd April.**
2. If 1, do they want to set the two distinct primer panel choices in the Submission? And what is put into MLWH? **N/A**

**Comment by JamesGlover** [comment]
Email to R+D: https://docs.google.com/document/d/1vyNg6CE0G2cUQdqGj7Oa8VVjPFhjTtZug6Wg7DFaGYQ/edit?usp=sharing

**Comment by andrewsparkes** [comment]
Awaiting email response from R&D regarding primer panel tracking question.

**Comment by JamesGlover** [comment]
Aliquot de-duplication in the flexible cherrypick pipeline is handled by PooledCherrypickRequest, rather than a TransferRequest.

In particular:

```ruby
# app/models/pooled_cherrypick_request.rb

  def transfer_aliquots
    target_asset.aliquots << aliquots_for_transfer
  end

  private

  def aliquots_for_transfer
    asset.aliquots.map do |aliquot|
      aliquot.dup.tap do |clone|
        clone.study_id   = initial_study_id   || aliquot.study_id
        clone.project_id = initial_project_id || aliquot.project_id
      end
    end.reject do |candidate_aliquot|
      target_asset.aliquots.any? { |existing_aliquot| existing_aliquot.equivalent?(candidate_aliquot) }
    end
  end
```

```ruby
# app/models/aliquot.rb


  # Unlike the above methods, which allow untagged to match with tagged, this looks for exact matches only
  # only id, timestamps and receptacles are excluded
  def equivalent?(other)
    %i[
      sample_id tag_id tag2_id library_id bait_library_id
      insert_size_from insert_size_to library_type project_id study_id
    ].all? do |attrib|
      send(attrib) == other.send(attrib)
    end
  end
```

Looking at this now, primer panel should probably be in the list of equivalent attributes. In fact, it would be safer to whitelist permitted differences (id, timestamps...) and check the whole list, otherwise we'll keep introducing bugs here whenever aliquot changes.

**Comment by JamesGlover** [comment]
Naive option would be to add this behaviour straight into TransferRequest, two risks I see with that:
1) Performance. We transfer a LOT of aliquots all over the place, what would the impact of this test be on say a 384 well stamp, or pooling 384 aliquots into one tube.
2) Behaviour. Currently if you try and pool #equivalent? aliquots via a transfer request, you'll throw an exception, as it'll trigger a tag clash. Following this it would permit the action, with no indication that anything is 'wrong'. However:
   - I don't recall actually seeing anything trigger this particular exception, tag clashes are usually between different samples.
  - Its hard to say that the resulting behaviour is incorrect as such, but it does feel like something that shouldn't be occuring unless we're expecting it.


- 

1.

**Comment by JamesGlover** [comment]
For prosperity:
Point 2 in my comment above was *not* true, and instead duplicate aliquots were being filtered out silently. This would also affect genuine tag clash situations. Before adding the new behaviour we needed to fix the intended tag clash behaviour.
Investigation revealed that Rails was rescuing ActiveRecord::RecordInvalid errors itself, and while the various callbacks were being aborted, the exception wasn't being raised further. The solution was to change Aliquot::TagClash to inherit from StandardError instead.

**Comment by emrojo** [comment]
Dependents changes from other projects:
* https://github.com/sanger/sequencescape/pull/2610
* https://github.com/sanger/sequencescape/pull/2612
* https://github.com/sanger/sequencescape-client-api/commit/e934b023d186394e751b0834a93502f489ce3b04

**Comment by andrewsparkes** [comment]
Awaiting on Jamie to decide deployment day/time.

**Comment by JamesGlover** [comment]
Looks like the tag clash error changes have prevented a proper error message from getting returned to the user. Should be a simple enough fix. https://github.com/sanger/sequencescape/issues/2883
