### ISSUE TITLE
GPL-511 Process tubes together as a collection (C=M)

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#439]
**User story**
Coming out of discussion recorded here - https://ssg-confluence.internal.sanger.ac.uk/pages/viewpage.action?pageId=101361052

As a user of Limber, I want to be able to process several tubes together, as a collection, so I don't have to individually click through each one.

**Who the primary contacts are for this story**
Andrew, Stef

**Acceptance criteria**
Details TBC. Here as a placeholder as thought about during tube rack purposes discussion.

**Additional context**
There is a use case in the Chromium pipeline.

**Comment by JamesGlover** [comment]
E-mail from MM chasing request for 'pass all tubes' functionality on 12/11/20, which this functionality is intended to provide.

Main limitation of providing 'pass all tubes' directly, is that there are actually two rounds of tube creation, so the functionality would need to:
1) Find all child tubes of the plate
2) Validate that none of the children need to be pooled with other tubes (I'm not sure how to handle scenarios where they do)
2) Pass each one in turn (as there is nom collection to add to)
3) Create a child tube and transfer for each tube in turn (Which will mostly involve the final tube tube transfer action, so actually looking up the MX tube associated with each)
4) Finally, pass each of the grandchild tubes.

This is a lot of heavy lifting for a single action, and would be quite brittle, needing to take into account possible variations in the end of the pipeline. And this still doesn't cover somehow presenting the result of all this to the user.

Adding tube collections would:
1) Provide more feedback of the steps
2) Allow things like 'State changes' to be preformed in a single API request
3) Be more reusable

**Comment by JamesGlover** [comment]
A 'collection' could potentially be implemented with racks: https://github.com/sanger/limber/issues?q=is%3Aissue+is%3Aopen+tube
