### ISSUE TITLE
GPL-621 Did we finish Duplex seq?

### ISSUE THREAD

**Issue by rl15** [sanger/limber#477]
**Description**
GPL-621 | [Research] As lead for Duplx Seq (Steph) I would like to PSD to deploy Duplex Seq to staging so R&D can UAT the pipline that we think was delivered in March 2020

**Who the primary contacts are for this work**
Steph L
Andrew S
Katy T
& one other to improve team liquidity

**Additional context or information**
Kanban board should accurately capture state of art when team walked out of office on 23rd March: https://github.com/orgs/sanger/projects/3

**Comment by andrewsparkes** [comment]
Branches in SS and Limber updated to latest develop code. Integration Suite and all tests passing. See PRs:
https://github.com/sanger/sequencescape/pull/2568/files
https://github.com/sanger/limber/pull/387
https://gitlab.internal.sanger.ac.uk/psd/integration-suite/-/merge_requests/16

**Comment by andrewsparkes** [comment]
Stef would like to test the pipeline from Wednesday to Saturday next week (14th-17th Oct).
