### ISSUE TITLE
GPL-635 New 384 tailed heron workflow 

### ISSUE THREAD

**Issue by rl15** [sanger/limber#480]
**User story**
GPL-635 | As a member of R&D (Lesley, Iraad, Emma B) we would like a new pipeline to support a tailed heron workflow in a 384 well format to reduce TRT

**Who are the primary contacts for this story**
Lesley S
Iraad B
Emma B

**Acceptance criteria**
To be considered successful the solution must allow:

- [x] Library type must be ~~Heron LTHR-384~~ PCR amplicon tailed adapters 384
- [x]  Request type must be ~~Heron LTHR-384~~ Limber Heron LTHR
- [x] Plate purposes:
~~Heron~~ LTHR-384 RT
~~Heron~~ LTHR-384 PCR 1
~~Heron~~ LTHR-384 PCR 2
~~Heron~~ LTHR-384 Lib PCR 1 [Tagged Plate]
~~Heron~~ LTHR-384 Lib PCR 2 [Tagged Plate]
~~Heron~~ LTHR-384 Lib PCR pool [Merged Plate]
- [x] Tube Purposes
LTHR-384 Pool XP (Picked Pool XP not Lib Pool XP for consistency with existing Heron)

see word document for bed verifications, from link below

**Additional context**
Workflows available:  https://ssg-confluence.internal.sanger.ac.uk/x/u4meBg

**Comment by JamesGlover** [comment]
A while since we've touched Limber, so updating dependencies first. Dev was already ahead of master, but still a bit dated.

**Comment by JamesGlover** [comment]
Checked with @andrewsparkes and @KatyTaylor and it looks like we get this for free.

**Comment by JamesGlover** [comment]
Question sent to R&D
> Sorry,
> 
> Another question.
> 
> The requirements say:
> Request type must be Heron LTHR-384
> 
> Almost all other Limber request types are preceded by ‘Limber.’  Has the ‘must’ slipped in accidentally here, or is there a reason for wanting a different naming convention?
> 
> James

**Comment by JamesGlover** [comment]
Also getting clarification on the robot layout specified. There is an existing bravo layout that differs from that listed here, but that doesn't appear to have even been used, and it looks like we can just update it. (Asset audits) awaiting confirmation.

**Comment by JamesGlover** [comment]
Existing bravo configuration was set-up as a fallback. Don't need two seperate configs, but would prefer the one listed in the story.

The actual bravo used it NOT the one already listed, waiting on a barcode.

**Comment by JamesGlover** [comment]
Renamed library type to 'PCR amplicon tailed adapters 384' for consistency with existing pipelines.
Also, opted for Heron LTHR for request-type to be consistent with other 96/384 variants where the same request type is used.

**Comment by JamesGlover** [comment]
Completed 1st draft:

- Purpose configuration
- Pipeline configuration
- Robot configuration
- Request type configuration
- Submission Template configuration
- Integration suite tests

About to run integration suite

**Comment by JamesGlover** [comment]
Assed audits PR
https://github.com/sanger/asset_audits/pull/205
