### ISSUE TITLE
GPL-636 New 96 tailed heron workflow (blue light option)

### ISSUE THREAD

**Issue by rl15** [sanger/limber#481]
User story
GPL-636 | As a member of R&D (Lesley, Iraad, Emma B) we would like a new pipeline to support a tailed heron workflow in a 96 well format to blue light priority samples if insufficient short term demand to use 384 plates

Who are the primary contacts for this story
Lesley S
Irrad B
Emma B

Acceptance criteria
To be considered successful the solution must allow:
- [x] Library type must be Heron LTHR
- [x] Request type must be Heron LTHR
- [x] Plate purposes:
Heron LTHR RT
Heron LTHR PCR 1
Heron LTHR PCR 2
Heron LTHR Lib PCR 1
Heron LTHR Lib PCR 2
Heron LTHR Lib PCR pool

see word document for bed verifications

Additional context
Workflows available: https://ssg-confluence.internal.sanger.ac.uk/x/u4meBg

Effective dependency on:
https://github.com/sanger/limber/issues/480

Due to supporting code changes.

**Comment by JamesGlover** [comment]
> Hi Leslely,
> 
> I just want to confirm the tag groups listed on the 96 workflow:
> 
> TS_pWGSA_UDI96
> TS_pWGSB_UDI96
> TS_pWGSC_UDI96
> TS_pWGSD_UDI96
> 
> Are all fine, and unambiguous
> 
> TS_RNAhWGS_UDI96 doesn’t exist, but the similarly named TSRNAhWGS_UDI96 does, so I’ll go with that.
> 
> TS_SC_UDI96 also doesn’t exist
> 
> I’m assuming this was accidentally named TSISC_UDI96, although as both ISC and SC are a thing, this might be something else entirely. There’s also TSISC_UDI96, which is much newer, but similarly badly named (unless it is ISC related of course).
> 
> We also have: TS_pWGSA_UDI96v2 on the list of templates, this has been added for other pipelines. Should we add that too? (I’ve forgotten the exact details, I think it was intended to replace V1 due to dropouts, but if I recall correctly there was a bit of strangeness going on . I think we fixed that)

Reply:

> Hi James,
> 
> Can we take the 2 we're not sure about off the list for now? Ben added them on and I'm not certain of the group name or if they're even needed. He's on leave at the moment so I can't chase it either.
> 
> Please just go with;
> TS_pWGSA_UDI96
> TS_pWGSB_UDI96
> TS_pWGSC_UDI96
> TS_pWGSD_UDI96
> 
> And also TS_pWGSA_UDI96v2. I believe the problem we had with this tag set earlier in the year was solved.
> 
> Apologies if we've caused confusion.
> 
> Best wishes,
> Lesley

**Comment by JamesGlover** [comment]
For future reference, more discussion about 384 well version, including library and request type naming decisions:
https://github.com/sanger/limber/issues/480
