### ISSUE TITLE
GPL-637 New Library construction to form the Lib PCR plates

### ISSUE THREAD

**Issue by rl15** [sanger/limber#482]
**User story**
GPL-637 | As a member of R&D (Lesley, Iraad, Emma B) we would like a new library construction step where tags are added to the PCR plates to form the Lib PCR plates

**Who are the primary contacts for this story**
Lesley S
Iraad B
Emma B

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] add a list of acceptance criteria here
- [ ] ...

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**
Workflows available: https://ssg-confluence.internal.sanger.ac.uk/x/u4meBg

**Comment by JamesGlover** [comment]
Checked with @andrewsparkes and @KatyTaylor and sounds like the required behaviour maps up to the existing. So we get this for free.

**Comment by JamesGlover** [comment]
Moved to in progress to avoid confusion, will stick it back in Todo is new requirements crop up.

**Comment by JamesGlover** [comment]
Not quite as free as I hoped, but pretty cheap.

The current tag-plate validation was tripping up on the second plate, and tried to enforce UDI plates. However, fortunately the plate was still identified as not a 'cross-plate' pool (Which as far as we're concerned, it isn't, as the samples *will* have the same tags). Just updated UDI enforcement to only active if the submission has an existing tag plate associated with it AND actually needs UDIs.
