### ISSUE TITLE
GPL-664 BUG - Heron tailed 384 - Scanning source plates submits form

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#500]
**Describe the bug**
When creating 'LTHR-384 Lib PCR pool' plate from 'LTHR-384 Lib PCR 1' and 'LTHR-384 Lib PCR 2', if the barcodes are scanned, the page errors.
I assume this is because the scanner adds a 'return' character after the text, and this submits the form. The form should not be submitted manually - the user should scan both barcodes and then manually click 'Merge plates'.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the Heron Tailed Workflow until the 'LTHR-384 Lib PCR 1' and 'LTHR-384 Lib PCR 2' plates are made (use Integration Suite?)
2. Click on button 'Add an empty LTHR-384 Lib PCR pool plate'
3. Scan Source Plate 1
4. See errors: 
- Please scan in all the required source plate barcodes
- Source plates do not have the expected types, check whether the right set of plate types have been made.

**Expected behaviour**
Nothing. Should allow you to scan plate 2 and then hit 'Merge Plates'

**Screenshots**
![image](https://user-images.githubusercontent.com/10407809/94423692-f141e000-0180-11eb-8ea6-bb1015a891f2.png)

**Comment by KatyTaylor** [comment]
Pausing until can talk to James, as having trouble stepping through the pipeline in my local environment.

**Comment by JamesGlover** [comment]
From slack

> **James**  _09:19_
> Ahh, lots of discussion yesterday.
> Tag plate stuff was a code fix, not yet merged to develop, which might be why you were having issues. (There’s also the issue of creating a tag plate size 96, and using that in a 384 well pipeline. The error for that is a little obtuse, and just list the wells that aren’t available. I did look to see if I could improve this, but this size isn’t currently made available on the qcable,  which makes the changes non-trivial)
> Integration suite: I’ve got VPN access restored, and pulled across the directory, so I’ll try and get a PR in for that today.
> Order role: Was actually thinking about that this morning. Andrew’s right about the shared purposes, but Katy’s also right that the HR in LTHR stands for Heron, so definitely scope for improvement. I think there’s also room to have limber only add the order role where it is required.
> The scanning issue: Saw the emails yesterday, it sounds like you might not have got the chance to look into it closely. The scanners are supposed to send a tab at the end of their read, but some send a carriage return. Annoyingly, this submits the form. Somewhere in the depths of helix is a PDF to reconfigure the readers, but I think in a few cases the carriage-return behaviour is actually wanted for other software they use. We’re handling this in a few other places, although in most cases I think we’re triggering a different action, rather than just suppressing the default.
