### ISSUE TITLE
GPL-672 Chromium 10X - Change from 4 tags to single UDIs

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/limber#515]
**Description**
As Stef I would like to know how much development time is required to change the 10X pipelines from using 4 tags per well to single UDI tags.

> 10X have released a new tag set which now included UDIs.
> In this set, instead of the 4 tags present in a single well we now only have a single tag.
> In the 10X pipeline we have that page where we assign the tags. How much work would it be to add another optional tag set? The key difference being that there is now 1 tag per well instead of 4.

> Let’s say we make a complete switch to UDIs for 3’ 5’ and VDJ how many weeks of LIMS time should I schedule for this?

**Who the primary contacts are for this work**
Stefanie L (R&D)

**Knowledge or Stake holders**
Ian J

**Additional context or information**
Uses Limber custom tagging screen and passes tag choices through to Sequencescape so probably work required on both sides. Also NPG to consider for analysis?

**Comment by andrewsparkes** [comment]
From James 1st Oct:

> I don’t think it’s too tricky. As I see it we have three options:
> Add in a new tag plate purpose that uses the normal creator and allows the UDI options
> Expose the tags_per_well configuration option in the interface. (Flexible, but error prone)
> Have tags per well be a property of the tag group. Either in the limber config, or in Sequencescape and pass it across the API.
> 11:42
> Option 1 and 2 are pretty easy, but possibly error prone, especially as we don’t filter the tag_groups list as best I can tell.
> 11:42
> Option 3 is a little more work, especially if we put it in Sequencescape, but probably manageable

Have asked Stef to confer with NPG over 10X pipeline analysis in case changes are required on that side. Possible their analysis pipeline is built to expect the 4 tags and may require changes or us to use a different library type.

**Comment by JamesGlover** [comment]
If we have a complete switch-over to the new UDI set, without needing both in parallel, that lets us just update the existing purpose in the purpose .yml file. (Essentially a variation of option 2)

It will still be possible to retrospectively work out (within the lims itself) which tag set / number of tags were used, so there isn't any information 'lost' by recycling the plate purpose.

**Comment by andrewsparkes** [comment]
Tested changing the purposes in the yml, works. 5 prime GEX (LBC 5p GEX LigXP), TCR (LBC TCR Post Lig 1XSPRI) and BCR (LBC BCR Post Lig 1XSPRI) pipelines. Integration suite test changed to use a 96-tag set rather than 384. Re-generate limber config. No other changes required.
Clarifying with Stef whether she wants all 3 of the 5 prime pipelines changed, and also if she wants the 3 prime pipelines v2 and v3 changed as well. And if it's a straight switchover we need or both 1 and 4 tags possible.

**Comment by andrewsparkes** [comment]
Confirmation from Stef:
Awaiting SeqCom for go ahead on this change to UDIs, as multiple faculty groups use it.
Change will be to 5 prime VDJ GEX, TCR and BCR pipelines, and to the 3 prime v3 pipeline (v2 version unchanged).
There will also be a further story to change some file content details for liquid handler CSVs in these pipelines. Stef will confirm later this week what they are assuming SeqCom give approval to go ahead. These changes should also be minor config changes.

**Comment by andrewsparkes** [comment]
Go ahead confirmed.
Stef to document additional requirements Tuesday 27th. Easiest to do it all together.
