### ISSUE TITLE
GPL-679 PWGS 96 to 384

### ISSUE THREAD

**Issue by rl15** [sanger/limber#518]
**User story**
GPL-679 | As a member of R&D (Lesley S & Benn F) I would like to translate the current WGS PCR pipeline from a 96 well format into a higher density 384 well plate format to support pathogen WGS.

**Who are the primary contacts for this story**
Lesley S &
Benn F

**Acceptance criteria**

see https://ssg-confluence.internal.sanger.ac.uk/x/W4meBg
for plate purposes and robot bed verification steps, and process flow.

Tasks:
- [x] Integration Suite - create pipeline test
- [x] Limber - pipeline config
- [x] Limber - plate purposes config
- [x] Limber - robot bed verifications
- [x] Sequencescape - create new purposes, request types, submission templates (limber.rake task)

**Additional Information**
The two most complex pipeline steps are split out into https://github.com/sanger/sequencescape/issues/2934 and https://github.com/sanger/sequencescape/issues/2935

**Comment by Chris-Friend** [comment]
I've updated Katy's branch with a couple of minor changes, and with a first implementation of the missing pWGS steps' purposes

**Comment by Chris-Friend** [comment]
Changes to sequencescape's `limber.rake` to add a new submission templates for the pWGS-384 pipeline https://github.com/sanger/sequencescape/compare/GPL-679-pWGS-sequencing-template?expand=1

**Comment by Chris-Friend** [comment]
Updates following discussion with Lesley and Ben:
* Tag set spelling should be 'TS_sc384'
* Library type should be 'Standard'
* Allowed submission templates are: 'HiSeq X Paired end sequencing', 'NovaSeq 6000 paired end sequencing', 'MiSeq sequencing'
* Creation of pWGS-384 Post Shear XP from 4 LB Post Shear plates uses Quad stamp
* From pWGS-384 Lib PCR to tubes, there is the possibility of pooling all 384 samples into 1 tube, or pooling into 4 tubes of 96 samples by submission (see GPL-681)

**Comment by emrojo** [comment]
Also related with Sequencescape changes in draft https://github.com/sanger/sequencescape/tree/GPL-679-pWGS-sequencing-template
