### ISSUE TITLE
GPL-680 condense 4 x 96 LB Post shear plates into 1 x 384 pWGS-384 Post Shear XP plate.

### ISSUE THREAD

**Issue by rl15** [sanger/limber#519]
**User story**
GPL-680 | As a member of R&D (Lesley S & Benn F) we would like to condense 4 x 96 LB Post Shear plates into 1 x 384 pWGS-384 Post Shear XP plate.

**Who are the primary contacts for this story**
Lesley S & 
Benn F

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] When on a LB Post Shear plate in the new pWGS-384 pipeline, when I click on the button to create the next plate (pWGS-384 Post Shear XP), I should be taken to a screen where I can scan 4 plate barcodes
- [x] Those 4 LB Post Shear plates are condensed into one pWGS-384 Post Shear XP plate
- [x] Should there be any validation around which types of input plates it accepts? (In case relevant - these plates would probably all have different submissions, due to the pooling behaviour required. See https://github.com/sanger/sequencescape/issues/2935)

**Dependencies**
This story is blocked by the following dependencies:
- https://github.com/sanger/limber/issues/518

**Comment by Chris-Friend** [comment]
First two acceptance criteria met by changes in branch https://github.com/sanger/sequencescape/compare/GPL-679-pWGS-sequencing-template?expand=1

**Comment by Chris-Friend** [comment]
Validation should be the same as the pcr_free pipeline, i.e. that a labware exists with input barcode(s), and validation of plate propose in the following robot step
