### ISSUE TITLE
GPL-681 Split 1 x pWGS-384 Lib PCR plate back into 96 plex  pools

### ISSUE THREAD

**Issue by rl15** [sanger/limber#520]
See comments - I don't think any actual extra work will be needed for this, but leaving this story here to make sure we test it properly, and do the correct thing with submissions in the Integration Suite test.

**User story**
GPL-681 | As a member of R&D I would like the ability to Split 1 x pWGS-384 Lib PCR plate back into 96 plex pools for the step pWGS-384 Lib PCR → pWGS-384 Lib Pool XP

I know we designed this for the single cell 384 line, (however we) can’t recall if this behaviour was dictated in the LIMS or part of the SSR submission.

**Who are the primary contacts for this story**
Lesley S &
Ben F

**Acceptance criteria**
- [x] When on the 'pWGS-384 Lib PCR' plate page in the new pWGS-384 pipeline, when I click on the button to create a 'pWGS-384 Lib Pool XP' tube, the right number of child tubes are created, with pooling based on the submission the wells were in.

**Dependencies**
This story is blocked by the following dependencies:
- https://github.com/sanger/limber/issues/518

**Comment by Chris-Friend** [comment]
Allow pooling by submission, i.e. allowing pooling into 4 tubes if four input submissions, or a single tube if four input plates part of a single submission
Linked to PR https://github.com/sanger/limber/pull/527.
