### ISSUE TITLE
GPL-721 As a user I would like to be able to Quad stamp in Limber

### ISSUE THREAD

**Issue by stevieing** [sanger/limber#562]
**User story**
Currently quad stamping to a 384 well plate is done in Sequencescape. This is inefficient as for part of the new Beckman integration users will no longer need to use Sequencescape for anything else?? so it would be better to have this in Limber as it will flow better and save time. Therefore we should add the ability to quad stamp to limber.

**Who are the primary contacts for this story**
e.g. John S (don't include surnames in public repos)

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] add a list of acceptance criteria here
- [ ] ...

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by JamesGlover** [comment]
See: https://github.com/sanger/limber/issues/560
