### ISSUE TITLE
GPL-768 Prevent Users selecting same panel when tagging (96 Well) [Heron]

### ISSUE THREAD

**Issue by JamesGlover** [sanger/limber#569]
This story was split from https://github.com/sanger/limber/issues/546 to handle the 96 well plate requirement.

**User story**
As Lesley I want to restrict tag-plate selection in the Heron Tailed workflow (Sanger_tailed_artic_v1_nnn) to ensure that the same primer panel is not picked for each fork.

- Primer panels now included in tag plates, so applied at same time
- Need to ensure that PCR1 and PCR2 plates each use a different panel.
- Tag plate become Lib PCR1 and Lib PCR 2 ad in place currently

Suggested approach:
- Two different tag layout templates, with same tag group. Suffix primer panel name. (There is a rake task in SS for handling this: lib/tasks/generate_primer_panel_templates.rake))
- Adjust approved layout templates to be confined to corresponding template
- Remove old templates from approved list

**Edit** While this works for the 384 well pipeline, the approach is not suitable for the 96 well version. Lesley S has indicated that prioritisation of the 384 well version is good for the time being, so this has been completed using the approach above.

**96 well version**
- Current flag to ensure identical tag templates should be switched to ensure identical tag groups instead
- The existing templates should be switched out for the primer-panel variants.
- There's a rake task in Sequencescape to generate these variants (lib/tasks/generate_primer_panel_templates.rake)
- Current flag to ensure identical tag templates should be switched to ensure identical tag groups instead

Note: Complete switch over to new process is acceptable and desirable

**Who are the primary contacts for this story**
Lesley S
Naomi P

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] 384 well pipeline (Done in https://github.com/sanger/limber/issues/546)
- [ ] 96 well pipeline

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by SujitDey2022** [comment]
![image](https://github.com/sanger/limber/assets/115623404/eab8e7e9-1fc6-4db0-bddf-a661faa6b07b)
