### ISSUE TITLE
GPL-816 Modify LTHR-384 pipeline to pool into 1 tube

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#602]
**User story**
As R&D I would like the Heron LTHR-384 pipeline to multiplex all 384 samples into just one tube at the end of the workflow. 

Currently, if you start with 4 LTHR Cherrypick plates, and go down the 'LTHR 384 Novaseq' workflow, it creates one submission for each of the 4 plates and therefore ends up pooling the samples into 4 different tubes.

**Who are the primary contacts for this story**
Ben F, Scott T, (James G - did original story)

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] When entering the LTHR-384 pipeline in Limber with 4 LTHR Cherrypick plates, I should end up with 1 multiplexed tube at the end with all the samples pooled in it (rather than 4).
- [ ] Update the Integration Suite test.

**Additional context**
I assume this should be done by creating 1 submission for all 4 plates, rather than 4 separate ones.
However, it could be done by changing the pooling behaviour at the end of the pipeline.

**Comment by JamesGlover** [comment]
End of the pipeline might actually be easier, both for us, and the user. Although we'd need to remove the sequencing request from. the initial submission and generate it on the final tube instead.

**Comment by JamesGlover** [comment]
Yep, thinking about this, I think this could be just config only if we don't try and change the submission to include all 4 plates.

**Comment by JamesGlover** [comment]
Ahh, noticed they still want to be able to support the separate pooling, in which case changing the submisison is the right way to go. 
- This will also require changing quad plate creation to validate that we have all plates of the submission in the quad
OR
- Changing quad plate creation to find all plates automatically
