### ISSUE TITLE
GPL-818 TOKEN: As rep for R&D and CASM (Stef L) I would like a targeted duplex-seq pipeline 

### ISSUE THREAD

**Issue by rl15** [sanger/limber#603]
**Description**
Epic: As rep for R&D and CASM (Stef L) I would like a targeted duplex-seq pipeline to enable TBD 

This is a token for a conversation to have

Key points

**Who the primary contacts are for this work**
Stef (R&D)

**Key points**

- seqcom proposal for CASM request a targeted duplex-seq pipeline. 
- means joining 2 existing pipelines
- existing duplex-seq pipeline & hybridization pipeline (currently used for ISC libraries)
- change to existing duplex-seq pipeline
- change: number of plate labels
- Join to hybridization pipeline

Stef estimate by analogy  4 weeks

(Stef, Monday, 18 January 2021 at 15:30)

**Knowledge or Stake holders**
TBD

**Additional context or information**
Stef L (Monday, 18 January 2021 at 15:30), Subject: Targeted Duplex-Seq pipeline proposal,email to Rich L

**Comment by Skrich1999** [comment]
Emailed Stef to find out if still needed?

**Comment by SujitDey2022** [comment]
![image](https://github.com/sanger/limber/assets/115623404/008226ef-e841-4180-a3ed-e54de08b06ea)
