### ISSUE TITLE
GPL-823 Show help text when a plate is cancelled

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#606]
**User story**
As a Limber user, I would like to have some help text on the page when a plate is cancelled, to help me understand why.

**Who are the primary contacts for this story**
Katy, James G

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] When on a page where the UI shows that the plate is cancelled, due to the associated transfer request and submission being cancelled, some help text shows that says something like "This plate has been cancelled, along with the associated submission. If you think it's been replaced by a new submission, try going back to the stock plate (link) to start again on this pipeline."

**Dependencies**
This story is blocked by the following dependencies:
- https://github.com/sanger/sequencescape/issues/3019 

**Additional context**
See related (blocking) SS story in dependencies for background.

The screen we're talking about will look something like this currently:
![Screenshot 2021-01-19 at 16 21 26](https://user-images.githubusercontent.com/10407809/105065500-d4a21e80-5a75-11eb-9266-4f04929e9e10.png)

**Comment by JamesGlover** [comment]
Validators on presenters already hook into the warning / message system, so would be the ideal way of handling this.
