### ISSUE TITLE
BUG - Timeouts in GBS pool tube creation

### ISSUE THREAD

**Issue by JamesGlover** [sanger/limber#634]
**Describe the bug**
GBS MiSeq Pool tube creation was returning a 404 after 60s, due to the tube search taking too long to return. I've temporarily increased the timeouts in nginx to relieve the problem. But should do the following:

1) Add a 503 error template to avoid the confusion of a 404
2) Update to use the V2 tube endpoint to improve performance
3) Consider further improvements (such as asynchonous calls)

**RT Ticket Number**
#712129

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page '...'
2. Click on button '...'
3. See error

**Expected behaviour**
What was expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

**Comment by KatyTaylor** [comment]
I deployed these code changes - https://github.com/sanger/limber/pull/635. Have moved this issue back to the column it was in before though as I think it might still have some work in progress. (James's comment on PR says "Actual code changes to address the performance issues to follow.")
