### ISSUE TITLE
GPL-899 Redo tagging step in Heron pipeline

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#647]
**User story**
As a Heron pipeline user who has made a mistake on or after the tag addition step, I want to be able to repeat from a plate before that step, so that I don't have to go back all the way to the beginning of library prep.

**Who are the primary contacts for this story**
Sara, Tasha

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Tagging step (creating LTHR-384 Lib PCR 1 & 2) can be repeated in the Heron pipeline in Limber
- [ ] As much tag plate validation as possible is still carried out - tag plate should not be used twice, correct types of tag plates should be used, etc.
- [ ] Investigate if this can also be done for the 96 well pipeline, to keep it consistent
- [ ] Does not have to work across all pipelines

**Comment by JamesGlover** [comment]
Ahh, so in this case the tag clash detection is enabled, because the submission is starting on the 96 well plates, so it is registering as a cross-plate submission, despite being consolidated by this point. As a result the current issue only affects the Beckman workflow.

**Comment by JamesGlover** [comment]
Hmm, just remembering https://github.com/sanger/limber/issues/540
Will remove tag2 tube support alongside this story, especially if it makes things easier.

**Comment by JamesGlover** [comment]
96 well pipeline has never been used, so definitely low priority

**Comment by JamesGlover** [comment]
So for 96:
1) If plexed at 96, you should get it for free
2) If plexed at higher levels, we need to enforce unique tags. So adding this functionality would be significant work.

**Comment by JamesGlover** [comment]
Huh, 96 well version has a 'enforce_same_template_within_pool' flag set... so I'm guessing we aren't pooling at 384 and this should be okay.

**Comment by JamesGlover** [comment]
So, multiple possibilities:
1) Quick and dirty: New config option to disable for Heron 384
2) Better: Only flag as a cross plate submission if we haven't combined source plates

This will fix heron by virtue of disabling tag clash detection

3) Robust: Exclude templates associated with the requests on this particular plate.

This latter option is likely slower, and definitely more work. However we do have some work associated with the bespoke pipeline, that will perhaps be of use here. Going to have a check.

**Comment by JamesGlover** [comment]
And will pick up #540 as well, not sure if it will make it easier per-se, but will reduce the number of moving parts I need to consider.

**Comment by JamesGlover** [comment]
I *think* option 2 is a goer, but need to double check the full scope of the GBS pipeline.

**Comment by JamesGlover** [comment]
So GBS isn't a problem, but option 2 will fail to enforce unique tag sets if we pool different request types. This is currently unpermitted, but this is a bug, with story in place to fix.

The main issue is this:
- We need to pull a list of requests out of the submission, and find those that are not associated with this particular plate
- Well need to filter out cancelled and failed stuff, but thats easy enough
- But we also need to filter out request types upstream and downstream of our current request.
- If we just do this via the request type though, we end up filtering out any parallel forks with a different request type
- This isn't just theoretical, this was the intended design of the GnT pipeline. It is temporarily disabled, but they want the functionality restored.

Think I'll need to resort to quick and dirty for the moment. But going to have a little more of a think.

**Comment by JamesGlover** [comment]
Just poking around in case this problem has been solved before. I vaguely recall the technique of pulling requests out of submission that match a given request type

**Comment by JamesGlover** [comment]
Okay, so I think quick and dirty is probably actually quick and safest in this case. We'll explicitly disable the cross-pool detection for Heron (384) only.

**Comment by JamesGlover** [comment]
To reliably do this intelligently we probably need a somewhat different approach, more akin to that seen in the custom tagging pipeline. While we probably could work out a way of building up lists of request 'lineages' and working out which are absent on the plate, it's ultimately a step removed from the actual thing we case about, which is 'will we get a tag clash'. 
It also dramatically complicates tag clash detection with an understanding of the request graph.

Instead it would make more sense to extract a list of all tags associated with the pool, (like we do in custom pooling), but include the request information along side it. We could then filter out tags associated with failed/cancelled requests, those associated with the same requests as the current plate. It might also then make sense to allow cancelling a tag plate to free up those tags for other pools.

Still going with option 1 for now, but wanted to record what was in my brain for prosperity.
