### ISSUE TITLE
GPL-900 Cancel a single plate [Heron]

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#648]
**User story**
As a lab user I would like to be able to cancel a single plate, without any further repercussions (no requests cancelled etc), to signal that it should not be processed further. It should behave consistently regardless of which plate it is. This will be helpful as a visual indicator that this plate should not be processed further, but allow me to go back to an earlier plate in the pipeline and carry on from there under the same submission.

**Who are the primary contacts for this story**
James G, Katy

**Acceptance criteria**
When I cancel a plate in Limber:
- [ ] It cancels the transfer requests into that plate
- [ ] It does not cancel any Requests or Submissions
- [ ] It does not block processing on any plates other than the one I am cancelling
- [ ] There is some signposting in the app telling me what will happen when I cancel the plate

**Comment by JamesGlover** [comment]
I believe most changes for this story will actually be in Sequencescape.

**Comment by KatyTaylor** [comment]
When this issue is done, can we please:
a) cancel plate DN783725O - see ticket https://rt.sanger.ac.uk/Ticket/Display.html?id=714307 
b) update this advice page - https://ssg-confluence.internal.sanger.ac.uk/pages/viewpage.action?pageId=111062752

**Comment by KatyTaylor** [comment]
Further to the above - I'm closing the related RT ticket, so can we please also update Kasia when the above is done.
