### ISSUE TITLE
GPL-921 Add library type: "Haplotagging"

### ISSUE THREAD

**Issue by neilsycamore** [sanger/limber#666]
As R&D (Mike Q) I would like to have a new library type added

Relates to [RT713560](https://rt.sanger.ac.uk/Ticket/Display.html?id=713560)

Contacts mq1, mcj, ec20

Library specs/requirements attached

[RT713560_library_request.docx](https://github.com/sanger/limber/files/6123396/RT713560_library_request.docx)

**Comment by rl15** [comment]
Emma G wrote (Monday, 15 March 2021 at 17:54)

Request is needed for end of April. Assume this is a quick one and we can put on hold for now.

**Comment by JamesGlover** [comment]
> Q. Is there any remaining uncertainty?
> A. As these have unique barcode structure
> 
> I7 6 bases known the 7 Ns
> I5 13 Ns
> They 
> a) can’t be run with anything else and 
> b) may cause confusion as some pipelines can’t copy with Ns BUT we have sequenced these previously and they were okay
> 

I *think* this is okay, but might need a little clarification about exactly how this will work.

**Comment by emrojo** [comment]
Also depends on:
 - https://github.com/sanger/sequencescape/pull/3162
 - https://gitlab.internal.sanger.ac.uk/psd/integration-suite/-/merge_requests/25
