### ISSUE TITLE
GPL-962 Add bed verifications for C-LCM, Duplex Seq, and Targeted NanoSeq

### ISSUE THREAD

**Issue by harrietc52** [sanger/limber#701]
**User story**
As Ops we would like to add bed verifications to various pipelines. 

Story came from research story [GPL-917](https://github.com/sanger/limber/issues/665)

**Who are the primary contacts for this story**
Ben F
Liz E
Harriet 
Andrew

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Add bed verifications as detailed below to Limber config/robots.rb
- [ ] Update integration suite tests where appropriate e.g. for WGS `spec/limber/wgs_pipeline_spec.rb`, and check they run

***Bed verification # 1***
**Robot**: Bravo
**From**: `LB Stock` or `LB Cherrypick `plate (Bed 4) 
**To**: `LB End Prep` (Hotel 1-4).
**Info**: Currently, source plate is Standard Stock (plate from CASM) which optionally goes into LCMB Cherrypick (in CASM Labs) or into LCMB Cherrypick (in our Labs), so either plate (LCMB Stock or LCMB Cherrypick) can be the start point for pipeline. 
Q. Is the support for the source plate being either Stock, or Stock and then Cherrypick, required for the Story 1, or shall this support be added in Story 2? **It’s another ‘nice to have’. Ops can keep working as they are but having a human put labels on top of labels is a potential source of error.** (tell Ben this might not be necessary to re print from a LIMS perspective).
Currently, cannot have an input plate that may can also be midway in pipeline. But both plates do transfer onto Frag. So have both input plates configured. 
**Update from Liz E (27.04.21)** "Story 1: The ability to start from either stock plate or Cherry-Pick would be great and would reduce the possibilities of mix up.  Sticking labels over labels is never a good solution."

***Bed verification # 2***
**Robot**: Bravo
**From:** `LB End Prep` Bed 6.
**To:** `LB End Prep` Bed 5. 
**Info:** They want to scan back onto robot, same position, to check it is in the correct location after the thermocycler. (stamp into). Meaning there is no transfer, but hopefully done in other robots to check how. E.g in robots.rb `bravo-lhr-384-end-prep` is checking the plate is put back with `verify_robot: true`, and the bed verification before that (`bravo-setup-lhr-384-xp-to-lhr-384-end-prep-to-lhr-384-al-lib`) is checking plate `require_robot: true`
"The end prep plate comes from bed 6 not bed 5, but we don’t need to track where it’s come from just need to verify it’s gone on the correct location (bed 5) and there’s been no mixups (make sure the robot scanned matches the robot scanned during bed verification #1" (Ben F)

***Bed verification # 3*** ??
**Robot**: Bravo
**From:** `LB End Prep`
**To:** `LB Lib PCR`
**Info:** Stamp into
Q. What tags are used? **The PCR tag plates that we use are: TS_pWGSA_UDI96v2, TS_pWGSB_UDI96, TS_pWGSC_UDI96, TS_pWGSD_UDI96** (Jamie)
Q. Is bed verification required from “LB End Prep” to “LB Lib PCR”? **No, this stage is the same as the other 96 well library preps so presumably you can copy one on those e.g RNAA.** 

***Bed verification # 4***
**Robot**: Hamiltons (in Post)

Single
**From:** `LB Lib PCR` (Bed 7)
**To:** `LB Lib PCR-XP` (Bed 9)

2-plate run
**From:** `LB Lib PCR` (Bed 7) **To:** `LB Lib PCR-XP` (Bed 9)
**From:** `LB Lib PCR` (Bed 12) **To:** `LB Lib PCR-XP` (Bed 14)

**Comment by harrietc52** [comment]
[LCMB Pipeline](https://github.com/sanger/limber/files/6310475/PMAP_0052_LCM_WGS_v0.1.pdf)

**Comment by andrewsparkes** [comment]
We don't seem to have an 'LB Stock' purpose in the Limber configs. 'LB Cherrypick' is the start of the current WGS pipeline and Ben said they just print the LB Cherrypick label and stick it over the label of the stock plate that they get from CASM. I think we can easily add an optional 'LB Stock' purpose prior to, or as an alternative to, the 'LB Cherrypick' purpose, but I may be wrong. Not hard to test by changing the Limber configs.

'LB End Prep' is the current name for the step after 'LB Cherrypick' for LCMB, it skips the LB Shear and LB Post Shear steps.
In your above notes, anywhere you name a purpose 'LCMB LB xxx', the name is currently 'LB xxx'. When we do the new pipeline we'd probably use 'LCMB' prefixes instead of 'LB', not have both.

There's a task missing:
Update the Integration suite to test the bed verifications.

Q. can we restrict the bed verifications to just the LCMB request type?

**Comment by harrietc52** [comment]
Q. Check LB Cherrypick or LB CPick
Q. can we restrict the bed verifications to just the LCMB request type?
Q. When we do the new pipeline we'd probably use 'LCMB' prefixes instead of 'LB', not have both. (Do they want LCMB LB or LCMB)
Q. Will source cherrypick and stock plates be LCMB or LB
Q. Is the submission made on the cherrypick plate, a library and sequencing request? ie Sequencing is done at the end in custom pooling.

**Comment by harrietc52** [comment]
**Integration Suite**

Add integration suite task for LCMB WGS pipeline, as it is at the moment

Similar to wgs_pipeline_spec.rb
with modifications to match how it is
remove shears
add new robot verfication from above
change ending so using custom pooling instead of multiplex (duplex seq pipeline does customer pooling so we can check)

**Comment by ElizabethEasthope** [comment]
Hi,  Would it be possible to pick this story back up.  The line is quite complex and we have had an issue where the plate was return to the deck in the wrong location resulting in a robot brake.  The engineer had to be called and the automation was out of action for a few days while it waited repair.
Is there chance to get this back on the priority list?
Thanks Liz

**Comment by andrewsparkes** [comment]
For Bed verification 2:

We already have these defined:
```
custom_robot(
      'bravo-lb-end-prep',
      name: 'bravo LB End Prep',
      verify_robot: true,
      beds: {
        bed(7).barcode => {
          purpose: 'LB End Prep',
          states: ['started'],
          label: 'Bed 7',
          target_state: 'passed'
        }
      }
    )

    bravo_robot do
      from 'LB End Prep', bed(7)
      to 'LB Lib PCR', bed(6)
    end
```
So is this ok? The story is talking about beds 5 and 6, not 7.

**Comment by andrewsparkes** [comment]
For bed verification 3:
This one is already in place for LB.

For bed verification 4:
You do not need to define two distinct bed verifications, for single and double versions. Just the double is enough. Bed verification code allows for just running one pair then.

**Comment by andrewsparkes** [comment]
When the LCMB is split off with its own plate purposes, these bed verifications will all need to be copied and the LCMB plate purposes used in the copies.

**Comment by andrewsparkes** [comment]
It might make sense to do this story and [GPL-963 Make LCMB own pipeline #702](https://github.com/sanger/limber/issues/702) at the same time, with a new LCMB integration suite test in Gitlab (see WGS one at spec/limber/wgs_pipeline_spec.rb in the Integration Suite repo).

**Comment by andrewsparkes** [comment]
Take care when adding bed verifications for Plate purposes starting 'LB'. The LB plate purposes are shared amongst multiple pipelines, and it may not be appropriate for the bed verification to be present for all usages of those purposes. Better when the purposes have distinct prefixes for specific pipelines so no overlaps.

**Comment by SujitDey2022** [comment]
Need to split the user-story into 3, each for the corresponding bed verification pipeline. The content of the story/acceptance criteria is legacy and needs to be reviewed and refined to meet the current requirements.

**Comment by SujitDey2022** [comment]
Discussed this with Sara W. and it was identified that there is a need to further refine and possibly split the user story. Awaiting further response from Short Read.
