### ISSUE TITLE
GPL-963 Make LCMB own pipeline for bed verification purposes

### ISSUE THREAD

**Issue by harrietc52** [sanger/limber#702]
**User story**
As Liz E I would like to move LCMB into its own distinct pipeline, with additional bed verification steps.

See also research story [GPL-917](https://github.com/sanger/limber/issues/665)

**Who are the primary contacts for this story**
Liz E
Ben F
Harriet C
Andrew S

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Lab to be able to run LCMB pipeline distinct from WGS and other existing pipelines
- [x] NPG contacted to discuss creation of LCMB specific library type to use the 'standard' analysis route
- [x] New Integration suite test for LCMB pipeline to run cleanly

**Pipeline Tasks**
Story includes the following pipeline tasks:

In Sequencescape:
- [x] Create plate and tube purposes for LCMB, details below
- [x] Check limber_lcmb request type definition and plate purposes it is linked to, likely need updating to LCMB versions. Move it to record loader if not already there. N.B. As the request type exists already this may involve rails console updates for the various environments - note down clearly what needs to be done when deploying to UAT/Training/Prod.
- [x] Check if we need a new submission template for the Library prep. Should already exist for limber_lcmb. Move to record loader if not already present.

In Limber:
- [x] Create a new pipeline config file for the pipeline, see details from Liz E below
- [x] Create new purposes config file for the LCMB plate and tube purposes (purposes filename: lcmb.yml)
- [x] Remove `limber_lcmb` request type from high_throughout_wgs pipeline config (could keep this until switch over is complete, and then library type would determine which pipeline during switch over for flexibility? would need LCMB library type for this)

In Integration Suite (Gitlab):
- [x] Check and update WGS pipeline to remove LCMB references (if needed)
- [x] Create new LCMB version of the WGS test with the LCMB purposes and submission details, plus any step changes that diverge it from WGS.
- [x] Add placeholders for checking bed verifications (see story https://github.com/sanger/limber/issues/1327)
- [x] Add placeholder for checking the file download (see story https://github.com/sanger/limber/issues/1329)
- [x] Test against SS and Limber

**Additional context**
***Pipeline details:***
From Liz E on 31st May
(NB. check standard naming conventions e.g. Camel Case, and align these plate purposes with existing WGS LB ones so we can create the purposes configs correctly - ensure no surprises like new labware creators are required).

LCMB pipeline config:
LCMB: # top of the pipeline
Pipeline_group: LCMB
Request_type: limber_lcmb (exists already)
Library type: standard [agreed to make LCMB library type]
Library pass: LCMB Lib PCR-XP
Relationships:
LCMB Cherrypick : LCMB End Prep
LCMB End Prep : LCB Lib PCR
LCMB Lib PCR : LCMB Lib PCR-XP
 
LCMB MX : bottom of pipeline (pooling and norm)
Pipeline group : LCMB
Filters:
Request type_key: limber_lcmb
Relationship:
LCMB Lib PCR-XP : LCMB Lib Pool
LCMB Lib Pool : LCMB Lib Pool Norm

***Purpose configs***
LCMB Labware purposes:
- LCMB Cherrypick
- LCMB End Prep
- LCMB Lib PCR
- LCMB Lib PCR-XP
- LCMB Custom Pool
- LCMB Custom Pool Norm

***After deploying***
Because the limber_lcmb request type already exists and has been connected to WGS-related library types and plate purposes, we need to fix these via the rails console.
In rails console delete incorrect request_type acceptable purposes and library_types:
`$ rt = RequestType.find_by(name: 'Limber LCMB')`
list plate purposes:
`$ rt.acceptable_purposes`
includes LB Cherrypick which we don't need. Remove it.
`$ pp = PlatePurpose.find_by(name: 'LB Cherrypick')`
`$ rt.acceptable_purposes.delete(pp)`

list library types:
`$ rt.library_types`
includes 'Standard' and 'Chromium single cell CNV' which we don't need. Remove them.
`$ lt_standard = LibraryType.find_by(name: 'Standard')`
`$ lt_chromium = LibraryType.find_by(name: 'Chromium single cell CNV')`
`$ rt.library_types.delete(lt_standard)`
`$ rt.library_types.delete(lt_chromium)`

**Comment by harrietc52** [comment]
[LCMB Pipeline](https://github.com/sanger/limber/files/6310481/PMAP_0052_LCM_WGS_v0.1.pdf)

**Comment by andrewsparkes** [comment]
library pass will be at the LCMB Lib PCR-XP plate

The plate purposes are easy to create, it's just config and then you run the config:generate rake task in Limber. The asset types and presenter and creator classes should be just already existing ones, the idea is they get re-used. No significant new behaviour was required.

Missing requirement?
Ben wanted a new concentration csv file to be downloadable at the PCR-XP stage. See exports_controller for how these are done.

**Comment by harrietc52** [comment]
Update:
Q. Check if changing LB End Prep -> LCMB Frag ER
Q. Check if they wan LCMB or LCMB LB, and if it fits on the labels

**Comment by andrewsparkes** [comment]
Questions answered in meeting with Liz E and Sujit on 30th June. Description in story updated to reflect latest understanding.

**Comment by SujitDey2022** [comment]
@andrewsparkes This story was further split into #1327 and #1329

**Comment by andrewsparkes** [comment]
Requested LCMB library type via Steven L in NPG on 17th July 2023
