### ISSUE TITLE
GPL-964 Clean up unused bed verifications

### ISSUE THREAD

**Issue by harrietc52** [sanger/limber#703]
**User story**
As a developer I would like to clean up any unused bed verification for plate purposes that are no longer used

Story came from research story [GPL-917](https://github.com/sanger/limber/issues/665)

**Who are the primary contacts for this story**
Harriet
Andrew
Ben F
Liz E

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] remove any bed verifications that are not currently in use, becuase the plate purposes in the bed verifications dont exist in any pipelines. Dont remove the unused plate purposes as they still need to exist. For example, most of the LHR have now been renames to LTHR and can be removed.

**Comment by andrewsparkes** [comment]
For Limber pipelines:
Limber bed verifications can be found in the config/robots.rb file. Check all the plate purposes in that file also exist in the config/pipelines files.

NB. Some pipelines and their bed verifications are still only in Sequencescape. This story is limited to cleaning up only the Limber code.

**Comment by andrewsparkes** [comment]
Not clear to me how we know what the list of unused plate purposes is for this story. Who decides which plate purposes and bed verifications are no longer needed, and how do they make that determination?
