### ISSUE TITLE
GPL-965 Add positive control to source plate in LCMB pipeline (BP-Medium)

### ISSUE THREAD

**Issue by harrietc52** [sanger/limber#704]
**User story**
As a user I would like to be able to add positive controls to the source plate in the LCMB pipeline, for PCR-XP stage to verify prep has worked (will have a concentration)

Story came from research story [GPL-917](https://github.com/sanger/limber/issues/665)

**Who are the primary contacts for this story**
Harriet
Andrew
Ben F
Liz E

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] the source plate can either be a LCMB Stock or LCMB Cherrypick
- [ ] user can click an empty well and add a posisitive control, scanning a batch barcode number 
- [ ] the control record will be created in SS
- [ ] well will then show '+'

**Additional context**

Q: Positive controls  will not get sequenced. - how to prevent this control from being sequenced?

**Comment by JamesGlover** [comment]
Does the control addition in the existing Cherrypick pipeline work here? Adding new control plates (And thus a different control. sample) is easy. (Which Wells are left free of controls is currently a global setting)

**Comment by andrewsparkes** [comment]
Ben specifically said that not all plates have empty wells, and if they do it may not be the same wells. Adding the control is an optional thing. He did say CASM tend to fill the plates column by column (if I remember correctly) so the first empty well in the sequence could be the default one to set?
Not familiar with control addition in cherrypick, is that an extra Limber 'step' in the pipeline?

**Comment by SujitDey2022** [comment]
Hi @harrietc52 can you help direct me to the point of contact for this user-story. Need to check if this requirement is still relevant.

**Comment by SujitDey2022** [comment]
Discussed this with Liz. E. and the story can be closed
