### ISSUE TITLE
GPL-999 | Process map & estimate for Cardinal scRNA pipeline to co-ordinate 5k pilot [ToR-047]

### ISSUE THREAD

**Issue by rl15** [sanger/limber#716]
**Description**
GPL-999 | As Project Manager for Cardinal (Nicole S) I would like estimate of effort to deliver first release of Cardinal scRNA pipeline to co-ordinate 5k pilot

**Who the primary contacts are for this work**
Nicole S (Project Manager)
Stef L (R&D)
Stephen W (Wet lab scientist)
Nicole S  (PI)

**Additional context or information**
Stef L will produce OG process map with Stephen W
LIMS generate backlog items and estimate (Potentiality in w/c 17th May)

**Comment by rl15** [comment]
Stef L wrote (Tuesday, 1 June 2021 at 10:39);

Please find attached the LIMS overview and associated process maps that we discussed on Friday. 

[20210601_Cardinal_process_maps.zip](https://github.com/sanger/limber/files/6609159/20210601_Cardinal_process_maps.zip)

NB This is a possible pilot OKR: Enable UK Biobank transcriptomics research through new cardinal pipeline enabling tracking and reporting of sample cohort progression of x samples in October 2021 rising to x by x

**Comment by rl15** [comment]
Rich L wrote to Steff (Friday, 28 May 2021 at 17:24)

Things that are different with Cardinal we should be aware of
 
Reception of material: This needs to be a high throughput reception.
 
Receive samples on site & know they are here: I believe this is covered by LabWhere – all reception activities are broadcast to the events warehouse (already stress tested by Heron +30M samples)

_NB From subsequent meeting on 7th June Bioresourse Management Service (BMS) will be used for Banking of material but not receipt (Stephen W)_ 

Start processing: Of these upto 96 tubes selected per day and scanned in to create a plate. We need to establish if this is supported already
+ capture the samples ‘site’ (see below)
 
Pooling: Want automated business rules around pooling
 
a)       If its 96 will be 8 pools of 12
b)      If its not 96 set of rules to try to balance the samples per pool
 
And ideally
 
c)       + A pool to contain 2 samples per site (A site is a physical location)
d)      + logic around volumes per pool based on cells per sample. (Have assumed this is measured as part of processing in quant hub. Can confirm quant hub does broadcast to MWLH (via SS)

**Comment by rl15** [comment]
Overview forwarded  on 8th June to Rich L (Note is a further document forwarded that can send on individuals who pick up the pipeline to backlog item conversion, which I can forward on if requested)

[Cardinal Pilot high level overview.pptx.zip](https://github.com/sanger/limber/files/6615409/Cardinal.Pilot.high.level.overview.pptx.zip)

**Comment by rl15** [comment]
Hum Gen would like estimate w/c 20th June.

**Comment by rl15** [comment]
>Stef L wrote (Friday, 11 June 2021 at 14:03)

> I met with team Cardinal and Sameena today and have discussed sample receipt and banking.
> Sample receipt will occur in Sameena’s team whilst sample banking will be part of the Cardinal LIMS pipeline.
>We need to gather a little more information but I will send an updated LIMS outline next week. Only the sample receipt and 
> banking steps will be amended – all other aspects will remain as they currently are.

**Comment by rl15** [comment]
Mail between Stefanie L

Thursday, 7 January 2021 at 11:28 - Subject: Cardinal Cell counter export - Possibly Quanthub

**Comment by KatyTaylor** [comment]
Closing this as was delivered ages ago.
