### ISSUE TITLE
DPL-017 Hamilton bed verification Heron 96 & 384 pipeline pooling and XP clean up step [m] [Heron]

### ISSUE THREAD

**Issue by rl15** [sanger/limber#732]
**User story**
DPL-017 | As R&D specialist (Iraad B) I would like Hamilton bed verification on the Heron covid pooling and XP clean up step on the 96 & 384 well process to ameliorate plate swaps with 6 plates per deck (currently reduced to 2 as temporary measure)

**Who are the primary contacts for this story**
Iraad B (R&D)
James G

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] add bed verification to Heron pipeline Heron COVID 384w pooling and cleanup step
- [x] modify limber bed verification to allow bed verifications from plates into tubes

**Identified uncertainty**
Beds: 6 plates to 6 tubes
Sources in beds 16-21, destinations in beds 22-27
96w pooling from all four quadrants of 384w plates won’t be possible anymore (i.e. splitting back out into multiple tubes at multiplex pooling stage). The protocol for running 1x quadrant of 96 samples will still be available to use if sample numbers drop. This will be more expensive, but we would be able to run up to 6 x 384 well plates at a time.

**Assumptions**
Change used across all uses of pipeline (regardless of building location).
Additional Hamilton tube holders made available (done).
Bed barcodes for each tube holder (Iraad has done this).

Restriction of quad-stamping to a single submission is to be looked at in a separate issue.

**Additional context**
https://drive.google.com/file/d/1CsV2Z7wbGhahre1NecigguHuW4JHCfwI/view (TOR 43)
https://drive.google.com/file/d/1WvTgOoi5XdW53ztaOFSkfuE1qyTFWxZh/view?usp=sharing

**Comment by rl15** [comment]
>Iraad B wrote (Thursday, 13 May 2021 at 11:20)

>We had a R&D OPS meeting about the LIMS and pipeline changes necessary for this process and I understand the LIMS changes that will need doing are only limited to the following Heron pipelines.
 
>The Heron COVID 384w pooling and cleanup step; and
>The Heron COVID 1 quadrant (96w) pooling and cleanup step that is part of the 96w process.
 

>This omits the following RISKS signalled by PSD.
>There is RISK operators won’t use the deck validation when presented with manual option too.
>An alternative is duplicating pipelines, which is large piece of work.

**Comment by andrewsparkes** [comment]
Bed numbers for verifications under discussion with Iraad and Scott.
384 pipeline will be up to 6 source plates to 6 destination tubes, 1:1 transfers. Source plates may be in beds 16-21, and destination tubes in beds 22-27.

Issue: Limber bed verification code is built solely around verifying plate to plate transfers, it does not handle tubes. Changing this makes the story larger.

**Comment by JamesGlover** [comment]
Hmm, so three aspects I see here:
1) Updating the plate lookup by barcode to use `Sequencescape::Api::V2::Labware` instead. This will get use 90% of the way there in terms of functionality
2) Update all the strings and variable names to say labware, rather than plate. This will be fiddly and annoying. (Will probably affect the models, views, controllers, and possibly some js)
3) `PlateMetadata` isn't available on tubes at the moment. We don't strictly need this functionality at the moment, so could skip it for tubes, but I don't see any major reasons (other than naming) why the association can't exist on labware.
