### ISSUE TITLE
DPL-063 DEPRECATED - Cardinal - tube barcoding

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#755]
**User story**
As a scientist from Human Genetics, I need the tubes containing fresh blood samples I will be receiving daily from various sites across the UK to be barcoded appropriately.

**Who are the primary contacts for this story**
Stef L

**Acceptance criteria**
- I need to be able to generate a batch of barcodes
- The barcodes should be identifiable as from a particular blood collection site e.g. Newcastle, Stockport, Bristol, Reading, ELGH (e.g. unique prefix).
- Administrators should be able to add new sites, with their barcode formats, into the system, to allow for quick on-boarding of new sites and avoid involving PSD when setting a new one up. (nice to have)
- Each barcode must be unique so that it can be used to identify a particular patient. 
- I must be able to export or copy paste these barcodes so I can easily email them to the relevant site.
- I must be able to print these barcodes (from Squix printers) in case I need to send them physically to the relevant site, where they will be stuck onto blood collection tubes.

**Dependencies**
References
This story has a non-blocking relationship with:
- https://github.com/sanger/limber/issues/812 

**Additional context**

Nicole Staudt (project manager) from Cardinal will be the one informed about new sites (the most common time when new barcodes will need to be generated) - she may then ask an SSR to generate barcodes for them. Or could do it directly if she has access to whatever app is necessary.

**Comment by KatyTaylor** [comment]
Q's:

1. So barcodes need to be something like 'NCL-123456', 'STK-123455' (for Newcastle and Stockport) - they identify the site not the project - they don't have to include 'UKB' as well?
2. Confirm that we don't need to print off the barcodes - we email them to the site?
3. Are the tubes in tube racks or standalone?
4. Will they be manually scanning them in one by one? (Rich's comment mentioned something about high throughput receipt)
5. Not sure if we normally like to do automated emails - possibly think about alternatives.
6. Is there sample metadata provided at all?
7. "a control will be added to the plate" - at what stage would this happen? The rest of this story is talking about tubes, not plates.

**Comment by andrewsparkes** [comment]
Q. Is that BMS system going to use our Labwhere application for the 'assign then into a storage location' requirement? If so will that be a box / rack barcode location containing multiple tube locations? Consider how that will be managed.

**Comment by KatyTaylor** [comment]
> Q. Is that BMS system going to use our Labwhere application for the 'assign then into a storage location' requirement? If so will that be a box / rack barcode location containing multiple tube barcodes? Consider how that will be managed.

As I understood it, there are no fluidx tube racks at this stage, the only relevant barcodes will be these 'vacutainer' tubes.
The fluidx tube racks come in in this story - https://github.com/sanger/limber/issues/773 - for the 'cell banking' - at which stage I presume they are not using LabWhere - sounded like we give them a list of "original tube barcode, new fluidx tube barcode, and new rack barcode" and they take it from there. But it's a good question and something to keep an eye on.

**Comment by KatyTaylor** [comment]
More Q&A with Stef (copy pasted from email):

Q1. What will be the process of on-boarding a new collection site? At the moment I am imagining a user picks from a list of sites to generate barcodes, and dev input would be required to add a site to that list. 
_A1. Sounds good – how annoying would it be to add new sites/ how long would this take? I can imagine that this would need to be acted on quickly i.e can’t be a process of having to submit a story which needs to be prioritised etc._
--> Have added acceptance criteria for this to be configurable.

Q2. What is the starting list of collection sites? (not urgent but will be needed to do the story) 
_A2. Still unclear at this point._

Q3. What barcode label size is needed to go on a ‘vacutainer’ tube? Is it something we’ve already got set up? 
_A3. Don’t worry about this for now – still some uncertainty._

**Comment by KatyTaylor** [comment]
Update: barcodes no longer needed for UKB, but they are needed for Genes & Health

**Comment by KatyTaylor** [comment]
Risk that UKB has barcodes with leading zeros.

Open question - which app to put barcode generation and printing in? Similar to Baracoda / UI? Sequencescape?

**Comment by KatyTaylor** [comment]
Spun this story out - https://github.com/sanger/limber/issues/812 - since it has become clear we do need to import some metadata about samples into Sequencescape.

**Comment by KatyTaylor** [comment]
Deprecated this as we are planning to just use NT barcodes, using manifests - more details to come.

**Comment by KatyTaylor** [comment]
Detail on tube label sizes from Slack, in case needed in future:

the smallest vacutainer sizes we expect to be 2 or 3 ml. I don't know what label sizes are available but I would have thought that a similar size to the ones that are currently used for the COVID tests on site would be suitable for any size of tube (Nicole)

If the site itself doesn't have any requirements then the standard tube label format should be a good option. (Stef)

Tubes are 13 x 75mm for a draw of 2-4ml of blood. (Stephen)

**Comment by KatyTaylor** [comment]
New information from Nicole S (see email "Cardinal barcodes" including Katy, Stef and Stephen W Wednesday, 8 September 2021 at 15:26, onwards):

East London Genes and Health will generate their own barcodes, with a format of “S2-046-XXXXX”, where XXXXX is a number. Therefore all suppliers (them and UKB) are generating their own barcodes, and this story is really obsolete.
