### ISSUE TITLE
DPL-064 Cardinal - sample arraying

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#756]
**User story**
As a member of the Cardinal team, in order to start processing the samples, I need to transfer a portion of the blood from vacutainer tubes to a 96 well plate, and record which samples went into which wells in the LIMS.

The transfer will be a manual process (not robotics) and I want to put measures in place to ensure that discrepancies don't arise between the order in which samples go into the plate in the LIMS vs in reality.

**Who are the primary contacts for this story**
Stef L

**Acceptance criteria**
- User can create a new "LCA Blood Plate" (96 well) in the LIMS.
- User can print off a barcode for the above plate.
- User can populate the above plate with samples, in column order, by scanning in one blood tube after another.
- When user has finished, samples are saved into the plate in the LIMS.
- See mock up here (3rd step) for idea of user interface - https://lucid.app/lucidchart/invitations/accept/inv_466bfafd-b2f5-42a8-ac0f-ed4b54e1904b
- On occasion a control will be added to the plate. This will require its own unique identifier which identifies it as a control.
- User can print off a page showing which tubes were transferred into which well positions, to take into the fume cupboard (see 'additional context')
- User can delete tubes from the screen while part way through arraying, if they made a mistake.

**Dependencies**
Limber pipeline setup - https://github.com/sanger/limber/issues/772

Related: https://github.com/sanger/limber/issues/764 (see [diagram](https://lucid.app/lucidchart/invitations/accept/inv_466bfafd-b2f5-42a8-ac0f-ed4b54e1904b) for how we think they will interact)

**Additional context**
Lab workflow will probably be:
- Gather source tubes and a rack
- Use screen to scan tubes into the plate, while transferring them physically (with closed lids) into the correct positions in the rack
- Take the rack (and the printed out sheet from LIMS if available) to the fume cupboard to do the actual transfer into the plate

**Comment by KatyTaylor** [comment]
Q's:
- What's the reason for this daily sampling?
- Is blood transferred more than once from the same vacutainer?
- Not sure about auto-generation of manifest - if it's just for making the submission more streamlined, there might be a better way to automate that.
- The 'LCA pipeline' - doesn't exist yet, right?

**Comment by andrewsparkes** [comment]
Have some concerns about how this un-bought BMS and un-bought ELN will interface with our systems. That interaction needs some consideration, maybe discuss with whoever is responsible for buying those systems. Ideally barcode of the source (stock) tube could be the key and that is all that we need. But by end of the pipeline after multiple pooling steps could be difficult to make that connection.

**Comment by KatyTaylor** [comment]
> Have some concerns about how this un-bought BMS and un-bought ELN will interface with our systems. That interaction needs some consideration, maybe discuss with whoever is responsible for buying those systems. Ideally barcode of the source (stock) tube could be the key and that is all that we need. But by end of the pipeline after multiple pooling steps could be difficult to make that connection.

Yep so I was wondering if we could actually make the `name` of the samples in Sequencescape the stock tube barcode. That way, we could keep it as an identifier all the way down the pipeline.
Laura will be involved with the new BMS system - I've already had a quick chat with her about it.

**Comment by KatyTaylor** [comment]
Made this diagram of how the UI could look, with a comparison to the Heron pipeline: https://lucid.app/lucidchart/invitations/accept/inv_466bfafd-b2f5-42a8-ac0f-ed4b54e1904b

Meeting with Stef raised a potential requirement, which we are treating as an enhancement for the future: the option to create identical blood and blood bank plates, both at once (in reality they would create one plate with double volume and then stamp half into the other plate).

**Comment by KatyTaylor** [comment]
Write up before holiday:
- I have unmerged code in this branch - https://github.com/sanger/limber/tree/dpl064-sample-arraying 
    - An earlier version of this branch was merged into Andrew's branch
    - Since then, I have:
        - modified Pipeline.rb to cope with pipeline config that doesn't have any filters - for when requests aren't needed
        - added an in progress test for Pipeline.rb

- I have looked into the Ruby labware_creator and Sequencescape side of plate creation today. 
    - the call to targetUrl from the Vue component goes to ```plate_creation_controller#create```, and then to ```multi_stamp#create_labware!```
    - In ```create_labware!``` it does 2 API calls:
        - to create an empty plate, ```api.pooled_plate_creation.create!``` - uses V1 API, creates an ```AssetCreation``` record, which acts as a factory to create the plate
            - I have tested this using tube uuids instead of plate uuids, and it works - so think no changes needed Limber or Sequencescape side here 🥳 
        - to create the transfer requests and aliquots etc., ```api.transfer_request_collection.create!``` - uses V1 API, creates a TransferRequestCollection record, which creates the transfer requests etc. through Rails magic using `accepts_nested_attributes_for :transfer_requests`
            - This should be fine for our purposes because it accepts receptacle uuids, whether they are from a tube or well
            - We need to tweak the API to make sure we have the tube receptacle in Limber (alternative is to pass labware uuid to Transfer Request Collection, but that is only there for backwards compatibility reasons so better to pass receptacle uuid if poss)
            - Tested passing no outer_request to this endpoint - it works as long as the whole outer_request key is missing - don't send nil or anything. I was testing it using a tweaked version of the quad stamp page - tested where the source wells did have requests coming from them, and the endpoint did not pick them up automatically, so it all seems fine - no changes needed SS side, and only change Limber side is to not send outer_request (in `request_hash` in multi_stamp.rb)

**Comment by KatyTaylor** [comment]
Tasks:

Blood Vac page:
- [ ] Blood Vac tube page needs to have a ‘children’ tab

Sample arraying page:
- [ ] Scroll righthand side of screen independently
- [ ] Barcode scanner tab between boxes
- [ ] Refactor to DRY code (javascript components) (TubeScan looks likely)
- [ ] Printing the page (arraying page, or download from next plate page)

Labware creator:
- [ ] Labware creator tests

Submission / Blood Array / Bank page:
- [ ] Submission screen js console error (comments box)
- [ ] Submission error handling
