### ISSUE TITLE
DPL-065 Cardinal - PBMC isolation and cell count input files

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#757]
**User story**
As a user of the Cardinal pipeline, I need the plate containing the isolated PBMCs (peripheral blood mononuclear cells) to be recorded in the LIMS, and be able to generate files for the cell-counting Cellaca machine to use.

**Who are the primary contacts for this story**
Stef L

**Acceptance criteria**
- I can create an "LCA PBMC Plate", as a stamp of the "LCA Blood Plate".
- I can print out the barcode for above plate.
- I can print out barcodes for up to 4 additional QC plates.
    - These can have the same barcode as the LCA PBMC plate but with a suffix of QC1,2,3 or 4
    - Only 1 QC barcode will be needed if there are 24 samples or less, only 2 QC barcodes if there are 25-48 samples, etc
- I can generate Cellaca input files
    - The Cellaca can process 24 samples at a time (see input file layout in Figure 1). 
    - The LIMS needs to populate the sample name into the respective field (instead of the 'A1', 'A2' etc shown). 
    - If more than 24 samples are in the plate, additional file(s) need to be created. 
    - They can be labelled QC 1,2,3 or 4. 
    - The files can be downloaded in Limber.

![image](https://user-images.githubusercontent.com/10407809/124907596-45b39f00-dfe0-11eb-9bf0-4dcf9169c2b5.png)
_Figure 1. LIMS generated Cellaca upload file (.csv in a 8x3 format.)_

**Dependencies**
This story is blocked by the following dependencies:
- pipeline setup - https://github.com/sanger/limber/issues/772
- LCA Blood Plate type from https://github.com/sanger/limber/issues/756 must be available to finish this story.

**Comment by KatyTaylor** [comment]
Q's:
- Limber pipeline - need to have names for submission templates, library types, request types etc.
- Is the Cellaca upload file a csv?
- Is it definitely 'sample names' that are needed, not sanger sample id or any other identifier?

**Comment by andrewsparkes** [comment]
See Limber exports_controller.rb and the file_links in config/purposes files to see how to make the csv file download links.
