### ISSUE TITLE
DPL-069 Cardinal - Chromium connect (S)

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#760]
**User story**
As a user of the Cardinal pipeline, I need to feed my sample pools (on the LCA PBMC Pools Plate) into the chromium connect liquid handler, and record the following plates and indexes that are used.

**Who are the primary contacts for this story**
Stef L

**Acceptance criteria**
- [x]  Following on from the LCA PBMC pools plate, I can generate a new plate: LCA 10X cDNA plate (stamp).  I can print out the barcode for this plate.
- [x]  Following on from the LCA 10X cDNA plate, I can generate a new plate: LCA Connect PCRXP (stamp). I can print out the barcode for this plate.
- [x] During the LCA Connect PCRXP creation, I can assign tag indexes.
- [x] ~The i7 and i5 tag index dropdown lists are restricted to the relevant tag sets (currently waiting on 10X for what these are)~ see https://github.com/sanger/limber/issues/858

**Dependencies**
This story cannot be completed without the previous plate type existing, and basics of the pipeline being set up. https://github.com/sanger/limber/issues/772

**Comment by KatyTaylor** [comment]
Q's:
1. Names of tags?

**Comment by andrewsparkes** [comment]
The 'offset' functionality is in the custom tagging view in Limber, lets the user re-use a partially used tag plate and offset the start well so they can make efficient use of tag plates when working with sample plates that have <96 samples.

**Comment by KatyTaylor** [comment]
Update following meeting with Stef yesterday: 

* Stef to check on what the 10X single index tag set is called in Limber 
* The tag plates are commercial, not made on site. 10X at the moment don't scan a tag plate barcode into Limber, they select tag sets for i7 and i5 - we could do this for Cardinal as long as works for single index.

Summary from Slack prior to meeting:
They are currently using single index tags, no time line for moving to dual index but could happen in future. Would be good if the software allowed use of either.

Stef: "if we limit it to the 10X single and dual index tags that would be great. Both are already in the system. 10X TT are the dual index ones. I would need to have a look what the single index tags are."

Stephen: "Currently the tag set is "Single Index Plate T Set A  P/N2000240", "Last I asked there is no time line for dual index."

**Comment by sdjmchattie** [comment]
I've sent Stef a list of the existing tag set options and asked how we should decide which should be displayed for the plate creation.

**Comment by KatyTaylor** [comment]
Extra info RE tag sets:

Current 10X tag sets are:
- "Chromium genome 96" (single indexing)
- "10X_Plate TT Set A i7", "10X_Plate TT Set A i5" (dual indexing)
However, because 10X are releasing a new kit, these might not be the ones they use, so Stef's waiting to hear back from 10X what the sequences in the new kit will be.

**Comment by KatyTaylor** [comment]
Split tag set acceptance criteria out into https://github.com/sanger/limber/issues/858 for clarity of tracking
