### ISSUE TITLE
DPL-068 Cardinal - Sample pooling robot driver file

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#768]
**User story**
As a user of the Cardinal pipeline, I need to have a file that I can upload to the Hamilton robot, so that it knows how to transfer samples into the LCA PBMC Pools plate, as determined by https://github.com/sanger/limber/issues/759.

**Who are the primary contacts for this story**
Stef L

**Acceptance criteria**
- The volume of each sample to be added to the pool needs to be calculated from the previously uploaded Cardinal_PBMC_Count file / qc results. 
    - 20,000 cells need to be taken from each sample into the pool. The volume that needs to be taken to achieve this needs to be calculated from the live cell count. E.g. 1,000,000 live cells per ml (20,000/1,000,000) = 0.02ml (20ul). 
  
- A resuspension volume also needs to be specified per pool. The volume is fixed and specified in Figure 4.  

![image](https://user-images.githubusercontent.com/10407809/124908187-f6ba3980-dfe0-11eb-8230-05e1d48b4f34.png)

_Figure 4: resuspension volume_

- The LIMS needs to generate a Hamilton driver file that states: source plate, source well, destination plate, destination well, sample volume and resuspension volume. The destination well identifies the pool e.g. all samples going into well A1 are in a single pool. The sample volume reflects the amount of sample volume that needs to go into the pool (20,000 cells per sample). The resuspension volume is taken from Figure 4 and depends on the number of samples in the pool.
**UPDATE: this was actually implemented as resuspension volume = 3.125 * num samples**

Example file: [LIMS_Pool_Example.csv](https://github.com/sanger/limber/files/7084772/LIMS_Pool_Example.csv)
More realistic example file (from running integration suite test after development: [hamilton_pooling_plate_pbmc.csv](https://github.com/sanger/limber/files/7718239/hamilton_pooling_plate_pbmc.csv)

**Dependencies**
pipeline setup - https://github.com/sanger/limber/issues/772
Probably blocked by https://github.com/sanger/limber/issues/759 - or maybe need to be thought about together.

**Comment by andrewsparkes** [comment]
See Limber exports_controller.rb and the file_links in config/purposes files to see how to make the csv file download links.

**Comment by KatyTaylor** [comment]
Info from Slack:

Andrew Sep 3rd

> Hamilton driver file question: Do you remember when we have files to drive robots downloadable from Limber, we have a value (we call it workflow) in the upper left cell in the csv that says something like '10X VDJ Post Ligation SPRI', 'Sample Dilution', '10X VDJ Post Target Enrichment 2 Double SPRI' etc. Is that value required by the Hamilton method to recognise the file as valid?

Stef

> it depends on how the hamilton method is written. i believe for this method we don't need such a header. but i will email colin who wrote the method to double check. i typically create such headers as my pipelines tend to have multiple driver files uploaded. the header ensures that the correct file is used for the correct step. here we only have one driver file so we should be fine without the header.

> just to confirm - no header in a1 is needed. the files are just as they are
