### ISSUE TITLE
DPL-071-1 Cardinal - download template for pooling decision

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#769]
**User story**
As a user of the Cardinal pipeline, I would like to be able to download information about the wells on a LCA Connect PCRXP plate, so that I can work out the pooling strategy outside the LIMS.

**Who are the primary contacts for this story**
Stef L

**Acceptance criteria**
I can download a file from the LCA Connect PCRXP plate in Limber, containing the following for each well:
- well ID
- If possible, the number of samples that were previously combined into that particular well (in this story - https://github.com/sanger/limber/issues/759)
- tag index
- Depending on difficulty, implement this for multiple source plates
- The hope is that this file can act as a template for the file that is uploaded in https://github.com/sanger/limber/issues/770

**Dependencies**
This story is blocked by the following dependencies:
pipeline setup - https://github.com/sanger/limber/issues/772
https://github.com/sanger/limber/issues/761

**Comment by andrewsparkes** [comment]
See Limber exports_controller.rb and the file_links in config/purposes files to see how to make the csv file download links.

**Comment by KatyTaylor** [comment]
Added research flag as a bit of investigation is required on our (developer) side to figure out how the custom pooling works.
