### ISSUE TITLE
DPL-072 Cardinal - Custom pooling (M)

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#770]
**User story**
As a Cardinal pipeline user, I need to pool together samples from multiple LCA Chromium Connect PCR XP plates, into a tube. The wells to be pooled, and the volumes coming from each source well will be set based on the information I upload in a file.

**Who are the primary contacts for this story**
Stef L

**Acceptance criteria**
- Output labware is a tube / tubes called "LCA Custom Pool"
- There is one ~can be one or more~ "LCA Connect PCRXP" input plate~s~ (see additional context)
- Input file format is a csv with headers "Source Well", "Volume to add to pool", and "Dest. well (?)", as in Duplex-seq pipeline
- Look to see if code checks for tag clashes
- I can create more than one child tube by uploading 2 different files.

**Dependencies**
This story is blocked by the following dependencies:
pipeline setup - https://github.com/sanger/limber/issues/772

**Additional context**
Update after into to LIMS with Stef & Cardinal team on  30/09/2021:

Stef is assuming this page only allows pooling from one plate into multiple tubes, rather than multiple plates into multiple tubes - this can be achieved using 'poolings/new' afterwards

**Comment by andrewsparkes** [comment]
Existing custom pooling functionality in Limber should work for this, although not sure about volume to transfer.

**Comment by KatyTaylor** [comment]
research label added for same reason as on https://github.com/sanger/limber/issues/769
