### ISSUE TITLE
DPL-062 Cardinal pipeline - integration test

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#771]
**User story**
As a developer I would like to have an integration test in the integration suite repo for the new Cardinal pipeline, to catch any bugs in future and to act as documentation for the pipeline.

**Who are the primary contacts for this story**
Stef L, Katy

**Acceptance criteria**
- Integration Suite has an integration test for the main route(s) through the cardinal pipeline.

**Dependencies**
This story is blocked by the following dependencies:
Other Cardinal pipeline stories (although basic version could be made early, and updated as stories get finished).

**Comment by andrewsparkes** [comment]
Recommend iterative approach to this as suggested above, develop it as fleshing out the other stories.
