### ISSUE TITLE
DPL-074-1 Cell banking - consolidate samples into tubes

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#773]
**User story**
As a member of the Cardinal team, I need to be able to "bank" extracted PBMCs (peripheral blood mononuclear cells), so that the samples can be re-processed if they fail the first time round. 
The second step in this is to transfer to a fluidx tube rack for storage.

**Who are the primary contacts for this story**
Stef L, Stephen W

**Acceptance criteria**

- Stamp from the LCA Blood Bank Plate into LCA PBMC Bank Plate (print barcode).
- Transfer to tubes, barcoded with FluidX tube barcodes
    - Allow the user to provide the tube barcodes - probably by uploading a scan of the tube rack
    - Pool wells that contain the same sample together into a destination tube

**Dependencies**
This story is blocked by the following dependencies:
https://github.com/sanger/limber/issues/764

**Additional context**
N.B. https://github.com/sanger/limber/issues/878 was split out of this story.

The actual transfer will be done by a Hamilton robot. This can be programmed to always transfer the wells in pairs, e.g.
A1 & B1 -> A1, 
C1 & D1 -> B1, etc.
We could also make the pooling decision like this, but it is probably more future-proof to make the decision based on what sample the well contains.

Talked to Danni from sample management about how they normally do transfers to fluidx tube racks - it is currently done through Samples Extraction, but the UX is not good (see separate comment below).

This task will be done by the Cardinal team, although they wil be buying the same equipment that Sample Management use.

**Comment by KatyTaylor** [comment]
To do: add links to new re-racking stories, and fix bug so Danni can continue testing in Samples Extraction

**Comment by KatyTaylor** [comment]
Final part of conversation with Danni about re-racking (email from me to Danni, Andrew, Eduardo.. realised I didn't actually copy in Rich despite saying I did... Subject "Re: Tube rack transfer" Thursday, 22 July 2021 at 17:29):

> Re-racking is something that Sample Management already do regularly (most often for the DDD project). They use the feature in Samples Extraction LIMS to support this. The feature is time consuming and treats tube racks as plates when importing from / exporting to Sequencescape. The upcoming Cardinal pipeline will also require use of this feature, which is why we revisited it now. We think improvements to this feature will benefit Sample Management, but also potentially Tree of Life and Long Read as they also use tubes. We think throughput for Cardinal will be low (~1 rack a day), but I’m confirming this with Stef.
 
> Option 1 (improve Samples Extraction):
Improve re-racking performance (https://github.com/sanger/samples_extraction/issues/137)
Give user feedback when scanning a barcode (previously requested by Laura L - https://github.com/sanger/samples_extraction/issues/116)
 
> Option 2 (move feature to Sequencescape):
Re-racking (https://github.com/sanger/sequencescape/issues/3260)
Stamp plate to tube rack (https://github.com/sanger/sequencescape/issues/3261)
 
> I think as a dev team we would prefer to do option 2, however it does bring up all those questions around tube racks again, which led to the group of issues in the housekeeping backlog that we never got round to doing.
 
> I think I would vote for option 2, but try to only take one step in the tube rack direction rather than having to do all of the stories at once (Eduardo’s suggestion for this was to create the functionality in Sequencescape but give the option to create a plate out of it rather than a tube rack, which would be the same as what Samples Extraction currently does).

**Comment by KatyTaylor** [comment]
Asked Stef following:

> I had been thinking that it would be necessary for the lab users to switch into Samples Extraction LIMS, from Limber, for this last step, as Samples Extraction has some support for tube racks. However, as far as I know, Cardinal does not require ‘re-racking’, instead it’s a simple stamp from a plate into a tube rack. Also, when Samples Extraction outputs its results to Sequencescape, they are actually represented as plates rather than tube racks. Therefore, I think Samples Extraction offers no advantages over just having one more step in the Limber cell banking pipeline, where the final ‘tube rack’ will be represented as a ‘plate’.
>  
> My question is:
>  
> Would the following be OK for a first version of the Cardinal cell banking pipeline:
> Final step in the Limber cell banking pipeline performs stamp from ‘LCA PBMC Bank Plate’ into a new plate type called something like ‘LCA PBMC Bank Tube Rack’
> ‘LCA PBMC Bank Tube Rack’ is represented as a plate in the LIMS, not a tube rack
> This means that you would have to print out a ‘DN…’ label for it, and stick that on the tube rack
> It also means that the individual tube barcodes would not be recorded

**Comment by KatyTaylor** [comment]
Answer to above from Stef's meeting with the Cardinal team to introduce them to the LIMS:

Stephen was fine with the tube rack being represented as a plate. Dominique had reservations because in her previous workplace there had been mix-ups where tubes swapped positions in a rack. I think they were in agreement that we could proceed with the above plan for the first version, with the potential of improving support for tube racks in the future.

Curve ball from that meeting - they want to be able to pool different wells together into the same tube. For example, they will array the same sample into wells A1 and B1 on the first plate, and then pool them both together into the same tube in position A1 on the tube rack.

**Comment by KatyTaylor** [comment]
Started a branch for this - https://github.com/sanger/limber/tree/DPL-074-banking-transfer-to-tube-rack

Just added the new plate to represent the tube rack so far. Unsure how to do the pooling step - maybe a version of custom pooling but for destination plates rather than tubes? Or just build some tube rack functionality?

**Comment by andrewsparkes** [comment]
After discussion today with Stephen, Scott, Lesley, Laura, Katy and myself, we decided the following:
- PSD will allow flexible layout of samples from the Vac tubes in the plate, so it doesn't have to be just pairs
- R&D will develop a file-driven Hamilton liquid handler program, rather than a fixed paired layout one
- PSD will upload a tube rack scan file to give us the FluidX barcodes and the layout in the rack, Stephen to supply an example (ideally want the rack barcode in the filename, option then to display that somewhere on the LIMS screen as a simple manual bed verification check for user setting up Hamilton)
- PSD will create a Hamilton driver file to run the liquid handler step flexibly, and if easy to do will add sample information in that file as a stop gap measure to help Laura (originating Vac tube barcode, sample identifier)
