### ISSUE TITLE
DPL-075 new LCM (low-input) combined DNA- & RNA-seq pipeline

### ISSUE THREAD

**Issue by rl15** [sanger/limber#775]
**Description**
DPL-075 As R&D lead (Scott G) I would like new LCM (low-input) combined DNA- & RNA-seq pipeline which is an expansion of the current LCM DNA pipeline

**Who the primary contacts are for this work**
Scott G
Stephen I

**Initial request copy & paste from RT 719477**
This is coming from a faculty demand for simultaneous sequencing of genomes and transcriptomes of low-input material. The basic idea is that samples going into the pipeline will be split into two volumes, with half going down the DNA library-prep pipeline (which is completely identical to the current pipeline) and half going down the RNA pipeline, which is broken into an initial preamplification step followed by a library prep which is basically identical to the DNA pipeline. There’s one additional complication, which is that the samples coming into the pipeline will be supplied in partially filled plates for practical reasons (max 24 samples in three columns of a 96, same layout every time), so the very first thing that needs to happen before anything else is a consolidation of four partially filled plates into a single 96. I think you may have built something conceptually similar to this for one of Stefanie Lensing’s 10x pipelines before now, although I believe she needed a lot more flexibility than I do. I have a basic Powerpoint-style description of what I’m trying to do that I can give you, although if you’re looking for a full process map then I’m going to need to corner Scott T at some point as I don’t have any experience of using Omnigraffle.

**Additional context or information**
Raised initially as RT: https://rt.sanger.ac.uk/Ticket/Display.html?id=719477
Google Doc: https://docs.google.com/document/d/1s5AvMllBHZzMpx85simlCivBSmnfctJ5cwl_AXJFF5I/edit#heading=h.b6x6g0667xkv 
[Combined LCM DNA- & RNA-seq.pdf](https://github.com/sanger/limber/files/6901446/Combined.LCM.DNA-.RNA-seq.pdf)

**Comment by stevieing** [comment]
#789 
#788 
#787
#786

**Comment by JamesGlover** [comment]
Gone through and added a few comments to the stories, mostly either fleshing out background, or indicating where we'll need more details.

There's also another requirement hidden in there, which I'll stick under Sequencescape at the moment, but I'm not 100% sure how best to approach:
https://github.com/sanger/sequencescape/issues/3282

**Comment by rl15** [comment]
Analysis complete on 10 August: 5 backlog items the 'Peach puff' set DPL-098, 099, 100, 101 & 113 (Steve & James)
