### ISSUE TITLE
DPL-099 As Scott after Lysate Plate Consolidation I need to split of the total volume of lysate in each well (50ul) into two equal 25ul fractions on different plates [ToR 12]

### ISSUE THREAD

**Issue by stevieing** [sanger/limber#787]
**User story**
After Lysate Plate Consolidation I need to split of the total volume of lysate in each well (50ul) into two equal 25ul fractions on different plates

It may be not needed and could have changes in future, so this story will need to validate if the volume is needed to be tracked and if it is going to change in future without us being noticed (in that case we may end up tracking wrong data).

**Who are the primary contacts for this story**
Scott / Steve

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Validate with users if this volume setting in the transfer may change in future and if is important to have this or not

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by stevieing** [comment]
This permits the separate downstream processes that are required for DNA-seq and RNA-seq.

**Comment by harrietc52** [comment]
[Combined.LCM.DNA-.RNA-seq.pdf](https://github.com/sanger/limber/files/6930116/Combined.LCM.DNA-.RNA-seq.pdf)

**Comment by JamesGlover** [comment]
Google doc: https://docs.google.com/document/d/1s5AvMllBHZzMpx85simlCivBSmnfctJ5cwl_AXJFF5I/edit

**Comment by JamesGlover** [comment]
As no CSV is required for this process, this is handled by configuration of the pipelines and the bravo robot.

If we don't track the `cherrypick?` plate, things are a little more complicated, as the consolidation step https://github.com/sanger/limber/issues/786 will need to spit out two children, not just one. (I can't remember if we do this elsewhere or not. I know it was discussed.)

**Comment by JamesGlover** [comment]
Some considerations wrt mapping each plate to the correct request type:
https://github.com/sanger/sequencescape/issues/3282

**Comment by JamesGlover** [comment]
See https://github.com/sanger/limber/issues/786 for discussion on the tracking of cherrypicked? plate. But in summary, it is probably easiest if the cherrypicked plate is untracked.

**Comment by KatyTaylor** [comment]
Closing, as is in Done column.
