### ISSUE TITLE
DPL-100 As developers we need to create the pipeline configuration and plate purposes for the new Combined LCM DNA / RNA-seq pipeline [ToR 12]

### ISSUE THREAD

**Issue by stevieing** [sanger/limber#788]
**User story**
As developers we need to create the pipeline configuration and plate purposes for the new Combined LCM DNA / RNA-seq pipeline.

**Who are the primary contacts for this story**
Scott / Steve

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Limber configurations
- [ ] Integration Suite Test

**Dependencies**
This story is blocked by the following dependencies:
Other Combined LCM stories

References
This story has a non-blocking relationship with:
NA

**Additional context**
See other LCM stories

**Comment by harrietc52** [comment]
[Combined.LCM.DNA-.RNA-seq.pdf](https://github.com/sanger/limber/files/6930119/Combined.LCM.DNA-.RNA-seq.pdf)

**Comment by JamesGlover** [comment]
The pdf says that the WGS equivalent part of the pipeline matches the current process, yet the purposes and process don't quite match up. I'm assuming we'd need new purposes here? 

Existing WGS
LB Cherrypick => LB Shear
LB Shear =>  LB Post Shear
LB Post Shear => LB End Prep
LB End Prep => LB Lib PCR
LB Lib PCR => LB Lib PCR-XP

Also, do we have information about which plates need to be tracked.
- Genomic XP
- Ligation
- AL Libs
Never leave the robot, which usually means they are untracked.

Assuming the above are untracked we have:
LB Cherrypick => LCMB LB End Prep
LCMB LB End Prep => LCMB Lib PCR
LCMB Lib PCR => LCMB Lib PCR XP

It would be possible to configure a new pipline reusing the existing purposes.
