### ISSUE TITLE
DPL-112 - add ability to generate normalisation template [Heron] [TOR-67]

### ISSUE THREAD

**Issue by stevieing** [sanger/limber#795]
**User story**
add ability to generate normalisation template [Heron]

**Who are the primary contacts for this story**
Iraad / Steve / James

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] I would like to be able to generate a normalisation template
- [ ] ...

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**
More information required from R&D

A meeting about Tapestation for Stef's work led to a conversation about this work for Naomi as well.  See https://github.com/sanger/quanthub/issues/102#issuecomment-906259713

**Comment by stevieing** [comment]
[Tapestation dispense tracking](https://lucid.app/lucidchart/ec04b099-acaf-46fd-ae5b-215772e1b866/edit?shared=true&page=nCgXyNn_.Gv-#)

**Comment by JamesGlover** [comment]
This story was due to a misunderstanding of the requirements. Instead the information should be displayed on a per-tube basis.

**Comment by JamesGlover** [comment]
Replaced by https://github.com/sanger/limber/issues/903
