### ISSUE TITLE
DPL-102 - As a developer I need to add the plate purposes required for the new Combined.LCM DNA / RNA-seq pipeline [ToR 12]

### ISSUE THREAD

**Issue by stevieing** [sanger/limber#796]
**User story**
As a developer I need to add the plate purposes required for the new Combined.LCM DNA / RNA-seq pipeline

**Who are the primary contacts for this story**
Scott / Steve

**Acceptance criteria**
The following plate purposes are required but some of them may already be available:
- [ ] RNASeq cherrypick
- [ ] RNA XP
- [ ] RNA XP in buffer
- [ ] RNA XP in RT mix
- [ ] RNA XP in preamp mix

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by JamesGlover** [comment]
Move issue to Limber as that's in charge of its own plate purposes.

**Comment by stevieing** [comment]
closed in favour of #788
