### ISSUE TITLE
DPL-069-2 Chromium connect restrict tag set list (S)

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#858]
**User story**
As a user of the Cardinal pipeline, I would like the tag set list on the page between the LCA 10X cDNA plate and the LCA Connect PCRXP plate to be restricted to just those that are relevant to me, to save time trying to find the right one.

**Who are the primary contacts for this story**
Stef, Katy, Stuart

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Tag sets in i7 and i5 lists are restricted to: <TBC>

**Dependencies**
Split out from https://github.com/sanger/limber/issues/760 for clarity of tracking

**Comment by sdjmchattie** [comment]
From Stef:

> The dual index set is 10X TT set A i7 and 10X TT set A i5.

There will be confirmation of the single index set soon.
