### ISSUE TITLE
DPL-144 - I need to be able to charge different amounts for the Duplex-seq and Targeted NanoSeq pipelines at the ‘charge and pass’ point. To do so we need to be able to distinguish between the two sample types e.g. through a different library type (S)

### ISSUE THREAD

**Issue by stevieing** [sanger/limber#861]
**User story**
I need to be able to charge different amounts for the Duplex-seq and Targeted NanoSeq pipelines at the ‘charge and pass’ point. To do so we need to be able to distinguish between the two sample types e.g. through a different library type. 

**Who are the primary contacts for this story**
Stef

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Although we are using the same LIMS pipeline for both Duplex-seq and Targeted NanoSeq we can charge different amounts at the ‘charge and pass’ step. The amount charged is determined by a differentiator e.g. library type. 
- [ ] ...

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by stevieing** [comment]
Small and just config I think, add an extra library type to the Limber high_throughput_duplex_seq pipeline yml file, and in SS to the RequestTypeConstructor in limber.rake (if memory serves this new library type may have to be manually added via the rails console in the various environments as the request type already exists)

Then SSRs just need to use the new library type when setting up the submissions.

**Comment by andrewsparkes** [comment]
I think we just need to add an extra library type to the Limber high_throughput_duplex_seq pipeline yml file, and in SS to the RequestTypeConstructor in limber.rake (if memory serves this new library type may have to be manually added via the rails console in the various environments as the request type already exists).
Then SSRs just need to use the new library type when setting up the submissions.

**Comment by andrewsparkes** [comment]
Note there are Sequencescape and Limber elements to this story.

Post deployment:
Check the new library type is connected to the duplex seq request type using the rails console in each environment.
If not it can be connected with the following:
$ rt = RequestType.find_by(name: 'Limber Duplex-Seq')
$ lt = LibraryType.find_by(name: 'Targeted Nanoseq')
$ rt.library_types << lt
