### ISSUE TITLE
DPL-074-2 Cell banking - what's in my tube rack? (C=M, V=4)

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/limber#878]
**User story**
As a member of the BioResource team, I would like the Cardinal team to provide, along with the physical tube rack, information as to what samples are in that tube rack.

**Who are the primary contacts for this story**
Stephen W (HumGen Cardinal team), Laura L (BioResource team)

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Input: csv from scanning a tube rack (format TBC) 
- [ ] Output file containing: 
    - original tube barcode (= 'supplier_name', from sample metadata)
    - original tube collection site (= 'collected_by', from sample metadata)
    - new fluidx tube barcode
    - new rack barcode

**Dependencies**
This story is blocked by the following dependencies:
- https://github.com/sanger/limber/issues/773

**Additional context**
The following option is the preferred one for implementing this:
- "What's in my tube rack?" utility page (probably makes most sense in Sequencescape?) - give it csv of tube rack scan, it returns output file in format requested

The following options for implementing this were also discussed:
- Tableau report as stop-gap - give it list of tube barcodes, it returns sample supplier names (= "original tube barcode")
- Tube rack creation page - give it csv of tube rack scan, it creates tube rack in SS - then export required information from the tube rack page (could be generic export for any labware, in SS or Limber)

We also discussed providing links between labware pages in SS and Limber, to make switching between apps easier if needed.

There is a manual workaround.

**Comment by stevieing** [comment]
Need a tube rack csv but they are available wrangler and samples extraction.

**Comment by KatyTaylor** [comment]
> Need a tube rack csv but they are available wrangler and samples extraction.

Update on this - the format of tube rack csv the Cardinal team are getting from their scanner machine is different from that in Sample Management, and it's causing them to have to manually edit the file so that Limber can accept it - Stephen is looking into whether the scanner can be configured to change format. 

Relevant to this story when deciding what format(s) of csv to accept.

**Comment by KatyTaylor** [comment]
Reopening as might be needed in 007c project
