### ISSUE TITLE
DPL-172 As Stef L. I would like additional features beyond MVP added the Targeted NanoSeq pipeline so that reporting is more detailed

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/limber#913]
**User story**
DPL-172 As Stef L. I would like additional features beyond MVP added the Targeted NanoSeq pipeline so that reporting is more detailed

**Who are the primary contacts for this story**
Stef L.

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] NPG support a new library type in the analysis stage - not force it through as "Duplex Seq'
- [x] Samples enter as currently for Duplex-seq (LDS stock plate and associated manifest). The stock plate could be renamed to LTN stock.
- [ ] Enable cherrypick functionality in sequencescape. Use the cherrypick functionality that is available in sequencescape. This will enable a cherrypick plate to be created in sequencescape by combining several stock plates. The cherrypick is carried out on the Tecan - use the existing sequencescape bed verification and Tecan GWL file generation functionalities. Output plate LTN Cherrypick.
- [ ] For samples that don’t need to be cherrypicked the LTN stock plate can be converted to a LTN Cherrypick plate in sequencescape. This feature is implemented in #928
- [ ] The supplied material is sheared by sonication:- this feature is implemented in #928
- Bed verification should be available for the Bravo (cherrypick plate on position 7, shear plate onto position 9. 
- [x] ‘Add an empty LTN Post Shear plate’ (print label). 
- Bed verification on Bravo (shear plate onto position 9 and post shear plate onto position 7). 
- [x] Pipeline now progresses similarly to Duplex-seq pipeline:
Create a LTN AL-Lib plate, with this plate creation several labels are printed:
-   LTN End repair
-   LTN A-Tail
-   LTN Ligation
-   LTN AL-lib
-   LTN AL-lib stamp
-   LTN AL-lib QC1
-   LTN A-lib QC2 (384 well plate label)
- [ ] QC2 data is qPCR data that is uploaded to quanthub using the existing Duplex-seq AL-LIB quant type.
- [ ] A similar qPCR file output is generated as for the duplex-seq pipeline. This is populated by faculty and then re-uploaded in Limber as is the case for the Duplex-seq pipeline. Use the existing template but remove the following columns: 
- submit for sequencing
- sub-pool
- coverage
- [ ] Add a new LTN Dil plate (print barcode). 
- The Dil plate also has a hamilton dilution driver file which works exactly as the Duplex-seq driver file (same rules and takes the same information from the previously uploaded file). 
- Hamilton bed verification as for Duplex-seq.
- PCR cycle binning: samples need to be binned into different cycles based on upload (as for Duplex-seq)
- [ ] Add a new LTN PCR plate (print barcode) and allow index set selection (pWGS)
- [ ] Add a new LTN PCR XP plate (print barcode)
- [ ] A quant file for the LTN PCR XP Plate can be uploaded to quanthub using the existing Duplex-seq library quant type.
- [ ] On the LTN PCR XP plate enable download of a file that states: Plate Barcode, Plate ID, Sanger Sample ID, Sample Name, Input amount desired (from the previous customer upload), Concentration (from the quant file uploaded to quanthub using the Duplex-seq Library quant type). 
- [ ] This plate is then treated like an LCMB plate progressing to ISC. A ReISC type submission will be placed on the LTN PCR XP plate. It then goes down the same process as existing ReISC submission:
- LB Lib PCR-XP (new plate ID for ReISC)
- LB Lib PrePool
- LB Hyb
- LB Cap Lib
- LB Cap Lib PCR
- LB Cap Lib PCR-XP
- LB Cap Lib Pool
- LB Lib Pool Norm.
- [ ] The final sequencing submission is made by the operational team as is currently the case for ReISC. 

**Dependencies**
#928 

**References**
Link to word doc from Stef 
https://docs.google.com/document/d/1MGKqqXoqsgTSwr3FsnIBoCPPZJi1mqVa/edit?usp=sharing&ouid=104941231716000289616&rtpof=true&sd=true

**Additional context**
This came out of discussions around the changes we made to accommodate the Targeted Nanoseq pipeline within the existing Duplex Seq pipeline, and the conclusion that this was not really appropriate and that it should have it’s own pipeline.
 
Sample management are not comfortable to proceed without the shearing steps (bullet points: 4+5) to be LIMS integrated. So a minimal requirement would be to add this as an optional step to the duplex-seq pipeline (this step is not required for duplex-seq itself). 
Furthermore the 2 new library types (bullet point: 15) would also need to be implemented.

**Comment by TWJW-SANGER** [comment]
I have extracted the MVP parts of this story into #928 so that they can be prioritised separately.

**Comment by andrewsparkes** [comment]
Emailed Stef to check if still relevant.

**Comment by andrewsparkes** [comment]
12th April: Stef says additional changes will be required and she needs to meet with the team running the pipeline to finalise the requirements.
Returning to backlog.
