### ISSUE TITLE
DPL-183 As Stef L. I would like the MVP features for a new Targeted NanoSeq  pipeline so that we can accurately track, process and report samples (C=?, V=4)

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/limber#928]
**User story**
As Stef L. I would like the MVP features for a new Targeted NanoSeq  pipeline so that we can accurately track, process and report samples.

**Who are the primary contacts for this story**
Stef L.

**Acceptance criteria**
To be considered successful the solution must allow:

- [x]  For samples that don’t need to be cherrypicked the LTN stock plate can be converted to a LTN Cherrypick plate in sequencescape.
- [x] New plate purposes - prefixed LTN instead of LDS #913 
- [x]  The supplied material is sheared by sonication. Upon scanning the LTN Cherrypick plate into Limber enable ‘Add an empty LTN shear plate’ (print labels).
- [x] Bed verification should be available for the Bravo (cherrypick plate on position 7, shear plate onto position 9)
- [x] ‘Add an empty LTN Post Shear plate’ (print label). 
- [x] Bed verification on Bravo (shear plate onto position 9 and post shear plate onto position 7).
- [x]  Two new library types are required for the Re-ISC submission: Targeted NanoSeq Pulldown Twist and Targeted NanoSeq Pulldown Agilent.
- [x] An integration suite test
- [x]   The final sequencing submission is made by the operational team as is currently the case for ReISC.

**Dependencies**

References
This story has a non-blocking relationship with:
#913 

**Additional context**
This came out of discussions around the changes we made to accommodate the Targeted Nanoseq pipeline within the existing Duplex Seq pipeline, and the conclusion that this was not really appropriate and that it should have it’s own pipeline.

Ops have a workaround for this BUT it involves the submission of plates with **handwritten barcodes** and shearing in SM without sample tracking.
This will not scale to volumes of samples expected in Jan 2022.

**Comment by stevieing** [comment]
[Targted Duplex-seq Process map.pdf](https://github.com/sanger/limber/files/7677209/Targted.Duplex-seq.Process.map.pdf)

**Comment by andrewsparkes** [comment]
NB. On deploying we need to check the following request types via the rails console (as the configuration changes in the code do not update request types that already exist).
Check request type 'Limber ISC' does **not** have the 'Targeted Nanoseq Pulldown Twist' and '.. Agilent' library types.
Check request type 'Limber ReISC' **does** have the 'Targeted Nanoseq Pulldown Twist' and '.. Agilent' library types.
Check request type 'Limber Targeted Nanoseq' only has the 'Targeted Nanoseq' library type and not the Twist and Agilent ones.
e.g.
```
rt = RequestType.find_by(name: 'Limber Targeted Nanoseq')
rt.library_types
lt  = LibraryType.find_by(name: 'name of library type')
```
to add a library type to list:
`rt.library_types << lt`
to remove from list:
`rt.library_types.delete(lt)`
