### ISSUE TITLE
DPL-191 - enable the heron ARTIC stamp method on the Hamilton platform (C=S, V=5)

### ISSUE THREAD

**Issue by stevieing** [sanger/limber#935]
**User story**
As a member of R&D (Lesley S) I would like to add a Hamilton robot to the heron LIMS for the production of the LTHR-384 PCR 1 and 2 plates from the LTHR-384 RT plate. This will be in addition to the Bravo robot bravo LTHR-384 RT to LTHR-384 PCR 1 and 2, which already supports this process (image below) to enable contingency capacity for the ARTIC stamp process we have a Hamilton robot coming online.

![Picture1](https://user-images.githubusercontent.com/519327/145570798-700e538f-b4eb-4835-9aa0-ffee9f18e7a9.png)

**Who are the primary contacts for this story**
Lesley

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] The Hamilton robot should appear as an additional option to the Bravo robot:
- Robot name: Hamilton LTHR-384 RT
- Bed verification:
- Destination plate: Bed 2
- LTHR-384 PCR 1: Bed 1
- LTHR-384 PCR 2: Bed 3
- 

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by JamesGlover** [comment]
- Slightly adjusted the robot name to match the same format as the bravo.
- Tested via setting up an integration suite run, and took it through to the robot step, before using the Hamilton instead.
