### ISSUE TITLE
DPL-213 - As a lab user I would like to see a warning if there is a pool with a concentration of less than 4nM after being quanted on the tapestation (C=S, V=4)

### ISSUE THREAD

**Issue by stevieing** [sanger/limber#961]
**User story**
I ran a tapestation run yesterday and one of the pools failed. I deselected all the samples to remove them from the average on quanthub, and this allowed a submission of a concentration of 0nM to LIMBER for that pool (see first image below). If I go to validate the tubes (second image) it says to add 192uL to the norm tubes. I was wondering if LIMBER has an error message that displays if the concentration is below 4nM that maybe didn't show because it was 0nM? If there is no error message/warning about pools below 4nM I think it might be helpful for this to be added so no one makes mistakes thinking the norm tube is 4nM.

**Who are the primary contacts for this story**
Sara / Steve / Stuart

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] If the pool has a concentration of less than 4nM the page should show a warning
- [ ] ...

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**
![pastedImage](https://user-images.githubusercontent.com/519327/148047612-c0fc1023-9fc7-49b4-8f5f-553bdb52ba4b.png)

![pastedImage](https://user-images.githubusercontent.com/519327/148047628-88719774-b8a6-4b75-bffe-a0f4bf8fcc22.png)

**Comment by stevieing** [comment]
email from Stuart (21/12): I don’t see there being a problem with that change in January.  The reason it behaves the way it does at the moment is that during requirements gathering we were told if the volume is below 4nM already, then we should transfer the maximum we can and add no buffer.  I can see why it would be good to advise the user of that situation.
 
On the flip side, if it turns out the concentration of the Pool XP tube were more than 384 nM, it also only advises you to pick 2µL of the sample, which gives you more than a 4nM Pool Norm tube.  We were advised 2µL should be the minimum pick for the sample.  Does that behaviour also need flagging with a prompt?

email from Sara (22/12): Thanks for the prompt reply.
I think when we set out the requirements, we were receiving fairly standard concentrations of pools, but we now more regularly see pools below the 4nM template required for sequencing, so that flag would definitely help the team immediately see this issue.  We usually re-quant a pool below 4nM to confirm and then a workaround at sequencing is required so that the pool is still of sufficient template to load.
 
On the flip side, a pool of over 384nM would be super rare (I haven’t seen anything over about 80nM), so a pool this high would indicate a potential issue with the quantification step - probably worth a flag in the system for the team to look at this carefully.

**Comment by sdjmchattie** [comment]
I tested this in UAT to confirm the message appears.  When the concentration of the source is adequate, the UI remains unchanged:

![image](https://user-images.githubusercontent.com/1999241/150303592-2937ec8d-3cce-444e-ba77-6e62e8009453.png)

When the source tube has a molarity below 4 nM, the warning is shown:

![image](https://user-images.githubusercontent.com/1999241/150303661-5b5e4f2b-2e9e-49e5-9573-309e8d65d3f6.png)
