### ISSUE TITLE
DPL-252 Combined LCM - Bed verification for Split Step

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/limber#984]
**User story**
The current bed verification classed do not cope with the scenario where we have both multiple parents and multiple children, which is the case with the initial step in the Combined LCM pipeline. We as PSD need to modify or subclass one of the existing bed verification robot classes to allow for this functionality.

**Who are the primary contacts for this story**
Andrew
Eduardo

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] verification of the relationships between multiple parents (of one purpose type) split out into multiple (duplicated layout) children (with different purposes) 
- [ ] verification of the order of the sources (by column layout on the destination) as in PoolingRobot class

**Dependencies**
This story is blocked by the following dependencies:
na

References
This story has a non-blocking relationship with:
Combined LCM stories

**Additional context**
PoolingRobot does the correct checking of source plate order.
SplittingRobot does the split out to multiple children and has clearer configuration.

Combined LCM has 1-4 sources, 24 samples in each in columns 1-3
There are DNA and RNA destination plates, with matching layouts.
In reality there is an intermediate plate, untracked.
There are fixed transfers columns depending on source, so source 1 (cols 1-3) go into cols 1-3 on the destinations, source 2 (cols 1-3) go into cols 4-6 on the destinations, source 3 (cols 1-3) go into cols 7-9 on the destinations, and source 4 (cols 1-3) go into cols 10-12 on the destinations.

**Comment by andrewsparkes** [comment]
Required for LCM go live. Small story (hopefully).

**Comment by KatyTaylor** [comment]
Closing, as is in Done column.
